-- Generated by refresh-legacy-schema-artifacts.mjs
-- Source dialect: sqlite
-- Source root: drizzle/sqlite/migrations
CREATE TABLE `assignee` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	CONSTRAINT `fk_assignee_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_assignee_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `attachment` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text DEFAULT NULL,
	`hash` text DEFAULT NULL,
	`container_type` text DEFAULT NULL,
	`mime_type` text DEFAULT NULL,
	`size` integer DEFAULT NULL,
	`container_id` integer NOT NULL,
	`created_date` integer DEFAULT NULL,
	`owner_login_id` text DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `comment_thread` (
	`dtype` text NOT NULL,
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`state` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`pull_request_id` integer DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`prev_commit_id` text DEFAULT NULL,
	`commit_id` text DEFAULT NULL,
	`path` text DEFAULT NULL,
	`start_side` text DEFAULT NULL,
	`start_line` integer DEFAULT NULL,
	`start_column` integer DEFAULT NULL,
	`end_side` text DEFAULT NULL,
	`end_line` integer DEFAULT NULL,
	`end_column` integer DEFAULT NULL,
	CONSTRAINT `fk_comment_thread_pull_request_id_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_request`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_comment_thread_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `comment_thread_n4user` (
	`comment_thread_id` integer NOT NULL,
	`n4user_id` integer NOT NULL,
	CONSTRAINT `fk_comment_thread_n4user_comment_thread_id_comment_thread_id_fk` FOREIGN KEY (`comment_thread_id`) REFERENCES `comment_thread`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_comment_thread_n4user_n4user_id_n4user_id_fk` FOREIGN KEY (`n4user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`comment_thread_id`, `n4user_id`)
);
--> statement-breakpoint
CREATE TABLE `commit_comment` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`project_id` integer DEFAULT NULL,
	`path` text DEFAULT NULL,
	`line` integer DEFAULT NULL,
	`side` text DEFAULT NULL,
	`contents` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`commit_id` text DEFAULT NULL,
	CONSTRAINT `fk_commit_comment_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `email` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`email` text DEFAULT NULL,
	`valid` integer DEFAULT false,
	`token` text DEFAULT NULL,
	CONSTRAINT `fk_email_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `favorite_issue` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`issue_id` integer DEFAULT NULL,
	CONSTRAINT `fk_favorite_issue_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT `fk_favorite_issue_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `favorite_organization` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`organization_id` integer DEFAULT NULL,
	`organization_name` text DEFAULT NULL,
	CONSTRAINT `fk_favorite_organization_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT `fk_favorite_organization_organization_id_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `favorite_project` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`owner` text DEFAULT NULL,
	`project_name` text DEFAULT NULL,
	CONSTRAINT `fk_favorite_project_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT `fk_favorite_project_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `issue` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text DEFAULT NULL,
	`body` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`updated_date` integer DEFAULT NULL,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`number` integer DEFAULT NULL,
	`num_of_comments` integer DEFAULT NULL,
	`state` integer DEFAULT NULL,
	`due_date` integer DEFAULT NULL,
	`milestone_id` integer DEFAULT NULL,
	`assignee_id` integer DEFAULT NULL,
	`history` text DEFAULT NULL,
	`parent_id` integer DEFAULT NULL,
	`weight` integer DEFAULT 0,
	`updated_by_author_id` integer DEFAULT NULL,
	`is_draft` integer DEFAULT false,
	CONSTRAINT `fk_issue_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `fk_issue_milestone_id_milestone_id_fk` FOREIGN KEY (`milestone_id`) REFERENCES `milestone`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_issue_assignee_id_assignee_id_fk` FOREIGN KEY (`assignee_id`) REFERENCES `assignee`(`id`) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT `fk_issue_parent_id_01` FOREIGN KEY (`parent_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE SET NULL
);
--> statement-breakpoint
CREATE TABLE `issue_comment` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`contents` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`issue_id` integer DEFAULT NULL,
	`project_id` integer NOT NULL,
	`parent_comment_id` integer DEFAULT NULL,
	CONSTRAINT `fk_issue_comment_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_issue_comment_parent_id_01` FOREIGN KEY (`parent_comment_id`) REFERENCES `issue_comment`(`id`) ON UPDATE RESTRICT ON DELETE SET NULL
);
--> statement-breakpoint
CREATE TABLE `issue_comment_voter` (
	`issue_comment_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	CONSTRAINT `fk_issue_comment_voter_issue_comment_id_issue_comment_id_fk` FOREIGN KEY (`issue_comment_id`) REFERENCES `issue_comment`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_issue_comment_voter_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`issue_comment_id`, `user_id`)
);
--> statement-breakpoint
CREATE TABLE `issue_event` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`created` integer DEFAULT NULL,
	`sender_login_id` text DEFAULT NULL,
	`sender_email` text DEFAULT NULL,
	`issue_id` integer DEFAULT NULL,
	`event_type` text DEFAULT NULL,
	`old_value` text DEFAULT NULL,
	`new_value` text DEFAULT NULL,
	CONSTRAINT `fk_issue_event_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `issue_issue_label` (
	`issue_id` integer NOT NULL,
	`issue_label_id` integer NOT NULL,
	CONSTRAINT `fk_issue_issue_label_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_issue_issue_label_issue_label_id_issue_label_id_fk` FOREIGN KEY (`issue_label_id`) REFERENCES `issue_label`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`issue_id`, `issue_label_id`)
);
--> statement-breakpoint
CREATE TABLE `issue_label` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`category_id` integer DEFAULT NULL,
	`color` text DEFAULT NULL,
	`name` text DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	CONSTRAINT `fk_issue_label_category_id_issue_label_category_id_fk` FOREIGN KEY (`category_id`) REFERENCES `issue_label_category`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_issue_label_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `issue_label_category` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`project_id` integer DEFAULT NULL,
	`name` text DEFAULT NULL,
	`is_exclusive` integer DEFAULT false,
	CONSTRAINT `fk_issue_label_category_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `issue_sharer` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`created` integer DEFAULT NULL,
	`login_id` text DEFAULT NULL,
	`user_id` integer DEFAULT NULL,
	`issue_id` integer DEFAULT NULL,
	CONSTRAINT `fk_issue_sharer_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT `fk_issue_sharer_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `issue_voter` (
	`issue_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	CONSTRAINT `fk_issue_voter_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_issue_voter_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`issue_id`, `user_id`)
);
--> statement-breakpoint
CREATE TABLE `label` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`category` text DEFAULT NULL,
	`name` text DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `linked_account` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_credential_id` integer DEFAULT NULL,
	`provider_user_id` text DEFAULT NULL,
	`provider_key` text DEFAULT NULL,
	`provider_display_name` text DEFAULT NULL,
	`avatar_url` text DEFAULT NULL,
	CONSTRAINT `fk_linked_account_user_credential_id_user_credential_id_fk` FOREIGN KEY (`user_credential_id`) REFERENCES `user_credential`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `mention` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`resource_type` text DEFAULT NULL,
	`resource_id` text DEFAULT NULL,
	`user_id` integer DEFAULT NULL,
	CONSTRAINT `fk_mention_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `milestone` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text DEFAULT NULL,
	`due_date` integer DEFAULT NULL,
	`contents` text DEFAULT NULL,
	`state` integer DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	CONSTRAINT `fk_milestone_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `n4user` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text DEFAULT NULL,
	`login_id` text DEFAULT NULL,
	`password` text DEFAULT NULL,
	`password_salt` text DEFAULT NULL,
	`email` text DEFAULT NULL,
	`remember_me` integer DEFAULT false,
	`state` text DEFAULT NULL,
	`last_state_modified_date` integer DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`lang` text DEFAULT NULL,
	`token` text DEFAULT NULL,
	`is_guest` integer DEFAULT false,
	`english_name` text DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `notification_event` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text DEFAULT NULL,
	`sender_id` integer DEFAULT NULL,
	`created` integer DEFAULT NULL,
	`resource_type` text DEFAULT NULL,
	`resource_id` text DEFAULT NULL,
	`event_type` text DEFAULT NULL,
	`old_value` text DEFAULT NULL,
	`new_value` text DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `notification_event_n4user` (
	`notification_event_id` integer NOT NULL,
	`n4user_id` integer NOT NULL,
	CONSTRAINT `fk_notification_event_n4user_notification_event_id_notification_event_id_fk` FOREIGN KEY (`notification_event_id`) REFERENCES `notification_event`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_notification_event_n4user_n4user_id_n4user_id_fk` FOREIGN KEY (`n4user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`notification_event_id`, `n4user_id`)
);
--> statement-breakpoint
CREATE TABLE `notification_mail` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`notification_event_id` integer DEFAULT NULL,
	CONSTRAINT `fk_notification_mail_notification_event_id_notification_event_id_fk` FOREIGN KEY (`notification_event_id`) REFERENCES `notification_event`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `organization` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text DEFAULT NULL,
	`created` integer DEFAULT NULL,
	`descr` text DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `organization_user` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`organization_id` integer DEFAULT NULL,
	`role_id` integer DEFAULT NULL,
	CONSTRAINT `fk_organization_user_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_organization_user_organization_id_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_organization_user_role_id_role_id_fk` FOREIGN KEY (`role_id`) REFERENCES `role`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `original_email` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`message_id` text DEFAULT NULL,
	`resource_type` text DEFAULT NULL,
	`resource_id` text DEFAULT NULL,
	`handled_date` integer DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `play_evolutions` (
	`id` integer NOT NULL,
	`hash` text NOT NULL,
	`applied_at` integer DEFAULT NULL NOT NULL,
	`apply_script` text DEFAULT NULL,
	`revert_script` text DEFAULT NULL,
	`state` text DEFAULT NULL,
	`last_problem` text DEFAULT NULL,
	PRIMARY KEY (`id`)
);
--> statement-breakpoint
CREATE TABLE `posting` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text DEFAULT NULL,
	`body` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`updated_date` integer DEFAULT NULL,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`number` integer DEFAULT NULL,
	`num_of_comments` integer DEFAULT NULL,
	`notice` integer DEFAULT false,
	`readme` integer DEFAULT false,
	`history` text DEFAULT NULL,
	`parent_id` integer DEFAULT NULL,
	`updated_by_author_id` integer DEFAULT NULL,
	CONSTRAINT `fk_posting_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_posting_parent_id_01` FOREIGN KEY (`parent_id`) REFERENCES `posting`(`id`) ON UPDATE RESTRICT ON DELETE SET NULL
);
--> statement-breakpoint
CREATE TABLE `posting_comment` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`contents` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`posting_id` integer DEFAULT NULL,
	`project_id` integer NOT NULL,
	`parent_comment_id` integer DEFAULT NULL,
	CONSTRAINT `fk_posting_comment_posting_id_posting_id_fk` FOREIGN KEY (`posting_id`) REFERENCES `posting`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_posting_comment_parent_id_01` FOREIGN KEY (`parent_comment_id`) REFERENCES `posting_comment`(`id`) ON UPDATE RESTRICT ON DELETE SET NULL
);
--> statement-breakpoint
CREATE TABLE `posting_issue_label` (
	`posting_id` integer NOT NULL,
	`issue_label_id` integer NOT NULL,
	CONSTRAINT `fk_posting_issue_label_posting_id_posting_id_fk` FOREIGN KEY (`posting_id`) REFERENCES `posting`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_posting_issue_label_issue_label_id_issue_label_id_fk` FOREIGN KEY (`issue_label_id`) REFERENCES `issue_label`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`posting_id`, `issue_label_id`)
);
--> statement-breakpoint
CREATE TABLE `project` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text DEFAULT NULL,
	`overview` text DEFAULT NULL,
	`vcs` text DEFAULT NULL,
	`siteurl` text DEFAULT NULL,
	`owner` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`last_issue_number` integer DEFAULT NULL,
	`last_posting_number` integer DEFAULT NULL,
	`original_project_id` integer DEFAULT NULL,
	`last_pushed_date` integer DEFAULT NULL,
	`default_reviewer_count` integer DEFAULT NULL,
	`is_using_reviewer_count` integer DEFAULT false,
	`organization_id` integer DEFAULT NULL,
	`project_scope` text DEFAULT NULL,
	`previous_owner_login_id` text DEFAULT NULL,
	`previous_name` text DEFAULT NULL,
	`previous_name_changed_time` integer DEFAULT NULL,
	`is_code_accessible_member_only` integer DEFAULT false,
	CONSTRAINT `fk_project_organization_id_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_project_originalProject_23` FOREIGN KEY (`original_project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `project_label` (
	`project_id` integer NOT NULL,
	`label_id` integer NOT NULL,
	CONSTRAINT `fk_project_label_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_project_label_label_id_label_id_fk` FOREIGN KEY (`label_id`) REFERENCES `label`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`project_id`, `label_id`)
);
--> statement-breakpoint
CREATE TABLE `project_menu_setting` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`project_id` integer DEFAULT NULL,
	`code` integer DEFAULT false,
	`issue` integer DEFAULT false,
	`pull_request` integer DEFAULT false,
	`review` integer DEFAULT false,
	`milestone` integer DEFAULT false,
	`board` integer DEFAULT false,
	CONSTRAINT `fk_project_menu_setting_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `project_pushed_branch` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`pushed_date` integer DEFAULT NULL,
	`name` text DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	CONSTRAINT `fk_project_pushed_branch_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `project_transfer` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`sender_id` integer DEFAULT NULL,
	`destination` text DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`requested` integer DEFAULT NULL,
	`confirm_key` text DEFAULT NULL,
	`accepted` integer DEFAULT false,
	`new_project_name` text DEFAULT NULL,
	CONSTRAINT `fk_project_transfer_sender_id_n4user_id_fk` FOREIGN KEY (`sender_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_project_transfer_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `project_user` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`role_id` integer DEFAULT NULL,
	CONSTRAINT `fk_project_user_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_project_user_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_project_user_role_id_role_id_fk` FOREIGN KEY (`role_id`) REFERENCES `role`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `project_visitation` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`project_id` integer DEFAULT NULL,
	`recently_visited_projects_id` integer DEFAULT NULL,
	`visited` integer DEFAULT NULL,
	CONSTRAINT `fk_project_visitation_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `fk_project_visitation_recently_visited_projects_id_recently_visited_projects_id_fk` FOREIGN KEY (`recently_visited_projects_id`) REFERENCES `recently_visited_projects`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `property` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text DEFAULT NULL,
	`value` text DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE `pull_request` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text DEFAULT NULL,
	`body` text DEFAULT NULL,
	`to_project_id` integer DEFAULT NULL,
	`from_project_id` integer DEFAULT NULL,
	`to_branch` text DEFAULT NULL,
	`from_branch` text DEFAULT NULL,
	`contributor_id` integer DEFAULT NULL,
	`receiver_id` integer DEFAULT NULL,
	`created` integer DEFAULT NULL,
	`updated` integer DEFAULT NULL,
	`received` integer DEFAULT NULL,
	`state` integer DEFAULT NULL,
	`is_conflict` integer DEFAULT false,
	`is_merging` integer DEFAULT false,
	`last_commit_id` text DEFAULT NULL,
	`merged_commit_id_from` text DEFAULT NULL,
	`merged_commit_id_to` text DEFAULT NULL,
	`number` integer DEFAULT NULL,
	CONSTRAINT `fk_pull_request_to_project_id_project_id_fk` FOREIGN KEY (`to_project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_pull_request_from_project_id_project_id_fk` FOREIGN KEY (`from_project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_pull_request_contributor_id_n4user_id_fk` FOREIGN KEY (`contributor_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_pull_request_receiver_id_n4user_id_fk` FOREIGN KEY (`receiver_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `pull_request_commit` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`pull_request_id` integer DEFAULT NULL,
	`commit_id` text DEFAULT NULL,
	`author_date` integer DEFAULT NULL,
	`created` integer DEFAULT NULL,
	`commit_message` text DEFAULT NULL,
	`commit_short_id` text DEFAULT NULL,
	`author_email` text DEFAULT NULL,
	`state` text DEFAULT NULL,
	CONSTRAINT `fk_pull_request_commit_pull_request_id_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_request`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `pull_request_event` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`sender_login_id` text DEFAULT NULL,
	`pull_request_id` integer DEFAULT NULL,
	`event_type` text DEFAULT NULL,
	`created` integer DEFAULT NULL,
	`old_value` text DEFAULT NULL,
	`new_value` text DEFAULT NULL,
	CONSTRAINT `fk_pull_request_event_pull_request_id_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_request`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `pull_request_reviewers` (
	`pull_request_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	CONSTRAINT `fk_pull_request_reviewers_pull_request_id_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_request`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_pull_request_reviewers_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`pull_request_id`, `user_id`)
);
--> statement-breakpoint
CREATE TABLE `recent_issue` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`issue_id` integer DEFAULT NULL,
	`posting_id` integer DEFAULT NULL,
	`title` text DEFAULT NULL,
	`url` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	CONSTRAINT `fk_recent_issue_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT `fk_recent_issue_issue_id_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issue`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `recent_project` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`owner` text DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`project_name` text DEFAULT NULL,
	CONSTRAINT `fk_recent_project_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `recently_visited_projects` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	CONSTRAINT `fk_recently_visited_projects_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `review_comment` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`contents` text DEFAULT NULL,
	`created_date` integer DEFAULT NULL,
	`author_id` integer DEFAULT NULL,
	`author_login_id` text DEFAULT NULL,
	`author_name` text DEFAULT NULL,
	`thread_id` integer DEFAULT NULL,
	CONSTRAINT `fk_review_comment_thread_id_comment_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `comment_thread`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `role` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`name` text DEFAULT NULL,
	`active` integer DEFAULT false
);
--> statement-breakpoint
CREATE TABLE `site_admin` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`admin_id` integer DEFAULT NULL,
	CONSTRAINT `fk_site_admin_admin_id_n4user_id_fk` FOREIGN KEY (`admin_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `title_head` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`project_id` integer DEFAULT NULL,
	`head_keyword` text DEFAULT NULL,
	`frequency` integer DEFAULT NULL,
	CONSTRAINT `fk_title_head_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `unwatch` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`resource_type` text DEFAULT NULL,
	`resource_id` text DEFAULT NULL,
	CONSTRAINT `fk_unwatch_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `user_credential` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`login_id` text DEFAULT NULL,
	`email` text DEFAULT NULL,
	`name` text DEFAULT NULL,
	`active` integer DEFAULT false,
	`email_validated` integer DEFAULT false,
	CONSTRAINT `fk_user_credential_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `user_enrolled_organization` (
	`user_id` integer NOT NULL,
	`organization_id` integer NOT NULL,
	CONSTRAINT `fk_user_enrolled_organization_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_user_enrolled_organization_organization_id_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organization`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`user_id`, `organization_id`)
);
--> statement-breakpoint
CREATE TABLE `user_enrolled_project` (
	`user_id` integer NOT NULL,
	`project_id` integer NOT NULL,
	CONSTRAINT `fk_user_enrolled_project_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_user_enrolled_project_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	PRIMARY KEY (`user_id`, `project_id`)
);
--> statement-breakpoint
CREATE TABLE `user_project_notification` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`project_id` integer DEFAULT NULL,
	`notification_type` text DEFAULT NULL,
	`allowed` integer DEFAULT false,
	CONSTRAINT `fk_user_project_notification_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `fk_user_project_notification_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `user_setting` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`login_default_page` text DEFAULT NULL,
	CONSTRAINT `fk_user_setting_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `user_verification` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`login_id` text DEFAULT NULL,
	`verification_code` text DEFAULT NULL,
	`timestamp` integer DEFAULT NULL,
	CONSTRAINT `fk_user_verification_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `watch` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`user_id` integer DEFAULT NULL,
	`resource_type` text DEFAULT NULL,
	`resource_id` text DEFAULT NULL,
	CONSTRAINT `fk_watch_user_id_n4user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `n4user`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `webhook` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`project_id` integer DEFAULT NULL,
	`payload_url` text DEFAULT NULL,
	`secret` text DEFAULT NULL,
	`created_at` integer DEFAULT NULL,
	`git_push` integer DEFAULT false,
	`webhook_type` integer DEFAULT true,
	CONSTRAINT `fk_webhook_project_id_project_id_fk` FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE `webhook_thread` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`webhook_id` integer DEFAULT NULL,
	`resource_type` text DEFAULT NULL,
	`resource_id` text DEFAULT NULL,
	`thread_id` text DEFAULT NULL,
	`created_at` integer DEFAULT NULL,
	CONSTRAINT `fk_webhook_thread_webhook_id_webhook_id_fk` FOREIGN KEY (`webhook_id`) REFERENCES `webhook`(`id`) ON UPDATE RESTRICT ON DELETE CASCADE
);
--> statement-breakpoint
CREATE INDEX `ix_assignee_project_2` ON `assignee` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_assignee_user_1` ON `assignee` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_attachment_created_date` ON `attachment` (`created_date`);
--> statement-breakpoint
CREATE INDEX `ix_attachment_owner_login_id` ON `attachment` (`owner_login_id`);
--> statement-breakpoint
CREATE INDEX `ix_attachment_container` ON `attachment` (`container_type`,`container_id`);
--> statement-breakpoint
CREATE INDEX `ix_comment_thread_pullRequest_3` ON `comment_thread` (`pull_request_id`);
--> statement-breakpoint
CREATE INDEX `ix_comment_thread_project_4` ON `comment_thread` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_commit_comment_project_5` ON `commit_comment` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_email_user_6` ON `email` (`user_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_email_email_valid` ON `email` (`email`,`valid`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_favorite_issue_user_id_issue_id_1` ON `favorite_issue` (`user_id`,`issue_id`);
--> statement-breakpoint
CREATE INDEX `ix_favorite_issue_user_1` ON `favorite_issue` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_favorite_issue_project_2` ON `favorite_issue` (`issue_id`);
--> statement-breakpoint
CREATE INDEX `ix_favorite_organization_user_1` ON `favorite_organization` (`user_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_favorite_organization_user_id_organization_id_1` ON `favorite_organization` (`user_id`,`organization_id`);
--> statement-breakpoint
CREATE INDEX `ix_favorite_organization_organization_2` ON `favorite_organization` (`organization_id`);
--> statement-breakpoint
CREATE INDEX `ix_favorite_project_project_2` ON `favorite_project` (`project_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_favorite_project_user_id_project_id_1` ON `favorite_project` (`user_id`,`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_favorite_project_user_1` ON `favorite_project` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_milestone_8` ON `issue` (`milestone_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_author_id_state` ON `issue` (`author_id`,`state`);
--> statement-breakpoint
CREATE INDEX `ix_issue_created_date` ON `issue` (`created_date`);
--> statement-breakpoint
CREATE INDEX `ix_issue_weight` ON `issue` (`weight`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_issue_1` ON `issue` (`project_id`,`number`);
--> statement-breakpoint
CREATE INDEX `ix_issue_project_7` ON `issue` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_is_draft_2` ON `issue` (`is_draft`,`author_login_id`,`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_assignee_9` ON `issue` (`assignee_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_parent_id` ON `issue` (`parent_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_is_draft_1` ON `issue` (`weight`,`is_draft`,`number`,`created_date`);
--> statement-breakpoint
CREATE INDEX `ix_issue_comment_author_id` ON `issue_comment` (`author_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_comment_issue_10` ON `issue_comment` (`issue_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_comment_parent_id` ON `issue_comment` (`parent_comment_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_comment_project_id` ON `issue_comment` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_comment_voter_user_id` ON `issue_comment_voter` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_event_issue_11` ON `issue_event` (`issue_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_label_category_12` ON `issue_label` (`category_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_label_project_13` ON `issue_label` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_label_category_project_14` ON `issue_label_category` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_sharer_user_id` ON `issue_sharer` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_sharer_issue_id` ON `issue_sharer` (`issue_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_sharer_login_id` ON `issue_sharer` (`login_id`);
--> statement-breakpoint
CREATE INDEX `ix_issue_voter_user_id` ON `issue_voter` (`user_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_label_1` ON `label` (`category`,`name`);
--> statement-breakpoint
CREATE INDEX `ix_linked_account_user_credential_1` ON `linked_account` (`user_credential_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_linked_account_provider_user_id_provider_key` ON `linked_account` (`provider_user_id`,`provider_key`);
--> statement-breakpoint
CREATE INDEX `ix_mention_resource_type` ON `mention` (`resource_type`);
--> statement-breakpoint
CREATE INDEX `ix_mention_user_15` ON `mention` (`user_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_milestone_1` ON `milestone` (`project_id`,`title`);
--> statement-breakpoint
CREATE INDEX `ix_milestone_project_16` ON `milestone` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_n4user_email` ON `n4user` (`email`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_n4user_1` ON `n4user` (`login_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_n4user_token` ON `n4user` (`token`);
--> statement-breakpoint
CREATE INDEX `ix_n4user_is_guest` ON `n4user` (`is_guest`);
--> statement-breakpoint
CREATE INDEX `ix_notification_event_created` ON `notification_event` (`created`);
--> statement-breakpoint
CREATE INDEX `ix_notification_mail_notificationEvent_17` ON `notification_mail` (`notification_event_id`);
--> statement-breakpoint
CREATE INDEX `ix_organization_user_role_20` ON `organization_user` (`role_id`);
--> statement-breakpoint
CREATE INDEX `ix_organization_user_user_18` ON `organization_user` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_organization_user_organization_19` ON `organization_user` (`organization_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_original_email_message_id` ON `original_email` (`message_id`);
--> statement-breakpoint
CREATE INDEX `ix_original_email_resource_id` ON `original_email` (`resource_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_original_email_1` ON `original_email` (`resource_type`,`resource_id`);
--> statement-breakpoint
CREATE INDEX `ix_posting_project_21` ON `posting` (`project_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_posting_1` ON `posting` (`project_id`,`number`);
--> statement-breakpoint
CREATE INDEX `ix_posting_parent_id` ON `posting` (`parent_id`);
--> statement-breakpoint
CREATE INDEX `ix_posting_comment_posting_22` ON `posting_comment` (`posting_id`);
--> statement-breakpoint
CREATE INDEX `ix_posting_comment_author_id` ON `posting_comment` (`author_id`);
--> statement-breakpoint
CREATE INDEX `ix_posting_comment_project_id` ON `posting_comment` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_posting_comment_parent_id` ON `posting_comment` (`parent_comment_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_organization_24` ON `project` (`organization_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_originalProject_23` ON `project` (`original_project_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_menu_setting_project_25` ON `project_menu_setting` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_pushed_branch_project_39` ON `project_pushed_branch` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_transfer_project_27` ON `project_transfer` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_transfer_sender_26` ON `project_transfer` (`sender_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_user_user_28` ON `project_user` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_user_role_30` ON `project_user` (`role_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_user_project_29` ON `project_user` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_visitation_recentlyVisitedProjects_32` ON `project_visitation` (`recently_visited_projects_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_project_visitation_1` ON `project_visitation` (`project_id`,`recently_visited_projects_id`);
--> statement-breakpoint
CREATE INDEX `ix_project_visitation_project_31` ON `project_visitation` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_toProject_33` ON `pull_request` (`to_project_id`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_contributor_35` ON `pull_request` (`contributor_id`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_number` ON `pull_request` (`number`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_fromProject_34` ON `pull_request` (`from_project_id`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_receiver_36` ON `pull_request` (`receiver_id`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_commit_pullRequest_37` ON `pull_request_commit` (`pull_request_id`);
--> statement-breakpoint
CREATE INDEX `ix_pull_request_event_pullRequest_38` ON `pull_request_event` (`pull_request_id`);
--> statement-breakpoint
CREATE INDEX `ix_recent_issue_user_1` ON `recent_issue` (`user_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_recent_issue_user_id_issue_id_1` ON `recent_issue` (`user_id`,`issue_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_recent_issue_user_id_posting_id_1` ON `recent_issue` (`user_id`,`posting_id`);
--> statement-breakpoint
CREATE INDEX `ix_recent_issue_issue_2` ON `recent_issue` (`user_id`,`issue_id`);
--> statement-breakpoint
CREATE INDEX `ix_recent_issue_posting_3` ON `recent_issue` (`user_id`,`posting_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_recent_project_1` ON `recent_project` (`user_id`,`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_recently_visited_projects_user_40` ON `recently_visited_projects` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_review_comment_thread_41` ON `review_comment` (`thread_id`);
--> statement-breakpoint
CREATE INDEX `ix_site_admin_admin_42` ON `site_admin` (`admin_id`);
--> statement-breakpoint
CREATE INDEX `ix_title_head_head_keyword` ON `title_head` (`head_keyword`);
--> statement-breakpoint
CREATE INDEX `ix_title_head_project_id` ON `title_head` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_unwatch_user_43` ON `unwatch` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_unwatch_resource_id_resource_type` ON `unwatch` (`resource_id`,`resource_type`);
--> statement-breakpoint
CREATE INDEX `ix_user_credential_user_id_1` ON `user_credential` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_user_project_notification_project_45` ON `user_project_notification` (`project_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_user_project_notification_1` ON `user_project_notification` (`project_id`,`user_id`,`notification_type`);
--> statement-breakpoint
CREATE INDEX `ix_user_project_notification_user_44` ON `user_project_notification` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_user_setting_user_1` ON `user_setting` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_user_verification_user_1` ON `user_verification` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_user_verification_user_2` ON `user_verification` (`login_id`,`verification_code`);
--> statement-breakpoint
CREATE INDEX `ix_watch_resource_id_resource_type` ON `watch` (`resource_id`,`resource_type`);
--> statement-breakpoint
CREATE INDEX `ix_watch_user_46` ON `watch` (`user_id`);
--> statement-breakpoint
CREATE INDEX `ix_webhook_project_47` ON `webhook` (`project_id`);
--> statement-breakpoint
CREATE INDEX `ix_webhook_webhook_type` ON `webhook` (`webhook_type`);
--> statement-breakpoint
CREATE INDEX `ix_webhook_git_push_only` ON `webhook` (`git_push`);
--> statement-breakpoint
CREATE INDEX `ix_webhook_thread_webhook_1` ON `webhook_thread` (`webhook_id`);
--> statement-breakpoint
CREATE INDEX `ix_webhook_thread_resource_2` ON `webhook_thread` (`resource_type`,`resource_id`);
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `password` text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `access_token` text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `refresh_token` text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `id_token` text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `access_token_expires_at` integer DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `refresh_token_expires_at` integer DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `scope` text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `created_at` integer DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `linked_account` ADD `updated_at` integer DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `user_credential` ADD `image` text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `user_credential` ADD `created_at` integer DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE `user_credential` ADD `updated_at` integer DEFAULT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_user_credential_email` ON `user_credential` (`email`);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_user_credential_login_id` ON `user_credential` (`login_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_organization_name" ON "organization" (lower("name"));
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_project_owner_name" ON "project" (lower("owner"), lower("name"));
--> statement-breakpoint
