-- Generated by refresh-legacy-schema-artifacts.mjs
-- Source dialect: postgres
-- Source root: drizzle/pg/migrations
CREATE TABLE "assignee" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "attachment" (
	"id" bigserial,
	"name" varchar(255) DEFAULT NULL,
	"hash" varchar(255) DEFAULT NULL,
	"container_type" varchar(20) DEFAULT NULL,
	"mime_type" varchar(255) DEFAULT NULL,
	"size" bigint DEFAULT NULL,
	"container_id" bigint NOT NULL,
	"created_date" timestamp DEFAULT NULL,
	"owner_login_id" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "comment_thread" (
	"dtype" varchar(10) NOT NULL,
	"id" bigserial,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"state" varchar(6) DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"pull_request_id" bigint DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"prev_commit_id" varchar(255) DEFAULT NULL,
	"commit_id" varchar(255) DEFAULT NULL,
	"path" varchar(255) DEFAULT NULL,
	"start_side" varchar(1) DEFAULT NULL,
	"start_line" integer DEFAULT NULL,
	"start_column" integer DEFAULT NULL,
	"end_side" varchar(1) DEFAULT NULL,
	"end_line" integer DEFAULT NULL,
	"end_column" integer DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "comment_thread_n4user" (
	"comment_thread_id" bigint NOT NULL,
	"n4user_id" bigint NOT NULL,
	PRIMARY KEY ("comment_thread_id", "n4user_id")
);
--> statement-breakpoint
CREATE TABLE "commit_comment" (
	"id" bigserial,
	"project_id" bigint DEFAULT NULL,
	"path" varchar(255) DEFAULT NULL,
	"line" integer DEFAULT NULL,
	"side" varchar(1) DEFAULT NULL,
	"contents" text DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"commit_id" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "email" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"email" varchar(255) DEFAULT NULL,
	"valid" smallint DEFAULT 0,
	"token" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "favorite_issue" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"issue_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "favorite_organization" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"organization_id" bigint DEFAULT NULL,
	"organization_name" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "favorite_project" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"owner" varchar(255) DEFAULT NULL,
	"project_name" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue" (
	"id" bigserial,
	"title" varchar(255) DEFAULT NULL,
	"body" text DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"updated_date" timestamp DEFAULT NULL,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"number" bigint DEFAULT NULL,
	"num_of_comments" integer DEFAULT NULL,
	"state" integer DEFAULT NULL,
	"due_date" timestamp DEFAULT NULL,
	"milestone_id" bigint DEFAULT NULL,
	"assignee_id" bigint DEFAULT NULL,
	"history" text DEFAULT NULL,
	"parent_id" bigint DEFAULT NULL,
	"weight" smallint DEFAULT 0,
	"updated_by_author_id" bigint DEFAULT NULL,
	"is_draft" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue_comment" (
	"id" bigserial,
	"contents" text DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"issue_id" bigint DEFAULT NULL,
	"project_id" bigint NOT NULL,
	"parent_comment_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue_comment_voter" (
	"issue_comment_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	PRIMARY KEY ("issue_comment_id", "user_id")
);
--> statement-breakpoint
CREATE TABLE "issue_event" (
	"id" bigserial,
	"created" timestamp DEFAULT NULL,
	"sender_login_id" varchar(255) DEFAULT NULL,
	"sender_email" varchar(255) DEFAULT NULL,
	"issue_id" bigint DEFAULT NULL,
	"event_type" varchar(34) DEFAULT NULL,
	"old_value" text DEFAULT NULL,
	"new_value" text DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue_issue_label" (
	"issue_id" bigint NOT NULL,
	"issue_label_id" bigint NOT NULL,
	PRIMARY KEY ("issue_id", "issue_label_id")
);
--> statement-breakpoint
CREATE TABLE "issue_label" (
	"id" bigserial,
	"category_id" bigint DEFAULT NULL,
	"color" varchar(255) DEFAULT NULL,
	"name" varchar(255) DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue_label_category" (
	"id" bigserial,
	"project_id" bigint DEFAULT NULL,
	"name" varchar(255) DEFAULT NULL,
	"is_exclusive" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue_sharer" (
	"id" bigserial,
	"created" date DEFAULT NULL,
	"login_id" varchar(255) DEFAULT NULL,
	"user_id" bigint DEFAULT NULL,
	"issue_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "issue_voter" (
	"issue_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	PRIMARY KEY ("issue_id", "user_id")
);
--> statement-breakpoint
CREATE TABLE "label" (
	"id" bigserial,
	"category" varchar(255) DEFAULT NULL,
	"name" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "linked_account" (
	"id" bigserial,
	"user_credential_id" bigint DEFAULT NULL,
	"provider_user_id" varchar(255) DEFAULT NULL,
	"provider_key" varchar(255) DEFAULT NULL,
	"provider_display_name" varchar(255) DEFAULT NULL,
	"avatar_url" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "mention" (
	"id" bigserial,
	"resource_type" varchar(20) DEFAULT NULL,
	"resource_id" varchar(255) DEFAULT NULL,
	"user_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "milestone" (
	"id" bigserial,
	"title" varchar(255) DEFAULT NULL,
	"due_date" timestamp DEFAULT NULL,
	"contents" text DEFAULT NULL,
	"state" integer DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "n4user" (
	"id" bigserial,
	"name" varchar(255) DEFAULT NULL,
	"login_id" varchar(255) DEFAULT NULL,
	"password" varchar(255) DEFAULT NULL,
	"password_salt" varchar(255) DEFAULT NULL,
	"email" varchar(255) DEFAULT NULL,
	"remember_me" smallint DEFAULT 0,
	"state" varchar(7) DEFAULT NULL,
	"last_state_modified_date" timestamp DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"lang" varchar(255) DEFAULT NULL,
	"token" varchar(255) DEFAULT NULL,
	"is_guest" smallint DEFAULT 0,
	"english_name" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "notification_event" (
	"id" bigserial,
	"title" varchar(255) DEFAULT NULL,
	"sender_id" bigint DEFAULT NULL,
	"created" timestamp DEFAULT NULL,
	"resource_type" varchar(20) DEFAULT NULL,
	"resource_id" varchar(255) DEFAULT NULL,
	"event_type" varchar(34) DEFAULT NULL,
	"old_value" text DEFAULT NULL,
	"new_value" text DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "notification_event_n4user" (
	"notification_event_id" bigint NOT NULL,
	"n4user_id" bigint NOT NULL,
	PRIMARY KEY ("notification_event_id", "n4user_id")
);
--> statement-breakpoint
CREATE TABLE "notification_mail" (
	"id" bigserial,
	"notification_event_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" bigserial,
	"name" varchar(255) DEFAULT NULL,
	"created" timestamp DEFAULT NULL,
	"descr" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "organization_user" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"organization_id" bigint DEFAULT NULL,
	"role_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "original_email" (
	"id" bigserial,
	"message_id" varchar(255) DEFAULT NULL,
	"resource_type" varchar(20) DEFAULT NULL,
	"resource_id" varchar(255) DEFAULT NULL,
	"handled_date" timestamp DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "play_evolutions" (
	"id" integer NOT NULL,
	"hash" varchar(255) NOT NULL,
	"applied_at" timestamp DEFAULT current_timestamp() NOT NULL,
	"apply_script" text DEFAULT NULL,
	"revert_script" text DEFAULT NULL,
	"state" varchar(255) DEFAULT NULL,
	"last_problem" text DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "posting" (
	"id" bigserial,
	"title" varchar(255) DEFAULT NULL,
	"body" text DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"updated_date" timestamp DEFAULT NULL,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"number" bigint DEFAULT NULL,
	"num_of_comments" integer DEFAULT NULL,
	"notice" smallint DEFAULT 0,
	"readme" smallint DEFAULT 0,
	"history" text DEFAULT NULL,
	"parent_id" bigint DEFAULT NULL,
	"updated_by_author_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "posting_comment" (
	"id" bigserial,
	"contents" text DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"posting_id" bigint DEFAULT NULL,
	"project_id" bigint NOT NULL,
	"parent_comment_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "posting_issue_label" (
	"posting_id" bigint NOT NULL,
	"issue_label_id" bigint NOT NULL,
	PRIMARY KEY ("posting_id", "issue_label_id")
);
--> statement-breakpoint
CREATE TABLE "project" (
	"id" bigserial,
	"name" varchar(255) DEFAULT NULL,
	"overview" varchar(255) DEFAULT NULL,
	"vcs" varchar(255) DEFAULT NULL,
	"siteurl" varchar(255) DEFAULT NULL,
	"owner" varchar(255) DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"last_issue_number" bigint DEFAULT NULL,
	"last_posting_number" bigint DEFAULT NULL,
	"original_project_id" bigint DEFAULT NULL,
	"last_pushed_date" timestamp DEFAULT NULL,
	"default_reviewer_count" integer DEFAULT NULL,
	"is_using_reviewer_count" smallint DEFAULT 0,
	"organization_id" bigint DEFAULT NULL,
	"project_scope" varchar(9) DEFAULT NULL,
	"previous_owner_login_id" varchar(255) DEFAULT NULL,
	"previous_name" varchar(255) DEFAULT NULL,
	"previous_name_changed_time" bigint DEFAULT NULL,
	"is_code_accessible_member_only" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "project_label" (
	"project_id" bigint NOT NULL,
	"label_id" bigint NOT NULL,
	PRIMARY KEY ("project_id", "label_id")
);
--> statement-breakpoint
CREATE TABLE "project_menu_setting" (
	"id" bigserial,
	"project_id" bigint DEFAULT NULL,
	"code" smallint DEFAULT 0,
	"issue" smallint DEFAULT 0,
	"pull_request" smallint DEFAULT 0,
	"review" smallint DEFAULT 0,
	"milestone" smallint DEFAULT 0,
	"board" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "project_pushed_branch" (
	"id" bigserial,
	"pushed_date" timestamp DEFAULT NULL,
	"name" varchar(255) DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "project_transfer" (
	"id" bigserial,
	"sender_id" bigint DEFAULT NULL,
	"destination" varchar(255) DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"requested" timestamp DEFAULT NULL,
	"confirm_key" varchar(255) DEFAULT NULL,
	"accepted" smallint DEFAULT 0,
	"new_project_name" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "project_user" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"role_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "project_visitation" (
	"id" bigserial,
	"project_id" bigint DEFAULT NULL,
	"recently_visited_projects_id" bigint DEFAULT NULL,
	"visited" timestamp DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "property" (
	"id" bigserial,
	"name" varchar(25) DEFAULT NULL,
	"value" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "pull_request" (
	"id" bigserial,
	"title" varchar(255) DEFAULT NULL,
	"body" text DEFAULT NULL,
	"to_project_id" bigint DEFAULT NULL,
	"from_project_id" bigint DEFAULT NULL,
	"to_branch" varchar(255) DEFAULT NULL,
	"from_branch" varchar(255) DEFAULT NULL,
	"contributor_id" bigint DEFAULT NULL,
	"receiver_id" bigint DEFAULT NULL,
	"created" timestamp DEFAULT NULL,
	"updated" timestamp DEFAULT NULL,
	"received" timestamp DEFAULT NULL,
	"state" integer DEFAULT NULL,
	"is_conflict" smallint DEFAULT 0,
	"is_merging" smallint DEFAULT 0,
	"last_commit_id" varchar(255) DEFAULT NULL,
	"merged_commit_id_from" varchar(255) DEFAULT NULL,
	"merged_commit_id_to" varchar(255) DEFAULT NULL,
	"number" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "pull_request_commit" (
	"id" bigserial,
	"pull_request_id" bigint DEFAULT NULL,
	"commit_id" varchar(255) DEFAULT NULL,
	"author_date" timestamp DEFAULT NULL,
	"created" timestamp DEFAULT NULL,
	"commit_message" text DEFAULT NULL,
	"commit_short_id" varchar(255) DEFAULT NULL,
	"author_email" varchar(255) DEFAULT NULL,
	"state" varchar(7) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "pull_request_event" (
	"id" bigserial,
	"sender_login_id" varchar(255) DEFAULT NULL,
	"pull_request_id" bigint DEFAULT NULL,
	"event_type" varchar(34) DEFAULT NULL,
	"created" timestamp DEFAULT NULL,
	"old_value" text DEFAULT NULL,
	"new_value" text DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "pull_request_reviewers" (
	"pull_request_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	PRIMARY KEY ("pull_request_id", "user_id")
);
--> statement-breakpoint
CREATE TABLE "recent_issue" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"issue_id" bigint DEFAULT NULL,
	"posting_id" bigint DEFAULT NULL,
	"title" varchar(255) DEFAULT NULL,
	"url" varchar(255) DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "recent_project" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"owner" varchar(255) DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"project_name" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "recently_visited_projects" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "review_comment" (
	"id" bigserial,
	"contents" text DEFAULT NULL,
	"created_date" timestamp DEFAULT NULL,
	"author_id" bigint DEFAULT NULL,
	"author_login_id" varchar(255) DEFAULT NULL,
	"author_name" varchar(255) DEFAULT NULL,
	"thread_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "role" (
	"id" bigserial,
	"name" varchar(255) DEFAULT NULL,
	"active" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "site_admin" (
	"id" bigserial,
	"admin_id" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "title_head" (
	"id" bigserial,
	"project_id" bigint DEFAULT NULL,
	"head_keyword" varchar(255) DEFAULT NULL,
	"frequency" integer DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "unwatch" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"resource_type" varchar(20) DEFAULT NULL,
	"resource_id" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "user_credential" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"login_id" varchar(255) DEFAULT NULL,
	"email" varchar(255) DEFAULT NULL,
	"name" varchar(255) DEFAULT NULL,
	"active" smallint DEFAULT 0,
	"email_validated" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "user_enrolled_organization" (
	"user_id" bigint NOT NULL,
	"organization_id" bigint NOT NULL,
	PRIMARY KEY ("user_id", "organization_id")
);
--> statement-breakpoint
CREATE TABLE "user_enrolled_project" (
	"user_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	PRIMARY KEY ("user_id", "project_id")
);
--> statement-breakpoint
CREATE TABLE "user_project_notification" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"project_id" bigint DEFAULT NULL,
	"notification_type" varchar(34) DEFAULT NULL,
	"allowed" smallint DEFAULT 0,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "user_setting" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"login_default_page" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "user_verification" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"login_id" varchar(255) DEFAULT NULL,
	"verification_code" varchar(255) DEFAULT NULL,
	"timestamp" bigint DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "watch" (
	"id" bigserial,
	"user_id" bigint DEFAULT NULL,
	"resource_type" varchar(20) DEFAULT NULL,
	"resource_id" varchar(255) DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "webhook" (
	"id" bigserial,
	"project_id" bigint DEFAULT NULL,
	"payload_url" varchar(2000) DEFAULT NULL,
	"secret" varchar(250) DEFAULT NULL,
	"created_at" timestamp DEFAULT NULL,
	"git_push" smallint DEFAULT 0,
	"webhook_type" smallint DEFAULT 1,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE TABLE "webhook_thread" (
	"id" bigserial,
	"webhook_id" bigint DEFAULT NULL,
	"resource_type" varchar(20) DEFAULT NULL,
	"resource_id" varchar(255) DEFAULT NULL,
	"thread_id" varchar(2000) DEFAULT NULL,
	"created_at" timestamp DEFAULT NULL,
	PRIMARY KEY ("id")
);
--> statement-breakpoint
CREATE INDEX "ix_assignee_project_2" ON "assignee" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_assignee_user_1" ON "assignee" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_attachment_created_date" ON "attachment" ("created_date");
--> statement-breakpoint
CREATE INDEX "ix_attachment_owner_login_id" ON "attachment" ("owner_login_id");
--> statement-breakpoint
CREATE INDEX "ix_attachment_container" ON "attachment" ("container_type","container_id");
--> statement-breakpoint
CREATE INDEX "ix_comment_thread_pullRequest_3" ON "comment_thread" ("pull_request_id");
--> statement-breakpoint
CREATE INDEX "ix_comment_thread_project_4" ON "comment_thread" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_commit_comment_project_5" ON "commit_comment" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_email_user_6" ON "email" ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_email_email_valid" ON "email" ("email","valid");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_favorite_issue_user_id_issue_id_1" ON "favorite_issue" ("user_id","issue_id");
--> statement-breakpoint
CREATE INDEX "ix_favorite_issue_user_1" ON "favorite_issue" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_favorite_issue_project_2" ON "favorite_issue" ("issue_id");
--> statement-breakpoint
CREATE INDEX "ix_favorite_organization_user_1" ON "favorite_organization" ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_favorite_organization_user_id_organization_id_1" ON "favorite_organization" ("user_id","organization_id");
--> statement-breakpoint
CREATE INDEX "ix_favorite_organization_organization_2" ON "favorite_organization" ("organization_id");
--> statement-breakpoint
CREATE INDEX "ix_favorite_project_project_2" ON "favorite_project" ("project_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_favorite_project_user_id_project_id_1" ON "favorite_project" ("user_id","project_id");
--> statement-breakpoint
CREATE INDEX "ix_favorite_project_user_1" ON "favorite_project" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_milestone_8" ON "issue" ("milestone_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_author_id_state" ON "issue" ("author_id","state");
--> statement-breakpoint
CREATE INDEX "ix_issue_created_date" ON "issue" ("created_date");
--> statement-breakpoint
CREATE INDEX "ix_issue_weight" ON "issue" ("weight");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_issue_1" ON "issue" ("project_id","number");
--> statement-breakpoint
CREATE INDEX "ix_issue_project_7" ON "issue" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_is_draft_2" ON "issue" ("is_draft","author_login_id","project_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_assignee_9" ON "issue" ("assignee_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_parent_id" ON "issue" ("parent_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_is_draft_1" ON "issue" ("weight","is_draft","number","created_date");
--> statement-breakpoint
CREATE INDEX "ix_issue_comment_author_id" ON "issue_comment" ("author_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_comment_issue_10" ON "issue_comment" ("issue_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_parent_id_issue_comment" ON "issue_comment" ("parent_comment_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_comment_project_id" ON "issue_comment" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_comment_voter_user_id" ON "issue_comment_voter" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_event_issue_11" ON "issue_event" ("issue_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_label_category_12" ON "issue_label" ("category_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_label_project_13" ON "issue_label" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_label_category_project_14" ON "issue_label_category" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_sharer_user_id" ON "issue_sharer" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_sharer_issue_id" ON "issue_sharer" ("issue_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_sharer_login_id" ON "issue_sharer" ("login_id");
--> statement-breakpoint
CREATE INDEX "ix_issue_voter_user_id" ON "issue_voter" ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_label_1" ON "label" ("category","name");
--> statement-breakpoint
CREATE INDEX "ix_linked_account_user_credential_1" ON "linked_account" ("user_credential_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_linked_account_provider_user_id_provider_key" ON "linked_account" ("provider_user_id","provider_key");
--> statement-breakpoint
CREATE INDEX "ix_mention_resource_type" ON "mention" ("resource_type");
--> statement-breakpoint
CREATE INDEX "ix_mention_user_15" ON "mention" ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_milestone_1" ON "milestone" ("project_id","title");
--> statement-breakpoint
CREATE INDEX "ix_milestone_project_16" ON "milestone" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_n4user_email" ON "n4user" ("email");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_n4user_1" ON "n4user" ("login_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_n4user_token" ON "n4user" ("token");
--> statement-breakpoint
CREATE INDEX "ix_n4user_is_guest" ON "n4user" ("is_guest");
--> statement-breakpoint
CREATE INDEX "ix_notification_event_created" ON "notification_event" ("created");
--> statement-breakpoint
CREATE INDEX "ix_notification_mail_notificationEvent_17" ON "notification_mail" ("notification_event_id");
--> statement-breakpoint
CREATE INDEX "ix_organization_user_role_20" ON "organization_user" ("role_id");
--> statement-breakpoint
CREATE INDEX "ix_organization_user_user_18" ON "organization_user" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_organization_user_organization_19" ON "organization_user" ("organization_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_original_email_message_id" ON "original_email" ("message_id");
--> statement-breakpoint
CREATE INDEX "ix_original_email_resource_id" ON "original_email" ("resource_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_original_email_1" ON "original_email" ("resource_type","resource_id");
--> statement-breakpoint
CREATE INDEX "ix_posting_project_21" ON "posting" ("project_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_posting_1" ON "posting" ("project_id","number");
--> statement-breakpoint
CREATE INDEX "ix_posting_parent_id" ON "posting" ("parent_id");
--> statement-breakpoint
CREATE INDEX "ix_posting_comment_posting_22" ON "posting_comment" ("posting_id");
--> statement-breakpoint
CREATE INDEX "ix_posting_comment_author_id" ON "posting_comment" ("author_id");
--> statement-breakpoint
CREATE INDEX "ix_posting_comment_project_id" ON "posting_comment" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_posting_parent_id_posting_comment" ON "posting_comment" ("parent_comment_id");
--> statement-breakpoint
CREATE INDEX "ix_project_organization_24" ON "project" ("organization_id");
--> statement-breakpoint
CREATE INDEX "ix_project_originalProject_23" ON "project" ("original_project_id");
--> statement-breakpoint
CREATE INDEX "ix_project_menu_setting_project_25" ON "project_menu_setting" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_project_pushed_branch_project_39" ON "project_pushed_branch" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_project_transfer_project_27" ON "project_transfer" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_project_transfer_sender_26" ON "project_transfer" ("sender_id");
--> statement-breakpoint
CREATE INDEX "ix_project_user_user_28" ON "project_user" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_project_user_role_30" ON "project_user" ("role_id");
--> statement-breakpoint
CREATE INDEX "ix_project_user_project_29" ON "project_user" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_project_visitation_recentlyVisitedProjects_32" ON "project_visitation" ("recently_visited_projects_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_project_visitation_1" ON "project_visitation" ("project_id","recently_visited_projects_id");
--> statement-breakpoint
CREATE INDEX "ix_project_visitation_project_31" ON "project_visitation" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_toProject_33" ON "pull_request" ("to_project_id");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_contributor_35" ON "pull_request" ("contributor_id");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_number" ON "pull_request" ("number");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_fromProject_34" ON "pull_request" ("from_project_id");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_receiver_36" ON "pull_request" ("receiver_id");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_commit_pullRequest_37" ON "pull_request_commit" ("pull_request_id");
--> statement-breakpoint
CREATE INDEX "ix_pull_request_event_pullRequest_38" ON "pull_request_event" ("pull_request_id");
--> statement-breakpoint
CREATE INDEX "ix_recent_issue_user_1" ON "recent_issue" ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recent_issue_user_id_issue_id_1" ON "recent_issue" ("user_id","issue_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recent_issue_user_id_posting_id_1" ON "recent_issue" ("user_id","posting_id");
--> statement-breakpoint
CREATE INDEX "ix_recent_issue_issue_2" ON "recent_issue" ("user_id","issue_id");
--> statement-breakpoint
CREATE INDEX "ix_recent_issue_posting_3" ON "recent_issue" ("user_id","posting_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recent_project_1" ON "recent_project" ("user_id","project_id");
--> statement-breakpoint
CREATE INDEX "ix_recently_visited_projects_user_40" ON "recently_visited_projects" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_review_comment_thread_41" ON "review_comment" ("thread_id");
--> statement-breakpoint
CREATE INDEX "ix_site_admin_admin_42" ON "site_admin" ("admin_id");
--> statement-breakpoint
CREATE INDEX "ix_title_head_head_keyword" ON "title_head" ("head_keyword");
--> statement-breakpoint
CREATE INDEX "ix_title_head_project_id" ON "title_head" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_unwatch_user_43" ON "unwatch" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_unwatch_resource_id_resource_type" ON "unwatch" ("resource_id","resource_type");
--> statement-breakpoint
CREATE INDEX "ix_user_credential_user_id_1" ON "user_credential" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_user_project_notification_project_45" ON "user_project_notification" ("project_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_project_notification_1" ON "user_project_notification" ("project_id","user_id","notification_type");
--> statement-breakpoint
CREATE INDEX "ix_user_project_notification_user_44" ON "user_project_notification" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_user_setting_user_1" ON "user_setting" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_user_verification_user_1" ON "user_verification" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_user_verification_user_2" ON "user_verification" ("login_id","verification_code");
--> statement-breakpoint
CREATE INDEX "ix_watch_resource_id_resource_type" ON "watch" ("resource_id","resource_type");
--> statement-breakpoint
CREATE INDEX "ix_watch_user_46" ON "watch" ("user_id");
--> statement-breakpoint
CREATE INDEX "ix_webhook_project_47" ON "webhook" ("project_id");
--> statement-breakpoint
CREATE INDEX "ix_webhook_webhook_type" ON "webhook" ("webhook_type");
--> statement-breakpoint
CREATE INDEX "ix_webhook_git_push_only" ON "webhook" ("git_push");
--> statement-breakpoint
CREATE INDEX "ix_webhook_thread_webhook_1" ON "webhook_thread" ("webhook_id");
--> statement-breakpoint
CREATE INDEX "ix_webhook_thread_resource_2" ON "webhook_thread" ("resource_type","resource_id");
--> statement-breakpoint
ALTER TABLE "assignee" ADD CONSTRAINT "assignee_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "assignee" ADD CONSTRAINT "assignee_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "comment_thread" ADD CONSTRAINT "comment_thread_pull_request_id_pull_request_id_fkey" FOREIGN KEY ("pull_request_id") REFERENCES "pull_request"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "comment_thread" ADD CONSTRAINT "comment_thread_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "comment_thread_n4user" ADD CONSTRAINT "comment_thread_n4user_comment_thread_id_comment_thread_id_fkey" FOREIGN KEY ("comment_thread_id") REFERENCES "comment_thread"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "comment_thread_n4user" ADD CONSTRAINT "comment_thread_n4user_n4user_id_n4user_id_fkey" FOREIGN KEY ("n4user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "commit_comment" ADD CONSTRAINT "commit_comment_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "email" ADD CONSTRAINT "email_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "favorite_issue" ADD CONSTRAINT "favorite_issue_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "favorite_issue" ADD CONSTRAINT "favorite_issue_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "favorite_organization" ADD CONSTRAINT "favorite_organization_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "favorite_organization" ADD CONSTRAINT "favorite_organization_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "favorite_project" ADD CONSTRAINT "favorite_project_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "favorite_project" ADD CONSTRAINT "favorite_project_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "issue_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "issue_milestone_id_milestone_id_fkey" FOREIGN KEY ("milestone_id") REFERENCES "milestone"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "issue_assignee_id_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "assignee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "fk_issue_parent_id_01" FOREIGN KEY ("parent_id") REFERENCES "issue"("id") ON DELETE SET NULL ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_comment" ADD CONSTRAINT "issue_comment_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_comment" ADD CONSTRAINT "fk_issue_comment_parent_id_01" FOREIGN KEY ("parent_comment_id") REFERENCES "issue_comment"("id") ON DELETE SET NULL ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_comment_voter" ADD CONSTRAINT "issue_comment_voter_issue_comment_id_issue_comment_id_fkey" FOREIGN KEY ("issue_comment_id") REFERENCES "issue_comment"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_comment_voter" ADD CONSTRAINT "issue_comment_voter_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_event" ADD CONSTRAINT "issue_event_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_issue_label" ADD CONSTRAINT "issue_issue_label_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_issue_label" ADD CONSTRAINT "issue_issue_label_issue_label_id_issue_label_id_fkey" FOREIGN KEY ("issue_label_id") REFERENCES "issue_label"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_label" ADD CONSTRAINT "issue_label_category_id_issue_label_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "issue_label_category"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_label" ADD CONSTRAINT "issue_label_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_label_category" ADD CONSTRAINT "issue_label_category_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_sharer" ADD CONSTRAINT "issue_sharer_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_sharer" ADD CONSTRAINT "issue_sharer_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_voter" ADD CONSTRAINT "issue_voter_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "issue_voter" ADD CONSTRAINT "issue_voter_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD CONSTRAINT "linked_account_user_credential_id_user_credential_id_fkey" FOREIGN KEY ("user_credential_id") REFERENCES "user_credential"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "mention" ADD CONSTRAINT "mention_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "milestone_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "notification_event_n4user" ADD CONSTRAINT "notification_event_n4user_1KbPF6Zt9NUw_fkey" FOREIGN KEY ("notification_event_id") REFERENCES "notification_event"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "notification_event_n4user" ADD CONSTRAINT "notification_event_n4user_n4user_id_n4user_id_fkey" FOREIGN KEY ("n4user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "notification_mail" ADD CONSTRAINT "notification_mail_oTLEeQwfU5jf_fkey" FOREIGN KEY ("notification_event_id") REFERENCES "notification_event"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "organization_user" ADD CONSTRAINT "organization_user_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "organization_user" ADD CONSTRAINT "organization_user_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "organization_user" ADD CONSTRAINT "organization_user_role_id_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "posting" ADD CONSTRAINT "posting_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "posting" ADD CONSTRAINT "fk_posting_parent_id_01" FOREIGN KEY ("parent_id") REFERENCES "posting"("id") ON DELETE SET NULL ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "posting_comment" ADD CONSTRAINT "posting_comment_posting_id_posting_id_fkey" FOREIGN KEY ("posting_id") REFERENCES "posting"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "posting_comment" ADD CONSTRAINT "fk_posting_comment_parent_id_01" FOREIGN KEY ("parent_comment_id") REFERENCES "posting_comment"("id") ON DELETE SET NULL ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "posting_issue_label" ADD CONSTRAINT "posting_issue_label_posting_id_posting_id_fkey" FOREIGN KEY ("posting_id") REFERENCES "posting"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "posting_issue_label" ADD CONSTRAINT "posting_issue_label_issue_label_id_issue_label_id_fkey" FOREIGN KEY ("issue_label_id") REFERENCES "issue_label"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "fk_project_originalProject_23" FOREIGN KEY ("original_project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_label" ADD CONSTRAINT "project_label_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_label" ADD CONSTRAINT "project_label_label_id_label_id_fkey" FOREIGN KEY ("label_id") REFERENCES "label"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_menu_setting" ADD CONSTRAINT "project_menu_setting_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_pushed_branch" ADD CONSTRAINT "project_pushed_branch_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_transfer" ADD CONSTRAINT "project_transfer_sender_id_n4user_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_transfer" ADD CONSTRAINT "project_transfer_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_user" ADD CONSTRAINT "project_user_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_user" ADD CONSTRAINT "project_user_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_user" ADD CONSTRAINT "project_user_role_id_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "project_visitation" ADD CONSTRAINT "project_visitation_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
--> statement-breakpoint
ALTER TABLE "project_visitation" ADD CONSTRAINT "project_visitation_Y6HdABJHvXOw_fkey" FOREIGN KEY ("recently_visited_projects_id") REFERENCES "recently_visited_projects"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request" ADD CONSTRAINT "pull_request_to_project_id_project_id_fkey" FOREIGN KEY ("to_project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request" ADD CONSTRAINT "pull_request_from_project_id_project_id_fkey" FOREIGN KEY ("from_project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request" ADD CONSTRAINT "pull_request_contributor_id_n4user_id_fkey" FOREIGN KEY ("contributor_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request" ADD CONSTRAINT "pull_request_receiver_id_n4user_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request_commit" ADD CONSTRAINT "pull_request_commit_pull_request_id_pull_request_id_fkey" FOREIGN KEY ("pull_request_id") REFERENCES "pull_request"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request_event" ADD CONSTRAINT "pull_request_event_pull_request_id_pull_request_id_fkey" FOREIGN KEY ("pull_request_id") REFERENCES "pull_request"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request_reviewers" ADD CONSTRAINT "pull_request_reviewers_pull_request_id_pull_request_id_fkey" FOREIGN KEY ("pull_request_id") REFERENCES "pull_request"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "pull_request_reviewers" ADD CONSTRAINT "pull_request_reviewers_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "recent_issue" ADD CONSTRAINT "recent_issue_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "recent_issue" ADD CONSTRAINT "recent_issue_issue_id_issue_id_fkey" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "recent_project" ADD CONSTRAINT "recent_project_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
--> statement-breakpoint
ALTER TABLE "recently_visited_projects" ADD CONSTRAINT "recently_visited_projects_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "review_comment" ADD CONSTRAINT "review_comment_thread_id_comment_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "comment_thread"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "site_admin" ADD CONSTRAINT "site_admin_admin_id_n4user_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "title_head" ADD CONSTRAINT "title_head_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "unwatch" ADD CONSTRAINT "unwatch_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_credential" ADD CONSTRAINT "user_credential_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_enrolled_organization" ADD CONSTRAINT "user_enrolled_organization_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_enrolled_organization" ADD CONSTRAINT "user_enrolled_organization_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_enrolled_project" ADD CONSTRAINT "user_enrolled_project_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_enrolled_project" ADD CONSTRAINT "user_enrolled_project_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_project_notification" ADD CONSTRAINT "user_project_notification_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_project_notification" ADD CONSTRAINT "user_project_notification_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_setting" ADD CONSTRAINT "user_setting_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "user_verification" ADD CONSTRAINT "user_verification_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "watch" ADD CONSTRAINT "watch_user_id_n4user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "n4user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "webhook" ADD CONSTRAINT "webhook_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "webhook_thread" ADD CONSTRAINT "webhook_thread_webhook_id_webhook_id_fkey" FOREIGN KEY ("webhook_id") REFERENCES "webhook"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "password" varchar(255) DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "access_token" text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "refresh_token" text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "id_token" text DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "access_token_expires_at" timestamp DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "refresh_token_expires_at" timestamp DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "scope" varchar(255) DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "created_at" timestamp DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "linked_account" ADD COLUMN "updated_at" timestamp DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "user_credential" ADD COLUMN "image" varchar(255) DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "user_credential" ADD COLUMN "created_at" timestamp DEFAULT NULL;
--> statement-breakpoint
ALTER TABLE "user_credential" ADD COLUMN "updated_at" timestamp DEFAULT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_credential_email" ON "user_credential" ("email");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_credential_login_id" ON "user_credential" ("login_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_organization_name" ON "organization" (lower("name"));
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_project_owner_name" ON "project" (lower("owner"),lower("name"));
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_organization_name_organization" ON "organization" ("name");
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_project_owner_name_project" ON "project" ("owner", "name");
--> statement-breakpoint
