import * as stylex from "@stylexjs/stylex";

// Frozen paint evidence: yobi/_page.less, yobi/_yobiUI.less, and Bootstrap modal/button rules.
// This route-local theme contains only dark-mode override candidates.
export const siteProjectListTheme = stylex.defineVars({
  titleBorder: "#dddddd",
  titleText: "#4c4c4c",
  searchSurface: "#ffffff",
  searchBorder: "#cccccc",
  searchButtonSurface: "transparent",
  sidebarBorder: "#eeeeee",
  sidebarActiveBorder: "#f36c22",
  sidebarLinkText: "#333333",
  sidebarHoverSurface: "#eeeeee",
  badgeSurface: "#ff7332",
  badgeText: "#ecf0f1",
  badgeBorder: "#ffffff",
  badgeShadow: "0 1px 1px rgba(0, 0, 0, 0.2), inset 0 1px 1px rgba(0, 0, 0, 0.1)",
  listHeadSurface: "#f7f7f7",
  listBorder: "#efefef",
  rowEvenSurface: "#f9f9f9",
  avatarSurface: "#dddddd",
  deleteText: "#ffffff",
  deleteSurface: "#c93426",
  deleteInteractiveSurface: "#b13427",
  deleteBorder: "#b13427",
  deleteShadow: "0px 1px 0px rgba(0, 0, 0, 0.05)",
  paginationText: "#8e9094",
  paginationDelimiter: "#dddddd",
  paginationInputBorder: "#eeeeee",
  paginationAccent: "#f36c22",
  paginationInputInteractiveShadow: "inset -1px -1px 2px rgba(0, 0, 0, 0.1)",
  modalSurface: "#ffffff",
  modalBorder: "rgba(0, 0, 0, 0.3)",
  modalShadow: "0 3px 7px rgba(0, 0, 0, 0.3)",
  modalHeaderBorder: "#eeeeee",
  modalCloseText: "#000000",
  modalCloseTextShadow: "0 1px 0 #ffffff",
  modalCloseSurface: "transparent",
  modalFooterSurface: "#f5f5f5",
  modalFooterBorder: "#dddddd",
  modalFooterShadow: "inset 0 1px 0 #ffffff",
  modalBackdropSurface: "#000000",
  modalActionText: "#333333",
  modalActionSurface: "#ffffff",
  modalActionBorder: "rgba(0, 0, 0, 0.15)",
  modalActionInteractiveBorder: "rgba(0, 0, 0, 0.25)",
  modalActionShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
  modalActionInteractiveSurface: "#f1f1f1",
  modalActionInteractiveText: "#292929",
  modalConfirmText: "#ffffff",
  modalConfirmSurface: "#c93426",
  modalConfirmBorder: "#b13427",
  modalConfirmInteractiveSurface: "#b13427",
});
