import * as stylex from "@stylexjs/stylex";

export const siteUserListColors = stylex.defineVars({
  identityId: "#999999",
  identityName: "#0088cc",
  paginationAccent: "#f36c22",
  paginationDelimiter: "#dddddd",
  paginationFocusShadow: "inset -1px -1px 2px rgba(0, 0, 0, 0.1)",
  paginationInputBorder: "#eeeeee",
  paginationText: "#8e9094",
  listheadBorder: "#efefef",
  listheadSurface: "#f7f7f7",
  rowAlternateSurface: "#f9f9f9",
  rowBorder: "#efefef",
  searchBorder: "#cccccc",
  searchFocusBorder: "#f36c22",
  searchSurface: "#ffffff",
  searchText: "#555555",
  sidebarAccent: "#f36c22",
  sidebarBorder: "#eeeeee",
  sidebarHoverSurface: "#eeeeee",
  actionBorder: "rgba(0, 0, 0, 0.15)",
  actionBorderInteractive: "rgba(0, 0, 0, 0.25)",
  actionDanger: "#c93426",
  actionDangerBorder: "#b13427",
  actionDefaultSurface: "#ffffff",
  actionDefaultSurfaceInteractive: "#f1f1f1",
  actionInfo: "#3a7ee5",
  actionInfoBorder: "#206ee5",
  actionLabelInfo: "#3a87ad",
  actionPrimary: "#ff7332",
  actionPrimaryBorder: "#e95e01",
  actionShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
  actionText: "#333333",
  actionTextInteractive: "#292929",
  actionTextInverse: "#ffffff",
  stateTabActiveBackground: "#ffffff",
  stateTabActiveText: "#555555",
  stateTabBorder: "#dddddd",
  stateTabHoverBackground: "#f2f2f2",
  stateTabHoverBorder: "#eeeeee",
  stateTabText: "#3592b5",
  titleBorder: "#dddddd",
  titleText: "#4c4c4c",
});
