//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "commit_comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub project_id: Option<i64>,
    pub path: Option<String>,
    pub line: Option<i32>,
    pub side: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub contents: Option<String>,
    pub created_date: Option<DateTime>,
    pub author_id: Option<i64>,
    pub author_login_id: Option<String>,
    pub author_name: Option<String>,
    pub commit_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project,
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
