//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "issue_comment_voter")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub issue_comment_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::issue_comment::Entity",
        from = "Column::IssueCommentId",
        to = "super::issue_comment::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    IssueComment,
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::UserId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    N4user,
}

impl Related<super::issue_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComment.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::N4user.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
