//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "issue_label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub category_id: Option<i64>,
    pub color: Option<String>,
    pub name: Option<String>,
    pub project_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::issue_issue_label::Entity")]
    IssueIssueLabel,
    #[sea_orm(
        belongs_to = "super::issue_label_category::Entity",
        from = "Column::CategoryId",
        to = "super::issue_label_category::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    IssueLabelCategory,
    #[sea_orm(has_many = "super::posting_issue_label::Entity")]
    PostingIssueLabel,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project,
}

impl Related<super::issue_issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueIssueLabel.def()
    }
}

impl Related<super::issue_label_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabelCategory.def()
    }
}

impl Related<super::posting_issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostingIssueLabel.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        super::issue_issue_label::Relation::Issue.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::issue_issue_label::Relation::IssueLabel.def().rev())
    }
}

impl Related<super::posting::Entity> for Entity {
    fn to() -> RelationDef {
        super::posting_issue_label::Relation::Posting.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::posting_issue_label::Relation::IssueLabel.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
