//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notification_mail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub notification_event_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notification_event::Entity",
        from = "Column::NotificationEventId",
        to = "super::notification_event::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    NotificationEvent,
}

impl Related<super::notification_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
