//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "original_email")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub message_id: Option<String>,
    #[sea_orm(unique_key = "uq_original_email_1")]
    pub resource_type: Option<String>,
    #[sea_orm(unique_key = "uq_original_email_1")]
    pub resource_id: Option<String>,
    pub handled_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
