//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_credential")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: Option<i64>,
    pub login_id: Option<String>,
    pub email: Option<String>,
    pub name: Option<String>,
    pub active: Option<i8>,
    pub email_validated: Option<i8>,
    pub image: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::linked_account::Entity")]
    LinkedAccount,
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::UserId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    N4user,
}

impl Related<super::linked_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkedAccount.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::N4user.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
