import * as stylex from "@stylexjs/stylex";

export const anonymousHomeIntroBackgroundVars = stylex.defineVars({
  image:
    "linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.3)), var(--siteintro-background-image)",
});

export const anonymousHomeIntroBackgroundTheme = stylex.createTheme(
  anonymousHomeIntroBackgroundVars,
  {
    image:
      "linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.3)), var(--siteintro-background-image)",
  },
);

export const homeColors = stylex.defineVars({
  leftSidebarTabText: "lightgray",
  sidenavNoResultText: "mediumvioletred",
  sidenavIssueTitleMarker: "darkgray",
  sidenavShadow: "2px 2px 10px #888888",
  anonymousHomeFeaturePrimary: "#ff7332",
  authenticatedHomeSeriesTabLinkInteractionBorderBlockEnd: "#dddddd",
  authenticatedHomeSeriesTabLinkInteractionBorderBlockStart: "#eeeeee",
  authenticatedHomeSeriesTabLinkInteractionBorderInline: "#eeeeee",
  leftSidebarDirectProjectAvatar: "#000000",
  leftSidebarDirectProjectStarActive: "#e91e63",
  leftSidebarDirectProjectStarActiveHover: "#8a123b",
  leftSidebarDirectProjectStarIdle: "#eeeeee",
  leftSidebarFavoriteNestedProjectAvatar: "#000000",
  leftSidebarFavoriteNestedProjectStarActive: "#e91e63",
  leftSidebarFavoriteNestedProjectStarActiveHover: "#8a123b",
  leftSidebarFavoriteNestedProjectStarIdle: "#eeeeee",
  leftSidebarFavoriteOrganizationCount: "#808080",
  leftSidebarFavoriteOrganizationName: "#00bcd4",
  leftSidebarFavoriteOrganizationStarActive: "#e91e63",
  leftSidebarFavoriteOrganizationStarActiveHover: "#8a123b",
  leftSidebarFavoriteOrganizationStarIdle: "#eeeeee",
  leftSidebarFooterHeart: "#ff0000",
  leftSidebarProjectSubtabAccent: "#f36c22",
  leftSidebarRefreshAccent: "#03a9f4",
  leftSidebarTabAccent: "#f36c22",
  navigationAccent: "#5dbbe0",
  navigationCreateAction: "#f36c22",
  navigationDivider: "#788ba7",
  sidenavFavoriteStarActive: "#e91e63",
  sidenavFavoriteStarActiveHover: "#8a123b",
  sidenavFavoriteStarIdle: "#eeeeee",
  sidenavLogoutHover: "#9c27b0",
  sidenavOrganizationName: "#00bcd4",
  sidenavScrollbarThumb: "#2788ba",
  sidenavScrollbarTrack: "#d3d3d3",
  sidenavSearchFocusAccent: "#e91e63",
  sidenavSubtabAccent: "#f36c22",
  sidenavTabAccent: "#3592b5",
  textMuted: "#a2a2a2",
  textOnAccent: "#ffffff",
  textOnDarkHover: "#fcfcfc",
  anonymousHomeFeatureBorderColor: "#e8e8e8",
  anonymousHomeFeatureSurface: "#ffffff",
  anonymousHomeFeatureText: "#333333",
  anonymousHomeIntroBorderColor: "#333333",
  anonymousHomeIntroCtaBorderColor: "#e95e01",
  anonymousHomeIntroCtaBoxShadow: "0px 1px 0px rgba(0, 0, 0, 0.05)",
  anonymousHomeIntroCtaHoverSurface: "#e95e01",
  anonymousHomeIntroCtaSurface: "#ff7332",
  anonymousHomeIntroCtaText: "#ffffff",
  anonymousHomeIntroHeadingText: "#fafafa",
  anonymousHomeIntroTaglineItemText: "#ffffff",
  anonymousSiteSignupBorderColor: "#e95e01",
  anonymousSiteSignupBoxShadow: "0px 1px 0px rgba(0, 0, 0, 0.05)",
  anonymousSiteSignupHoverSurface: "#e95e01",
  anonymousSiteSignupSurface: "#ff7332",
  anonymousSiteSignupText: "#ffffff",
  authenticatedHomeDefaultLoginButtonBorderColor: "rgba(0, 0, 0, 0.15)",
  authenticatedHomeDefaultLoginButtonInteractionBorderColor: "rgba(0, 0, 0, 0.25)",
  authenticatedHomeDefaultLoginButtonInteractionSurface: "#f1f1f1",
  authenticatedHomeDefaultLoginButtonInteractionText: "#292929",
  authenticatedHomeDefaultLoginButtonShadow: "0px 1px 0px rgba(0, 0, 0, 0.05)",
  authenticatedHomeDefaultLoginButtonSurface: "#ffffff",
  authenticatedHomeDefaultLoginButtonText: "#333333",
  authenticatedHomeDefaultLoginPopoverArrowBorderColor: "rgba(0, 0, 0, 0.25)",
  authenticatedHomeDefaultLoginPopoverArrowInnerBorderColor: "#ffffff",
  authenticatedHomeDefaultLoginPopoverBorderColor: "rgba(0, 0, 0, 0.2)",
  authenticatedHomeDefaultLoginPopoverShadow: "-2px 2px 1px rgba(0, 0, 0, 0.1)",
  authenticatedHomeDefaultLoginPopoverSurface: "#ffffff",
  authenticatedHomeDefaultLoginPopoverText: "#333333",
  authenticatedHomeDefaultLoginPopoverTitleBorderColor: "#ebebeb",
  authenticatedHomeDefaultLoginPopoverTitleSurface: "#f7f7f7",
  authenticatedHomeIntroGuideCtaBorderColor: "#e95e01",
  authenticatedHomeIntroGuideCtaBoxShadow: "0px 1px 0px rgba(0, 0, 0, 0.05)",
  authenticatedHomeIntroGuideCtaHoverSurface: "#e95e01",
  authenticatedHomeIntroGuideCtaSurface: "#ff7332",
  authenticatedHomeIntroGuideCtaText: "#ffffff",
  authenticatedHomeIntroGuideHeadingText: "#333333",
  authenticatedHomeIntroGuideTableBorderBottomColor: "#eeeeee",
  authenticatedHomeIntroGuideToggleBorderColor: "rgba(0, 0, 0, 0.1)",
  authenticatedHomeIntroGuideToggleBorderTopColor: "#ffffff",
  authenticatedHomeIntroGuideToggleText: "#95a5a6",
  authenticatedHomeNotificationAuthorHoverText: "#f36c22",
  authenticatedHomeNotificationAuthorText: "#666666",
  authenticatedHomeNotificationEmptySurface: "#8b8b8b",
  authenticatedHomeNotificationEmptyText: "#ffffff",
  authenticatedHomeNotificationMessageText: "#888888",
  authenticatedHomeNotificationMetaText: "#bbbbbb",
  authenticatedHomeNotificationMoreSurface: "#e0e0e0",
  authenticatedHomeNotificationPaginationBorderColor: "rgba(0, 0, 0, 0.15)",
  authenticatedHomeNotificationPaginationBoxShadow: "0px 1px 0px rgba(0, 0, 0, 0.05)",
  authenticatedHomeNotificationPaginationInteractionBorderColor: "rgba(0, 0, 0, 0.25)",
  authenticatedHomeNotificationPaginationInteractionSurface: "#f1f1f1",
  authenticatedHomeNotificationPaginationInteractionText: "#292929",
  authenticatedHomeNotificationPaginationSurface: "#ffffff",
  authenticatedHomeNotificationPaginationText: "#333333",
  authenticatedHomeNotificationRowHoverSurface: "#f5f5f5",
  authenticatedHomeNotificationRowText: "#dddddd",
  authenticatedHomeNotificationTitleText: "#51aacc",
  authenticatedHomeNotificationTypeBaseText: "#4caf50",
  authenticatedHomeNotificationTypeChangedText: "#65c9df",
  authenticatedHomeNotificationTypeClosedText: "#fd6956",
  authenticatedHomeNotificationTypeCommentText: "#8b008b",
  authenticatedHomeNotificationTypeEllipsisText: "#808080",
  authenticatedHomeNotificationTypeInfoText: "#999999",
  authenticatedHomeNotificationTypeListText: "#795548",
  authenticatedHomeNotificationTypeMergedText: "#65c9df",
  authenticatedHomeNotificationTypeRejectedText: "#fd8658",
  authenticatedHomeNotificationTypeWarningText: "#fcc666",
  authenticatedHomeNotificationUpdatedSurface: "#ff9800",
  authenticatedHomeNotificationUpdatedText: "#ffffff",
  authenticatedHomePageWrapSurface: "#ffffff",
  authenticatedHomeSeriesTabActiveSurface: "#ffffff",
  authenticatedHomeSeriesTabActiveText: "#555555",
  authenticatedHomeSeriesTabLinkFocusSurface: "#eeeeee",
  authenticatedHomeSeriesTabLinkHoverSurface: "#f2f2f2",
  authenticatedHomeSeriesTabLinkText: "#3592b5",
  authenticatedHomeSeriesTabsBorderColor: "#dddddd",
  framedSiteMainSurface: "#ffffff",
  globalGnbBrandSurface: "#ff5722",
  globalGnbBrandText: "#803131",
  globalGnbInnerText: "#788ba7",
  globalGnbNavText: "#a2a2a2",
  globalGnbOuterProjectSurface: "rgba(0, 0, 0, 0.35)",
  globalGnbOuterSurface: "#1b1b1b",
  globalGnbSearchBoxSurface: "#ffffff",
  globalGnbSearchInputBackground: "#ffffff",
  globalGnbSearchInputColor: "#555555",
  globalGnbSearchInputFocusBorderColor: "#f36c22",
  globalGnbSearchScopeCaretColor: "#383838",
  globalGnbSearchScopeItemText: "#292929",
  globalGnbSearchScopeMenuBorder: "rgba(0, 0, 0, 0.2)",
  globalGnbSearchScopeMenuInteractionSurface: "rgba(0, 0, 0, 0.15)",
  globalGnbSearchScopeMenuInteractionText: "#292929",
  globalGnbSearchScopeMenuShadow: "0 2px 10px rgba(0, 0, 0, 0.2)",
  globalGnbSearchScopeMenuSurface: "#ffffff",
  globalGnbSearchScopeMenuText: "#ffffff",
  globalGnbSearchScopeToggleBorder: "rgba(0, 0, 0, 0.15)",
  globalGnbSearchScopeToggleInteractionBorder: "rgba(0, 0, 0, 0.25)",
  globalGnbSearchScopeToggleInteractionSurface: "#f1f1f1",
  globalGnbSearchScopeToggleInteractionText: "#292929",
  globalGnbSearchScopeToggleOpenShadow:
    "inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05)",
  globalGnbSearchScopeToggleShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
  globalGnbSearchScopeToggleSurface: "#f7f7f7",
  globalGnbSearchScopeToggleText: "#333333",
  globalGnbSearchSubmitColor: "#000000",
  globalSidebarOpenPinInteractionText: "#ffffff",
  globalSidebarOpenPinSurface: "#03a9f4",
  globalSidebarOpenPinText: "#3e2723",
  leftSidebarAccountHoverText: "#ffffff",
  leftSidebarAccountLogoutHoverSurface: "#9c27b0",
  leftSidebarAccountLogoutSurface: "#999999",
  leftSidebarAccountLogoutText: "#ffffff",
  leftSidebarAccountLogoutTextShadow: "0 -1px 0 rgba(0, 0, 0, 0.25)",
  leftSidebarAccountText: "#808080",
  leftSidebarClosePinInteractionText: "#ffffff",
  leftSidebarClosePinSurface: "#03a9f4",
  leftSidebarClosePinText: "#3e2723",
  leftSidebarDirectProjectHoverSurface: "rgba(255, 255, 255, 0.15)",
  leftSidebarDirectProjectOwnerText: "#808080",
  leftSidebarDirectProjectText: "#ffffff",
  leftSidebarFavoriteDividerBorder: "#808080",
  leftSidebarFavoriteNestedProjectHoverSurface: "rgba(255, 255, 255, 0.15)",
  leftSidebarFavoriteNestedProjectPopoverArrowBorder: "rgba(0, 0, 0, 0.25)",
  leftSidebarFavoriteNestedProjectPopoverBorder: "rgba(0, 0, 0, 0.2)",
  leftSidebarFavoriteNestedProjectPopoverShadow: "-2px 2px 1px rgba(0, 0, 0, 0.1)",
  leftSidebarFavoriteNestedProjectPopoverSurface: "#03a9f4",
  leftSidebarFavoriteNestedProjectText: "#ffffff",
  leftSidebarFavoriteOrganizationHoverSurface: "rgba(255, 255, 255, 0.15)",
  leftSidebarFavoriteOrganizationText: "#ffffff",
  leftSidebarFavoriteSearchSurface: "#000000",
  leftSidebarFavoriteSearchText: "#ffffff",
  leftSidebarFooterText: "#808080",
  leftSidebarOuterBorder: "#000000",
  leftSidebarOuterSurface: "#333333",
  leftSidebarOuterText: "#ffffff",
  leftSidebarProfileAvatarSurface: "#dddddd",
  leftSidebarProjectSearchSurface: "#000000",
  leftSidebarProjectSearchText: "#ffffff",
  leftSidebarProjectSubtabActiveText: "#fcfcfc",
  leftSidebarProjectSubtabSurface: "#eeeeee",
  leftSidebarProjectSubtabText: "#000000",
  leftSidebarRecentIssueHoverSurface: "rgba(255, 255, 255, 0.15)",
  leftSidebarRecentIssueText: "#ffffff",
  leftSidebarRecentSearchSurface: "#000000",
  leftSidebarTabSurface: "#000000",
  navigationDropdownText: "#efefef",
  sidenavAccountLogoutSurface: "#999999",
  sidenavAccountLogoutText: "#ffffff",
  sidenavAccountLogoutTextShadow: "0 -1px 0 rgba(0, 0, 0, 0.25)",
  sidenavAccountText: "#808080",
  sidenavBorder: "#cccccc",
  sidenavOrganizationHoverSurface: "#f1f1f1",
  sidenavPopoverArrowBorder: "rgba(0, 0, 0, 0.25)",
  sidenavPopoverBorder: "rgba(0, 0, 0, 0.2)",
  sidenavPopoverShadow: "-2px 2px 1px rgba(0, 0, 0, 0.1)",
  sidenavPopoverSurface: "#03a9f4",
  sidenavSubtabActiveText: "#fcfcfc",
  sidenavSubtabSurface: "#eeeeee",
  sidenavSubtabText: "#000000",
  sidenavSurface: "#ffffff",
  sidenavTabActiveText: "#555555",
  sidenavTabBorder: "#dddddd",
  sidenavTabHoverBorder: "#eeeeee",
  sidenavTabHoverSurface: "#f2f2f2",
  sidenavText: "#000000",
  siteAdminAffixSurface: "#ad0000",
  siteAdminAffixText: "#ffffff",
  siteFooterProviderText: "#333333",
  siteFooterSurface: "#ffffff",
});
