import * as stylex from "@stylexjs/stylex";
import { globalBreakpoints } from "../theme.stylex";

export const markdownHelpColors = stylex.defineVars({
  navSurface: "#f7f7f7",
  navBorder: "#dddddd",
  navLabelSurface: "#c7c9c9",
  navText: "#9e9e9e",
  navTextActive: "#333333",
  paneSurface: "#ffffff",
  codeSurface: "#efefef",
  tableBorder: "#dcddde",
  tableHeaderSurface: "#f7f7f7",
});

export const markdownHelpNavStyles = stylex.create({
  root: {
    marginTop: "5px",
    marginRight: "0px",
    marginBottom: "0px",
    marginLeft: "0px",
  },
  nav: {
    backgroundColor: markdownHelpColors.navSurface,
    borderColor: markdownHelpColors.navBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    borderBottomStyle: "none",
    listStyle: "none",
  },
  navItem: {
    display: "inline-block",
    lineHeight: "20px",
    paddingTop: "5px",
    paddingRight: { default: "7px", [globalBreakpoints.mobile]: "8px" },
    paddingBottom: "5px",
    paddingLeft: { default: "7px", [globalBreakpoints.mobile]: "8px" },
  },
  navLabel: {
    backgroundColor: markdownHelpColors.navLabelSurface,
    borderRadius: "3px",
    color: "#ffffff",
    display: "inline-block",
    fontSize: "11.844px",
    fontWeight: "bold",
    lineHeight: "14px",
    padding: "2px 4px",
    textShadow: "none",
    verticalAlign: "baseline",
    whiteSpace: "nowrap",
  },
  navChoice: {
    color: {
      default: markdownHelpColors.navText,
      ":hover": markdownHelpColors.navTextActive,
    },
    cursor: "pointer",
    position: "relative",
  },
  navChoiceActive: {
    color: markdownHelpColors.navTextActive,
    fontWeight: "bold",
    "::before": {
      borderBottomColor: markdownHelpColors.navBorder,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderTopColor: "transparent",
      borderStyle: "outset outset solid outset",
      borderWidth: "7px",
      bottom: "0px",
      content: '" "',
      height: "0px",
      left: "50%",
      marginLeft: "-7px",
      overflow: "hidden",
      position: "absolute",
      width: "0px",
    },
    "::after": {
      borderBottomColor: markdownHelpColors.paneSurface,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderTopColor: "transparent",
      borderStyle: "outset outset solid outset",
      borderWidth: "7px",
      bottom: "-1px",
      content: '" "',
      height: "0px",
      left: "50%",
      marginLeft: "-7px",
      overflow: "hidden",
      position: "absolute",
      width: "0px",
    },
  },
  navButton: {
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    color: "inherit",
    cursor: "pointer",
    font: "inherit",
    padding: "0px",
    verticalAlign: "baseline",
  },
});

export const markdownHelpContentStyles = stylex.create({
  paneList: {
    backgroundColor: markdownHelpColors.paneSurface,
    listStyle: "none",
  },
  pane: {
    borderTopStyle: "none",
    height: "0px",
    overflow: "hidden",
  },
  paneActive: {
    borderBottomStyle: "none",
    borderColor: markdownHelpColors.navBorder,
    borderLeftStyle: "solid",
    borderRightStyle: "solid",
    borderTopStyle: "none",
    borderWidth: "1px",
    height: "auto",
    padding: "10px",
  },
  output: {
    clear: "both",
    fontSize: "1.1em",
    overflow: "auto",
    overflowWrap: "break-word",
  },
  inputPre: {
    backgroundColor: "transparent",
    borderStyle: "none",
    margin: "0px",
    padding: "0px",
    whiteSpace: "pre",
    overflowWrap: "normal",
  },
  outputCode: {
    borderColor: markdownHelpColors.navBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    fontSize: "13px",
    padding: "5px 5px 2px",
  },
  outputPre: {
    backgroundColor: markdownHelpColors.codeSurface,
    borderStyle: "none",
    fontSize: "1em",
    margin: "10px 0px",
    padding: "10px",
    wordBreak: "normal",
  },
  outputPreCode: {
    borderStyle: "none",
    margin: "0px",
    padding: "0px",
  },
  table: { borderCollapse: "collapse", margin: "15px" },
  tableHeader: {
    backgroundColor: markdownHelpColors.tableHeaderSurface,
    borderColor: markdownHelpColors.tableBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    minWidth: "45px",
    padding: "5px",
  },
  tableCell: {
    borderColor: markdownHelpColors.tableBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "5px",
    wordBreak: "break-all",
  },
  taskList: {
    fontWeight: "normal",
    lineHeight: "20px",
    listStyle: "disc",
    marginBottom: "16px",
    marginLeft: "0px",
    padding: "0px 0px 5px 2.5em",
  },
  taskCheckbox: { verticalAlign: "top" },
});
