import * as stylex from "@stylexjs/stylex";

export const organizationDirectoryColors = stylex.defineVars({
  descriptionText: "#bababa",
  emptyText: "#898989",
  linkInteractive: "#005580",
  metadataText: "#999999",
  paginationAccent: "#f36c22",
  paginationDelimiter: "#dddddd",
  paginationInputBorder: "#eeeeee",
  paginationInputShadow: "inset -1px -1px 2px rgba(0, 0, 0, 0.1)",
  paginationText: "#8e9094",
  rowDivider: "#dcdcdc",
  searchBorder: "#cccccc",
  searchText: "#555555",
  tabActiveText: "#555555",
  tabBorder: "#dddddd",
  tabFocusSurface: "#eeeeee",
  tabHoverBorder: "#eeeeee",
  tabHoverSurface: "#f2f2f2",
  tabSurface: "#ffffff",
  tabText: "#3592b5",
  titleText: "#333333",
});

export const styles = stylex.create({
  breadcrumbOuter: { boxSizing: "border-box", padding: "0px 10px", width: "100%" },
  breadcrumbInner: { margin: "0px auto" },
  tabsList: {
    borderBottom: `1px solid ${organizationDirectoryColors.tabBorder}`,
    listStyle: "none",
    margin: "10px 0px 20px",
    padding: "0px",
  },
  tabsItem: { float: "left", fontSize: "16px", marginBottom: "-1px" },
  tabsLink: {
    color: organizationDirectoryColors.tabText,
    display: "block",
    fontWeight: "700",
    lineHeight: "20px",
    marginRight: "2px",
    padding: "8px 30px",
    textDecoration: "none",
  },
  tabsActiveLink: {
    backgroundColor: organizationDirectoryColors.tabSurface,
    borderColor: organizationDirectoryColors.tabBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    borderBottomColor: "transparent",
    color: organizationDirectoryColors.tabActiveText,
    cursor: "default",
  },
  pageWrap: {
    boxSizing: "border-box",
    margin: "10px auto 0px",
    padding: "0px 10px",
    width: "100%",
  },
  page: { margin: "5px auto 0px", width: "100%" },
  searchWrap: { clear: "both", height: "30px", padding: "10px 0px" },
  searchContainer: { float: "left" },
  searchForm: { margin: "0px 0px 2px" },
  searchBar: {
    backgroundColor: "#ffffff",
    borderColor: organizationDirectoryColors.searchBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    height: "20px",
    lineHeight: "20px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    backgroundColor: "#ffffff",
    borderStyle: "none",
    borderWidth: "0px",
    boxShadow: "none",
    color: organizationDirectoryColors.searchText,
    fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    height: "20px",
    margin: "0px -5px",
    outline: "none",
    padding: "0px 5px",
    transition: "width 0.15s ease",
    width: "350px",
  },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    boxShadow: "none",
    height: "20px",
    outline: "none",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  icon: {
    display: "inline-block",
    fontFamily: "yobicon",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 1,
    verticalAlign: "baseline",
    "::before": { content: '"\\e225"' },
  },
  list: { clear: "both", listStyle: "none", margin: "0px 0px 20px", padding: "0px" },
  row: {
    borderBottom: `1px solid ${organizationDirectoryColors.rowDivider}`,
    overflow: "hidden",
    padding: "15px 0px 10px",
  },
  privateRow: { backgroundColor: "#fcfcfc" },
  avatar: {
    borderRadius: "3px",
    display: "inline",
    float: "left",
    height: "50px",
    marginRight: "10px",
    overflow: "hidden",
    position: "relative",
    width: "50px",
  },
  avatarImage: { height: "100%", verticalAlign: "top", width: "100%" },
  identity: { float: "left" },
  privateIdentity: { opacity: 0.3 },
  privateMessage: { color: "gray", float: "left" },
  header: { fontSize: "20px", fontWeight: "700", marginBottom: "5px", marginLeft: "10px" },
  titleLink: { color: organizationDirectoryColors.titleText, textDecoration: "none" },
  description: {
    color: organizationDirectoryColors.descriptionText,
    marginLeft: "10px",
    maxHeight: "100px",
    maxWidth: "647px",
    overflowY: "auto",
    textOverflow: "ellipsis",
  },
  nameTag: {
    color: organizationDirectoryColors.metadataText,
    fontSize: "11px",
    margin: "0px 0px 0px 10px",
  },
  empty: { padding: "100px 0px", textAlign: "center" },
  emptyIcon: (backgroundImage: string) => ({
    backgroundImage,
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  }),
  emptyMessage: {
    color: organizationDirectoryColors.emptyText,
    fontSize: "16px",
    fontWeight: "700",
    lineHeight: "20px",
    margin: "30px 0px",
  },
  pagination: { clear: "both", margin: "20px 0px", textAlign: "center", width: "100%" },
  paginationList: {
    display: "inline-block",
    fontSize: "0px",
    listStyle: "none",
    margin: "0px 0px 0px -120px",
    padding: "0px",
  },
  paginationItem: {
    color: organizationDirectoryColors.paginationText,
    display: "inline-block",
    fontSize: "12px",
    padding: "0px 10px",
  },
  paginationIconItem: { padding: "0px 5px" },
  paginationDelimiter: {
    color: organizationDirectoryColors.paginationDelimiter,
    padding: "0px 5px",
  },
  paginationLabel: { color: organizationDirectoryColors.paginationAccent, fontSize: "11px" },
  paginationDisabled: { color: organizationDirectoryColors.paginationText },
  paginationInput: {
    borderColor: organizationDirectoryColors.paginationInputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: {
      ":hover": organizationDirectoryColors.paginationInputShadow,
      ":focus": organizationDirectoryColors.paginationInputShadow,
    },
    fontWeight: "700",
    margin: "0px",
    textAlign: "center",
    width: "30px",
  },
});
