import * as stylex from "@stylexjs/stylex";

export const searchColors = stylex.defineVars({
  border: "#ddd",
  inputBorder: "#ccc",
  inputText: "#555",
  link: "#3592b5",
  surface: "#fff",
  resultHeadingAccent: "#f36c22",
  listBorder: "#ddd",
  listTitle: "#333",
  listPostId: "#999",
  categoryActiveBackground: "#51aacc",
  categoryActiveText: "#fff",
  categoryEmptyText: "#d3d2d3",
  avatarBorder: "#ececec",
  metaText: "#999",
  keywordBackground: "#6bc4e9",
});
export const styles = stylex.create({
  globalSearchGridRow: {
    display: "flow-root",
    width: "100%",
  },
  globalSearchCategoryColumn: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: "0%",
    minHeight: "30px",
    width: "14.893617021276595%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: "0%",
      width: "100%",
    },
  },
  globalSearchResultsColumn: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: "2.127659574468085%",
    minHeight: "30px",
    width: "82.97872340425532%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: "0%",
      width: "100%",
    },
  },
  breadcrumb: { margin: "0px auto" },
  // Frozen `_page.less` `.page-wrap-outer` and `_responsive.less` mobile cascade.
  page: {
    boxSizing: "border-box",
    marginTop: "10px",
    minHeight: "450px",
    padding: "0 10px",
    width: "100%",
    "@media (max-width: 900px)": {
      minWidth: "10px",
      padding: "0px !important",
    },
  },
  category: {
    borderRightColor: searchColors.border,
    borderRightStyle: "solid",
    borderRightWidth: "1px",
  },
  categoryItem: { fontSize: "13px", fontWeight: "bold", padding: "8px" },
  categoryItemActive: {
    backgroundColor: searchColors.categoryActiveBackground,
    borderRadius: "6px",
    color: searchColors.categoryActiveText,
    fontWeight: "bold",
    overflow: "auto",
  },
  categoryLink: { display: "block" },
  categoryLinkActive: { color: searchColors.categoryActiveText },
  categoryLinkEmpty: { color: searchColors.categoryEmptyText },
  categoryBadge: { paddingLeft: "2px", paddingRight: "2px" },
  categoryBadgeActive: { color: searchColors.categoryActiveText },
  searchBox: {
    backgroundColor: searchColors.surface,
    borderColor: searchColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "5px",
  },
  searchInput: {
    boxSizing: "border-box",
    borderStyle: "none",
    borderWidth: "0px",
    color: searchColors.inputText,
    height: "30px",
    width: "100%",
  },
  result: { borderTopColor: searchColors.border, borderTopStyle: "solid", borderTopWidth: "1px" },
  resultHeading: {
    fontSize: "16px",
    marginTop: "15px",
    marginBottom: "10px",
    fontWeight: "normal",
    paddingLeft: "15px",
    paddingRight: "15px",
  },
  resultHeadingAccent: { color: searchColors.resultHeadingAccent },
  resultList: { listStyle: "none", display: "block" },
  resultItem: {
    position: "relative",
    display: "block",
    float: "none",
    margin: "0",
    padding: "15px",
    borderBottomColor: searchColors.listBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  resultItemProject: {
    paddingTop: "15px",
    paddingRight: "15px",
    paddingBottom: "15px",
    paddingLeft: "60px",
  },
  resultTitleWrap: {
    lineHeight: "30px",
    fontSize: "16px",
    fontWeight: "bold",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
  },
  resultPostId: { color: searchColors.listPostId, fontWeight: "normal" },
  resultTitle: { color: searchColors.listTitle },
  avatar: {
    borderColor: searchColors.avatarBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    float: "left",
    height: "40px",
    marginLeft: "-55px",
    width: "40px",
  },
  avatarImage: {
    borderStyle: "none",
    borderWidth: "0px",
    height: "100%",
    verticalAlign: "top",
    width: "100%",
  },
  content: { display: "block", fontSize: "14px", paddingLeft: "20px" },
  contentNoPadding: { paddingLeft: "0px" },
  contentBody: { display: "block" },
  meta: { color: searchColors.metaText, fontSize: "13px", marginTop: "10px", paddingLeft: "20px" },
  metaNoPadding: { paddingLeft: "0px" },
  metaItem: { lineHeight: "20px", marginRight: "10px" },
  projectLink: { ":hover": { color: searchColors.link } },
  userLink: { color: searchColors.link, fontWeight: "bold" },
  keyword: { backgroundColor: searchColors.keywordBackground, padding: "2px" },
  emptyResult: {
    backgroundPosition: "center 50%",
    backgroundRepeat: "no-repeat",
    marginBottom: "20px",
    marginTop: "20px",
    minHeight: "250px",
    paddingLeft: "20px",
    paddingRight: "20px",
    textAlign: "center",
  },
  emptyResultBackground: (backgroundImage: string) => ({ backgroundImage }),
  // Frozen `_common.less` pagination declarations and effective `_page.less` cascade.
  paginationWrap: {
    clear: "both",
    width: "100%",
    margin: "20px 0",
    textAlign: "center",
  },
  paginationPageNums: {
    display: "inline-block",
    padding: 0,
    margin: 0,
    fontSize: 0,
    listStyle: "none",
    marginLeft: "-120px !important",
    "@media all and (max-width: 720px)": {
      marginLeft: "-120px !important",
    },
  },
  paginationPageNum: {
    display: "inline-block",
    padding: "0 10px",
    color: "#8e9094",
    fontSize: "12px",
  },
  paginationIconPageNum: { padding: "0 5px" },
  paginationIconLabel: { fontSize: "11px", color: "#f36c22" },
  paginationIconLabelOff: { color: "#8e9094" },
  paginationDelimiter: { color: "#ddd", padding: "0 5px" },
  paginationInput: {
    margin: 0,
    width: "30px",
    textAlign: "center",
    fontWeight: "bold",
    border: "1px solid #eee",
    ":hover": {
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
      borderColor: "#f36c22",
    },
    ":focus": {
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
      borderColor: "#f36c22",
    },
  },
  paginationNoSpinner: { MozAppearance: "textfield" },
  paginationIcon: (backgroundImage: string) => ({
    display: "inline-block",
    backgroundRepeat: "no-repeat",
    backgroundImage,
    verticalAlign: "middle",
  }),
  paginationPrev: {
    width: "6px",
    height: "9px",
    backgroundPosition: "-136px -139px",
    marginRight: "10px",
  },
  paginationPrevOff: { backgroundPosition: "-164px -2px" },
  paginationNext: {
    width: "6px",
    height: "9px",
    backgroundPosition: "-146px -139px",
    marginLeft: "10px",
  },
  paginationNextOff: { backgroundPosition: "-23px -13px" },
});
