import * as stylex from "@stylexjs/stylex";

export const searchColors = stylex.defineVars({
  border: "#ddd",
  inputBorder: "#ccc",
  inputText: "#555",
  link: "#3592b5",
  surface: "#fff",
  resultHeadingAccent: "#f36c22",
  listBorder: "#ddd",
  listTitle: "#333",
  listPostId: "#999",
  categoryActiveBackground: "#51aacc",
  categoryActiveText: "#fff",
  categoryEmptyText: "#d3d2d3",
  avatarBorder: "#ececec",
  metaText: "#999",
  keywordBackground: "#6bc4e9",
});
export const styles = stylex.create({
  globalSearchGridRow: {
    display: "flow-root",
    width: "100%",
  },
  globalSearchCategoryColumn: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: "0%",
    minHeight: "30px",
    width: "14.52991452991453%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: "0%",
      width: "100%",
    },
  },
  globalSearchResultsColumn: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: "2.564102564102564%",
    minHeight: "30px",
    width: "82.90598290598291%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: "0%",
      width: "100%",
    },
  },
  breadcrumb: { margin: "0px auto" },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  category: {
    borderRightColor: searchColors.border,
    borderRightStyle: "solid",
    borderRightWidth: "1px",
  },
  categoryItem: { fontSize: "13px", fontWeight: "bold", padding: "8px" },
  categoryItemActive: {
    backgroundColor: searchColors.categoryActiveBackground,
    borderRadius: "6px",
    color: searchColors.categoryActiveText,
    fontWeight: "bold",
    overflow: "auto",
  },
  categoryLink: { display: "block" },
  categoryLinkActive: { color: searchColors.categoryActiveText },
  categoryLinkEmpty: { color: searchColors.categoryEmptyText },
  categoryBadge: { paddingLeft: "2px", paddingRight: "2px" },
  categoryBadgeActive: { color: searchColors.categoryActiveText },
  searchBox: {
    backgroundColor: searchColors.surface,
    borderColor: searchColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "5px",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: searchColors.inputText,
    width: "100%",
  },
  result: { borderTopColor: searchColors.border, borderTopStyle: "solid", borderTopWidth: "1px" },
  resultHeading: {
    fontSize: "16px",
    marginTop: "15px",
    fontWeight: "normal",
    paddingLeft: "15px",
    paddingRight: "15px",
  },
  resultHeadingAccent: { color: searchColors.resultHeadingAccent },
  resultList: { listStyle: "none", display: "block" },
  resultItem: {
    position: "relative",
    display: "block",
    float: "none",
    margin: "0",
    padding: "15px",
    borderBottomColor: searchColors.listBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  resultItemProject: {
    paddingTop: "15px",
    paddingRight: "15px",
    paddingBottom: "15px",
    paddingLeft: "60px",
  },
  resultTitleWrap: {
    lineHeight: "30px",
    fontSize: "16px",
    fontWeight: "bold",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
  },
  resultPostId: { color: searchColors.listPostId, fontWeight: "normal" },
  resultTitle: { color: searchColors.listTitle },
  avatar: {
    borderColor: searchColors.avatarBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    float: "left",
    height: "40px",
    marginLeft: "-55px",
    width: "40px",
  },
  avatarImage: {
    borderStyle: "none",
    borderWidth: "0px",
    height: "100%",
    verticalAlign: "top",
    width: "100%",
  },
  content: { display: "block", fontSize: "14px", paddingLeft: "20px" },
  contentNoPadding: { paddingLeft: "0px" },
  contentBody: { display: "block" },
  meta: { color: searchColors.metaText, fontSize: "13px", marginTop: "10px", paddingLeft: "20px" },
  metaNoPadding: { paddingLeft: "0px" },
  metaItem: { lineHeight: "20px", marginRight: "10px" },
  projectLink: { ":hover": { color: searchColors.link } },
  userLink: { color: searchColors.link, fontWeight: "bold" },
  keyword: { backgroundColor: searchColors.keywordBackground, padding: "2px" },
  emptyResult: {
    backgroundPosition: "center 50%",
    backgroundRepeat: "no-repeat",
    marginBottom: "20px",
    marginTop: "20px",
    minHeight: "250px",
    paddingLeft: "20px",
    paddingRight: "20px",
    textAlign: "center",
  },
  emptyResultBackground: (backgroundImage: string) => ({ backgroundImage }),
});
