import * as stylex from "@stylexjs/stylex";

export const searchColors = stylex.defineVars({
  border: "#ddd",
  inputBorder: "#ccc",
  inputText: "#555",
  link: "#3592b5",
  surface: "#fff",
  resultHeadingAccent: "#f36c22",
  listBorder: "#ddd",
  listTitle: "#333",
  listPostId: "#999",
});
export const styles = stylex.create({
  breadcrumb: { margin: "0px auto" },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  category: {
    borderRightColor: searchColors.border,
    borderRightStyle: "solid",
    borderRightWidth: "1px",
  },
  searchBox: {
    backgroundColor: searchColors.surface,
    borderColor: searchColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "5px",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: searchColors.inputText,
    width: "100%",
  },
  result: { borderTopColor: searchColors.border, borderTopStyle: "solid", borderTopWidth: "1px" },
  categoryShell: {
    borderRightColor: searchColors.border,
    borderRightStyle: "solid",
    borderRightWidth: "1px",
  },
  resultHeading: {
    fontSize: "16px",
    marginTop: "15px",
    fontWeight: "normal",
    paddingLeft: "15px",
    paddingRight: "15px",
  },
  resultHeadingAccent: { color: searchColors.resultHeadingAccent },
  resultList: { listStyle: "none", display: "block" },
  resultItem: {
    position: "relative",
    display: "block",
    float: "none",
    margin: "0",
    padding: "15px",
    borderBottomColor: searchColors.listBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  resultItemProject: {
    paddingTop: "15px",
    paddingRight: "15px",
    paddingBottom: "15px",
    paddingLeft: "60px",
  },
  resultTitleWrap: {
    lineHeight: "30px",
    fontSize: "16px",
    fontWeight: "bold",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
  },
  resultPostId: { color: searchColors.listPostId, fontWeight: "normal" },
  resultTitle: { color: searchColors.listTitle },
});
