import * as stylex from "@stylexjs/stylex";

export const postDetailColors = stylex.defineVars({
  bodyText: "#333333",
  headerTitleText: "#000000",
  headerSurface: "#f2f2f2",
  headerIdText: "#939393",
  headerDateText: "#999999",
  metaText: "#999999",
  surface: "#ffffff",
  taskProgressSurface: "#d4d4d4",
  taskProgressRed: "red",
});

export const styles = stylex.create({
  // Frozen `_page.less` `.error-wrap` and `_sprites.less` `.ico-err2` parity.
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  labelBackground: (backgroundColor: string) => ({ backgroundColor }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  header: { color: postDetailColors.bodyText },
  title: {
    padding: "10px 20px",
    color: postDetailColors.headerTitleText,
    wordBreak: "break-all",
    backgroundColor: postDetailColors.headerSurface,
    borderRadius: "10px",
    fontSize: "18px",
    lineHeight: "30px",
  },
  boardId: {
    color: postDetailColors.headerIdText,
    fontSize: "14px",
    paddingRight: "10px",
  },
  date: {
    display: "inline-block",
    marginRight: "20px",
    color: postDetailColors.headerDateText,
    lineHeight: "29px",
    verticalAlign: "top",
  },
  body: { color: postDetailColors.bodyText },
  author: { display: "block", margin: "10px 20px" },
  content: { backgroundColor: postDetailColors.surface },
  actions: { margin: "10px 0px", textAlign: "right" },
  postEditAction: { marginLeft: "10px", paddingTop: "5px" },
  postDeleteAction: { marginLeft: "6px" },
  commentEditAction: { marginLeft: "10px" },
  commentDeleteAction: { marginLeft: "6px" },
  commentAuthor: {
    color: "#3f3e40",
    fontSize: "13px",
    marginRight: "5px",
    verticalAlign: "middle",
  },
  commentResponsiveAvatar: {
    display: "none",
    "@media all and (max-width: 720px)": { display: "inline-block" },
  },
  commentResponsiveAvatarWrap: {
    display: "inline-block",
    height: "32px",
    overflow: "hidden",
    verticalAlign: "top",
    width: "32px",
    "@media all and (max-width: 720px)": {
      height: "24px",
      marginTop: "-5px",
      width: "24px",
    },
  },
  commentAgo: { color: "#7F8C8D" },
  commentActionButton: {
    backgroundColor: "transparent",
    border: 0,
    outline: "none",
    padding: 0,
  },
  commentActionIcon: {
    backgroundImage: "none",
    color: "#000000",
    display: "inline-block",
    fontFamily: "yobicon",
    fontSize: "20px",
    fontStyle: "normal",
    fontVariant: "normal",
    fontWeight: 400,
    lineHeight: "20px",
    opacity: 0.2,
    textDecoration: "none",
    verticalAlign: "baseline",
    ":hover": { color: "#51aacc", opacity: 1 },
  },
  commentEditIcon: { marginTop: "2px", "::before": { content: '"\\e51d"' } },
  commentDeleteIcon: { "::before": { content: '"\\e838"' } },
  commentBody: {
    fontSize: "1.1em",
    padding: "15px 20px",
  },
  commentActionRow: { float: "right" },
  commentList: { listStyle: "none", margin: 0, padding: 0 },
  commentRow: { padding: "10px 0px", position: "relative" },
  commentAvatar: {
    float: "left",
    paddingLeft: "5px",
    "@media all and (max-width: 720px)": { display: "none" },
  },
  commentAvatarWrap: { display: "inline-block" },
  commentMedia: {
    border: "1px solid #BDC3C7",
    borderRadius: "3px",
    marginLeft: "52px",
    overflow: "hidden",
    "::before": {
      backgroundColor: "#f8f8f8",
      borderColor: "#BDC3C7",
      borderStyle: "solid",
      borderWidth: "0 0 1px 1px",
      content: '" "',
      height: "9px",
      left: "47px",
      position: "absolute",
      top: "23px",
      transform: "rotate(45deg)",
      width: "9px",
    },
    ":hover": { boxShadow: "2px 2px 1px 0 rgb(220, 220, 220)" },
    "@media all and (max-width: 720px)": {
      marginLeft: "0px",
      "::before": { display: "none" },
    },
  },
  commentMediaTarget: {
    border: "2px solid #03a9f4",
    "::before": { borderColor: "#03a9f4", borderWidth: "0 0 2px 2px" },
  },
  commentMeta: {
    backgroundColor: "#F7F7F7",
    height: "22px",
    marginBottom: 0,
    padding: "5px 15px",
    "@media all and (max-width: 720px)": { padding: "5px" },
  },
  childCommentReply: {
    fontSize: "12px",
    backgroundColor: "#fff",
    position: "relative",
    right: "10px",
    color: "#00b0e8",
    border: "1px solid #00b0e8",
    marginTop: "-32px",
    padding: "0 5px",
    borderRadius: "3px",
    float: "right",
    zIndex: 2,
    ":hover": {
      boxShadow: "1px 1px 2px #e0e0e0",
      cursor: "pointer",
      display: "block",
    },
  },
  childCommentReplyHidden: { display: "none" },
  childCommentReplyVisible: { display: "block" },
  childCommentFormVisible: { display: "block" },
  disabledCommentActions: { textAlign: "right" },
  commentUploadHelp: { textAlign: "right" },
  commentActions: { textAlign: "right" },
  commentUpdateForm: { display: "none" },
  commentUpdateFormVisible: { display: "block" },
  commentUpdateWriteBox: { padding: "10px" },
  commentUpdateTextareaBox: {
    display: "block",
    margin: "0px 0px 10px",
    padding: "0px 2px 0px 0px",
    position: "relative",
  },
  commentUpdateTextareaControl: {
    borderRadius: "0px 0px 3px 3px",
    boxShadow: "none",
    fontSize: "12px",
    height: "160px",
    margin: 0,
    resize: "vertical",
    width: "100%",
    ":focus": {
      borderColor: "#F36C22 !important",
      borderStyle: "solid",
      borderWidth: "1px",
    },
    "@media all and (max-width: 720px)": { fontSize: "16px !important" },
  },
  commentUpdateFileUpload: { display: "inline-block", position: "relative" },
  commentUpdateActionButton: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.15)",
    borderRadius: "3px !important",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
    color: "#333333",
    cursor: "pointer",
    display: "inline-block",
    fontSize: "14px",
    lineHeight: "20px",
    marginBottom: 0,
    marginLeft: ".3em",
    outline: "0 none",
    padding: "4px 12px !important",
    position: "relative",
    textAlign: "center",
    textShadow: "none",
    transition: "all 0.3s ease",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    zIndex: 2,
    ":first-child": { marginLeft: 0 },
    ":hover": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
    ":focus": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
    ":active": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
  },
  commentUpdateFileUploadLabel: {
    display: "block",
    transition: "background 0.3s",
  },
  commentUpdateSaveButton: {
    backgroundColor: "#3A7EE5 !important",
    borderColor: "#206EE5",
    color: "#ffffff",
    ":hover": {
      backgroundColor: "#206EE5 !important",
      borderColor: "#206EE5",
      color: "#ffffff",
    },
    ":focus": {
      backgroundColor: "#206EE5 !important",
      borderColor: "#206EE5",
      color: "#ffffff",
    },
    ":active": {
      backgroundColor: "#3A7EE5 !important",
      borderColor: "#206EE5",
      color: "#ffffff",
    },
  },
  commentUpdateChecklistWrap: { marginTop: "2px" },
  commentUpdateChecklistButton: {
    backgroundColor: "#eeeeee",
    borderColor: "transparent",
    boxShadow: "none",
    color: "#666666",
    fontSize: "13px !important",
    fontWeight: 600,
    marginTop: "1px",
    padding: "1px 10px !important",
    ":hover": {
      backgroundColor: "#fbe9e7",
      borderColor: "#EF9A9A",
      color: "#C93426",
    },
    ":focus": {
      backgroundColor: "#fbe9e7",
      borderColor: "#EF9A9A",
      color: "#C93426",
    },
  },
  commentUpdateChecklistIcon: {
    backgroundImage: "none",
    display: "inline-block",
    fontFamily: "yobicon",
    fontStyle: "normal",
    fontVariant: "normal",
    fontWeight: "normal",
    lineHeight: "20px",
    textDecoration: "none",
    verticalAlign: "baseline",
    "::before": { content: '"\\e25e"' },
  },
  commentUpdateFileUploadInput: {
    bottom: 0,
    height: 0,
    left: 0,
    opacity: 0,
    position: "fixed",
    right: 0,
    top: 0,
    width: 0,
  },
  commentUpdateActions: { marginTop: "10px", textAlign: "right" },
  commentUpdateEditorNav: {
    borderBottomColor: "#dddddd",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    height: "29px",
    listStyle: "none",
    margin: "0px !important",
    padding: 0,
    "::before": { content: '""', display: "table", lineHeight: "0px" },
    "::after": { clear: "both", content: '""', display: "table", lineHeight: "0px" },
  },
  commentUpdateEditorNavItem: { float: "left", marginBottom: "-2px" },
  commentUpdateEditorTabLink: {
    borderColor: "transparent",
    borderRadius: "4px 4px 0px 0px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#3592b5",
    display: "block",
    fontWeight: "bold",
    lineHeight: "20px",
    marginRight: "2px",
    padding: "4px 15px",
    textDecoration: "none",
    ":hover": {
      backgroundColor: "#F2F2F2",
      borderColor: "#eeeeee #eeeeee #dddddd",
      textDecoration: "none",
    },
    ":focus": {
      backgroundColor: "#eeeeee",
      borderColor: "#eeeeee #eeeeee #dddddd",
      textDecoration: "none",
    },
    "@media all and (max-width: 720px)": {
      paddingLeft: "5px !important",
      paddingRight: "5px !important",
    },
  },
  commentUpdateEditorTabLinkActive: {
    backgroundColor: "#ffffff",
    borderColor: "#dddddd",
    borderBottomColor: "transparent",
    color: "#555555",
    cursor: "default",
    fontWeight: "bold",
    ":hover": {
      backgroundColor: "#ffffff",
      borderColor: "#dddddd",
      borderBottomColor: "transparent",
      color: "#555555",
    },
    ":focus": {
      backgroundColor: "#ffffff",
      borderColor: "#dddddd",
      borderBottomColor: "transparent",
      color: "#555555",
    },
  },
  comments: {
    clear: "both",
    display: "block",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    "@media all and (max-width: 720px)": { padding: "2px" },
  },
  commentHeader: {
    color: "#222222",
    fontSize: "16px",
    lineHeight: "40px",
  },
  commentHeaderIcon: {
    backgroundImage: "none",
    display: "inline-block",
    fontFamily: "yobicon",
    fontStyle: "normal",
    fontVariant: "normal",
    fontWeight: 400,
    lineHeight: 1,
    textDecoration: "none",
    verticalAlign: "baseline",
    "::before": { content: '"\\e4b7"' },
  },
  commentDivider: { margin: 0 },
  sidebar: { padding: "15px 0px 0px 52px" },
  footer: { fontSize: 0, marginTop: 20, textAlign: "right" },
  watchWrapper: { float: "left" },
  watch: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.15)",
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
    color: "#333333",
    cursor: "pointer",
    display: "inline-block",
    fontSize: "14px",
    lineHeight: "20px",
    marginBottom: 0,
    marginLeft: ".3em",
    outline: "0 none",
    padding: "4px 12px",
    position: "relative",
    textAlign: "center",
    textShadow: "none",
    transition: "all 0.3s ease",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    zIndex: 2,
    ":first-child": { marginLeft: 0 },
    ":hover": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
    ":focus": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
    ":active": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
  },
  watchWatching: {
    backgroundColor: "#f4efea",
    borderColor: "#c9c5c1",
    color: "#333333",
    ":hover": { backgroundColor: "#e0dad4" },
    ":focus": { backgroundColor: "#e0dad4" },
  },
  editorTabContent: { overflow: "visible", position: "relative" },
  editorPane: { display: "none" },
  editorPaneActive: { display: "block" },
  originalMessageToggle: {
    borderStyle: "none",
    borderWidth: 0,
    paddingLeft: 5,
    paddingRight: 5,
  },
  deleteModalVisible: { display: "block" },
  historyModalVisible: { display: "block" },
  commentDeleteVisible: { display: "block" },
  commentBodyHidden: { display: "none" },
  keymapModalVisible: { display: "block" },
  disabledComment: { cursor: "text" },
  shareLinkHidden: { display: "none" },
  tasklistProgress: { width: 0 },
  tasklist: {
    boxShadow: "none",
    display: "none",
    filter: "none",
    padding: "10px 20px 0px",
  },
  taskTitle: { fontWeight: "500" },
  taskDoneCounter: { marginLeft: "5px" },
  taskProgress: { backgroundColor: postDetailColors.taskProgressSurface },
  taskProgressBar: {
    backgroundColor: postDetailColors.taskProgressRed,
    height: "2px",
    transitionDuration: "0.2s",
  },
  keymapWrapper: { float: "left", marginLeft: 55, padding: "10px 0px" },
  desktopMetadata: {
    float: "right",
    marginRight: "10px",
    marginTop: "10px",
    "@media all and (max-width: 720px)": { display: "none" },
  },
  mobileMetadata: {
    display: "none",
    float: "right",
    fontSize: "0.7em",
    "@media all and (max-width: 720px)": { display: "block" },
  },
});
