import * as stylex from "@stylexjs/stylex";

export const postDetailColors = stylex.defineVars({
  bodyText: "#333333",
  headerTitleText: "#000000",
  headerSurface: "#f2f2f2",
  headerIdText: "#939393",
  headerDateText: "#999999",
  metaText: "#999999",
  surface: "#ffffff",
  taskProgressSurface: "#d4d4d4",
  taskProgressRed: "red",
});

export const styles = stylex.create({
  // Frozen `_page.less` `.error-wrap` and `_sprites.less` `.ico-err2` parity.
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  labelBackground: (backgroundColor: string) => ({ backgroundColor }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  header: { color: postDetailColors.bodyText },
  title: {
    padding: "10px 20px",
    color: postDetailColors.headerTitleText,
    wordBreak: "break-all",
    backgroundColor: postDetailColors.headerSurface,
    borderRadius: "10px",
    fontSize: "18px",
    lineHeight: "30px",
  },
  boardId: {
    color: postDetailColors.headerIdText,
    fontSize: "14px",
    paddingRight: "10px",
  },
  date: {
    display: "inline-block",
    marginRight: "20px",
    color: postDetailColors.headerDateText,
    lineHeight: "29px",
    verticalAlign: "top",
  },
  body: { color: postDetailColors.bodyText },
  author: { display: "block", margin: "10px 20px" },
  content: { backgroundColor: postDetailColors.surface },
  actions: { margin: "10px 0px", textAlign: "right" },
  postEditAction: { marginLeft: "10px", paddingTop: "5px" },
  postDeleteAction: { marginLeft: "6px" },
  commentEditAction: { marginLeft: "10px" },
  commentDeleteAction: { marginLeft: "6px" },
  commentActionRow: { float: "right" },
  childCommentReply: {
    fontSize: "12px",
    backgroundColor: "#fff",
    position: "relative",
    right: "10px",
    color: "#00b0e8",
    border: "1px solid #00b0e8",
    marginTop: "-32px",
    padding: "0 5px",
    borderRadius: "3px",
    float: "right",
    zIndex: 2,
    ":hover": {
      boxShadow: "1px 1px 2px #e0e0e0",
      cursor: "pointer",
      display: "block",
    },
  },
  childCommentReplyHidden: { display: "none" },
  childCommentReplyVisible: { display: "block" },
  childCommentFormVisible: { display: "block" },
  disabledCommentActions: { textAlign: "right" },
  commentUploadHelp: { textAlign: "right" },
  commentActions: { textAlign: "right" },
  commentUpdateActions: { textAlign: "right" },
  comments: {
    clear: "both",
    display: "block",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
  },
  sidebar: { padding: "15px 0px 0px 52px" },
  footer: { fontSize: 0, marginTop: 20, textAlign: "right" },
  watchWrapper: { float: "left" },
  watch: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.15)",
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
    color: "#333333",
    cursor: "pointer",
    display: "inline-block",
    fontSize: "14px",
    lineHeight: "20px",
    marginBottom: 0,
    marginLeft: ".3em",
    outline: "0 none",
    padding: "4px 12px",
    position: "relative",
    textAlign: "center",
    textShadow: "none",
    transition: "all 0.3s ease",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    zIndex: 2,
    ":first-child": { marginLeft: 0 },
    ":hover": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
    ":focus": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
    ":active": {
      backgroundColor: "#f1f1f1",
      borderColor: "rgba(0, 0, 0, 0.25)",
      color: "#292929",
      textDecoration: "none",
    },
  },
  watchWatching: {
    backgroundColor: "#f4efea",
    borderColor: "#c9c5c1",
    color: "#333333",
    ":hover": { backgroundColor: "#e0dad4" },
    ":focus": { backgroundColor: "#e0dad4" },
  },
  editorTabContent: { overflow: "visible", position: "relative" },
  editorPane: { display: "none" },
  editorPaneActive: { display: "block" },
  originalMessageToggle: {
    borderStyle: "none",
    borderWidth: 0,
    paddingLeft: 5,
    paddingRight: 5,
  },
  deleteModalVisible: { display: "block" },
  historyModalVisible: { display: "block" },
  commentDeleteVisible: { display: "block" },
  commentBodyHidden: { display: "none" },
  commentEditorVisible: { display: "block" },
  keymapModalVisible: { display: "block" },
  disabledComment: { cursor: "text" },
  shareLinkHidden: { display: "none" },
  tasklistProgress: { width: 0 },
  tasklist: {
    boxShadow: "none",
    display: "none",
    filter: "none",
    padding: "10px 20px 0px",
  },
  taskTitle: { fontWeight: "500" },
  taskDoneCounter: { marginLeft: "5px" },
  taskProgress: { backgroundColor: postDetailColors.taskProgressSurface },
  taskProgressBar: {
    backgroundColor: postDetailColors.taskProgressRed,
    height: "2px",
    transitionDuration: "0.2s",
  },
  keymapWrapper: { float: "left", marginLeft: 55, padding: "10px 0px" },
  desktopMetadata: {
    float: "right",
    marginRight: "10px",
    marginTop: "10px",
    "@media all and (max-width: 720px)": { display: "none" },
  },
  mobileMetadata: {
    display: "none",
    float: "right",
    fontSize: "0.7em",
    "@media all and (max-width: 720px)": { display: "block" },
  },
});
