import * as stylex from "@stylexjs/stylex";

export const postDetailColors = stylex.defineVars({
  action: "#51a351",
  bodyText: "#333333",
  headerTitleText: "#000000",
  headerSurface: "#f2f2f2",
  headerIdText: "#939393",
  headerDateText: "#999999",
  metaText: "#999999",
  surface: "#ffffff",
  taskProgressSurface: "#d4d4d4",
  taskProgressRed: "red",
});

export const styles = stylex.create({
  labelBackground: (backgroundColor: string) => ({ backgroundColor }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  header: { color: postDetailColors.bodyText },
  title: {
    padding: "10px 20px",
    color: postDetailColors.headerTitleText,
    wordBreak: "break-all",
    backgroundColor: postDetailColors.headerSurface,
    borderRadius: "10px",
    fontSize: "18px",
    lineHeight: "30px",
  },
  boardId: {
    color: postDetailColors.headerIdText,
    fontSize: "14px",
    paddingRight: "10px",
  },
  date: {
    display: "inline-block",
    marginRight: "20px",
    color: postDetailColors.headerDateText,
    lineHeight: "29px",
    verticalAlign: "top",
  },
  body: { color: postDetailColors.bodyText },
  author: { display: "block", margin: "10px 20px" },
  content: { backgroundColor: postDetailColors.surface },
  actions: { margin: "10px 0px", textAlign: "right" },
  comments: {
    clear: "both",
    display: "block",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
  },
  sidebar: { padding: "15px 0px 0px 52px" },
  footer: { fontSize: 0, marginTop: 20, textAlign: "right" },
  watch: {
    backgroundColor: postDetailColors.action,
    borderColor: postDetailColors.action,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
  },
  editorTabContent: { overflow: "visible", position: "relative" },
  originalMessageToggle: {
    borderStyle: "none",
    borderWidth: 0,
    paddingLeft: 5,
    paddingRight: 5,
  },
  deleteModalVisible: { display: "block" },
  historyModalVisible: { display: "block" },
  commentDeleteVisible: { display: "block" },
  commentBodyHidden: { display: "none" },
  commentEditorVisible: { display: "block" },
  keymapModalVisible: { display: "block" },
  disabledComment: { cursor: "text" },
  shareLinkHidden: { display: "none" },
  tasklistProgress: { width: 0 },
  tasklist: {
    boxShadow: "none",
    display: "none",
    filter: "none",
    padding: "10px 20px 0px",
  },
  taskTitle: { fontWeight: "500" },
  taskDoneCounter: { marginLeft: "5px" },
  taskProgress: { backgroundColor: postDetailColors.taskProgressSurface },
  taskProgressBar: {
    backgroundColor: postDetailColors.taskProgressRed,
    height: "2px",
    transitionDuration: "0.2s",
  },
  keymapWrapper: { marginLeft: 55, padding: "10px 0px" },
  mobileMetadata: {
    display: "none",
    fontSize: "0.7em",
    "@media all and (max-width: 720px)": { display: "block" },
  },
});
