//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "comment_thread")]
pub struct Model {
    pub dtype: String,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub author_id: Option<i64>,
    pub author_login_id: Option<String>,
    pub author_name: Option<String>,
    pub state: Option<String>,
    pub created_date: Option<DateTime>,
    pub pull_request_id: Option<i64>,
    pub project_id: Option<i64>,
    pub prev_commit_id: Option<String>,
    pub commit_id: Option<String>,
    pub path: Option<String>,
    pub start_side: Option<String>,
    pub start_line: Option<i32>,
    pub start_column: Option<i32>,
    pub end_side: Option<String>,
    pub end_line: Option<i32>,
    pub end_column: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comment_thread_n4user::Entity")]
    CommentThreadN4user,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project,
    #[sea_orm(
        belongs_to = "super::pull_request::Entity",
        from = "Column::PullRequestId",
        to = "super::pull_request::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    PullRequest,
    #[sea_orm(has_many = "super::review_comment::Entity")]
    ReviewComment,
}

impl Related<super::comment_thread_n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentThreadN4user.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::pull_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequest.def()
    }
}

impl Related<super::review_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewComment.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::comment_thread_n4user::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::comment_thread_n4user::Relation::CommentThread
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
