//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "favorite_organization")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_favorite_organization_user_id_organization_id_1")]
    pub user_id: Option<i64>,
    #[sea_orm(unique_key = "uq_favorite_organization_user_id_organization_id_1")]
    pub organization_id: Option<i64>,
    pub organization_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::UserId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    N4user,
    #[sea_orm(
        belongs_to = "super::organization::Entity",
        from = "Column::OrganizationId",
        to = "super::organization::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Organization,
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::N4user.def()
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organization.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
