//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "issue_comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub contents: Option<String>,
    pub created_date: Option<DateTime>,
    pub author_id: Option<i64>,
    pub author_login_id: Option<String>,
    pub author_name: Option<String>,
    pub issue_id: Option<i64>,
    pub project_id: i64,
    pub parent_comment_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::issue::Entity",
        from = "Column::IssueId",
        to = "super::issue::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Issue,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentCommentId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::issue_comment_voter::Entity")]
    IssueCommentVoter,
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issue.def()
    }
}

impl Related<super::issue_comment_voter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueCommentVoter.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::issue_comment_voter::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::issue_comment_voter::Relation::IssueComment
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
