//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_label_1")]
    pub category: Option<String>,
    #[sea_orm(unique_key = "uq_label_1")]
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_label::Entity")]
    ProjectLabel,
}

impl Related<super::project_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectLabel.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_label::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_label::Relation::Label.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
