//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notification_event_n4user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub notification_event_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub n4user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::N4userId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    N4user,
    #[sea_orm(
        belongs_to = "super::notification_event::Entity",
        from = "Column::NotificationEventId",
        to = "super::notification_event::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    NotificationEvent,
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::N4user.def()
    }
}

impl Related<super::notification_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
