//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notification_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: Option<String>,
    pub sender_id: Option<i64>,
    pub created: Option<DateTime>,
    pub resource_type: Option<String>,
    pub resource_id: Option<String>,
    pub event_type: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub old_value: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub new_value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notification_event_n4user::Entity")]
    NotificationEventN4user,
    #[sea_orm(has_many = "super::notification_mail::Entity")]
    NotificationMail,
}

impl Related<super::notification_event_n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEventN4user.def()
    }
}

impl Related<super::notification_mail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationMail.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::notification_event_n4user::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::notification_event_n4user::Relation::NotificationEvent
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
