//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "organization")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    pub created: Option<DateTime>,
    pub descr: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::favorite_organization::Entity")]
    FavoriteOrganization,
    #[sea_orm(has_many = "super::organization_user::Entity")]
    OrganizationUser,
    #[sea_orm(has_many = "super::project::Entity")]
    Project,
    #[sea_orm(has_many = "super::user_enrolled_organization::Entity")]
    UserEnrolledOrganization,
}

impl Related<super::favorite_organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoriteOrganization.def()
    }
}

impl Related<super::organization_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUser.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::user_enrolled_organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEnrolledOrganization.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_enrolled_organization::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_enrolled_organization::Relation::Organization
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
