//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "play_evolutions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub hash: String,
    pub applied_at: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub apply_script: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub revert_script: Option<String>,
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_problem: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
