//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "posting")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub body: Option<String>,
    pub created_date: Option<DateTime>,
    pub updated_date: Option<DateTime>,
    pub author_id: Option<i64>,
    pub author_login_id: Option<String>,
    pub author_name: Option<String>,
    #[sea_orm(unique_key = "uq_posting_1")]
    pub project_id: Option<i64>,
    #[sea_orm(unique_key = "uq_posting_1")]
    pub number: Option<i64>,
    pub num_of_comments: Option<i32>,
    pub notice: Option<i16>,
    pub readme: Option<i16>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub history: Option<String>,
    pub parent_id: Option<i64>,
    pub updated_by_author_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::posting_comment::Entity")]
    PostingComment,
    #[sea_orm(has_many = "super::posting_issue_label::Entity")]
    PostingIssueLabel,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project,
}

impl Related<super::posting_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostingComment.def()
    }
}

impl Related<super::posting_issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostingIssueLabel.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        super::posting_issue_label::Relation::IssueLabel.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::posting_issue_label::Relation::Posting.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
