//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pull_request_commit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pull_request_id: Option<i64>,
    pub commit_id: Option<String>,
    pub author_date: Option<DateTime>,
    pub created: Option<DateTime>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub commit_message: Option<String>,
    pub commit_short_id: Option<String>,
    pub author_email: Option<String>,
    pub state: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pull_request::Entity",
        from = "Column::PullRequestId",
        to = "super::pull_request::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    PullRequest,
}

impl Related<super::pull_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
