//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    pub active: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::organization_user::Entity")]
    OrganizationUser,
    #[sea_orm(has_many = "super::project_user::Entity")]
    ProjectUser,
}

impl Related<super::organization_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUser.def()
    }
}

impl Related<super::project_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
