//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "issue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub body: Option<String>,
    pub created_date: Option<DateTime>,
    pub updated_date: Option<DateTime>,
    pub author_id: Option<i64>,
    pub author_login_id: Option<String>,
    pub author_name: Option<String>,
    #[sea_orm(unique_key = "uq_issue_1")]
    pub project_id: Option<i64>,
    #[sea_orm(unique_key = "uq_issue_1")]
    pub number: Option<i64>,
    pub num_of_comments: Option<i32>,
    pub state: Option<i32>,
    pub due_date: Option<DateTime>,
    pub milestone_id: Option<i64>,
    pub assignee_id: Option<i64>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub history: Option<String>,
    pub parent_id: Option<i64>,
    pub weight: Option<i8>,
    pub updated_by_author_id: Option<i64>,
    pub is_draft: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assignee::Entity",
        from = "Column::AssigneeId",
        to = "super::assignee::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Assignee,
    #[sea_orm(has_many = "super::favorite_issue::Entity")]
    FavoriteIssue,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::issue_comment::Entity")]
    IssueComment,
    #[sea_orm(has_many = "super::issue_event::Entity")]
    IssueEvent,
    #[sea_orm(has_many = "super::issue_issue_label::Entity")]
    IssueIssueLabel,
    #[sea_orm(has_many = "super::issue_sharer::Entity")]
    IssueSharer,
    #[sea_orm(has_many = "super::issue_voter::Entity")]
    IssueVoter,
    #[sea_orm(
        belongs_to = "super::milestone::Entity",
        from = "Column::MilestoneId",
        to = "super::milestone::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Milestone,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Project,
    #[sea_orm(has_many = "super::recent_issue::Entity")]
    RecentIssue,
}

impl Related<super::assignee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignee.def()
    }
}

impl Related<super::favorite_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoriteIssue.def()
    }
}

impl Related<super::issue_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComment.def()
    }
}

impl Related<super::issue_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueEvent.def()
    }
}

impl Related<super::issue_issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueIssueLabel.def()
    }
}

impl Related<super::issue_sharer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueSharer.def()
    }
}

impl Related<super::issue_voter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueVoter.def()
    }
}

impl Related<super::milestone::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Milestone.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::recent_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecentIssue.def()
    }
}

impl Related<super::issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        super::issue_issue_label::Relation::IssueLabel.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::issue_issue_label::Relation::Issue.def().rev())
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::issue_voter::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::issue_voter::Relation::Issue.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
