//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "linked_account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_credential_id: Option<i64>,
    pub provider_user_id: Option<String>,
    pub provider_key: Option<String>,
    pub provider_display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub password: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub access_token: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub refresh_token: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub id_token: Option<String>,
    pub access_token_expires_at: Option<DateTime>,
    pub refresh_token_expires_at: Option<DateTime>,
    pub scope: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_credential::Entity",
        from = "Column::UserCredentialId",
        to = "super::user_credential::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    UserCredential,
}

impl Related<super::user_credential::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCredential.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
