//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "n4user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub login_id: Option<String>,
    pub password: Option<String>,
    pub password_salt: Option<String>,
    pub email: Option<String>,
    pub remember_me: Option<i8>,
    pub state: Option<String>,
    pub last_state_modified_date: Option<DateTime>,
    pub created_date: Option<DateTime>,
    pub lang: Option<String>,
    #[sea_orm(unique)]
    pub token: Option<String>,
    pub is_guest: Option<i8>,
    pub english_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assignee::Entity")]
    Assignee,
    #[sea_orm(has_many = "super::comment_thread_n4user::Entity")]
    CommentThreadN4user,
    #[sea_orm(has_many = "super::email::Entity")]
    Email,
    #[sea_orm(has_many = "super::favorite_issue::Entity")]
    FavoriteIssue,
    #[sea_orm(has_many = "super::favorite_organization::Entity")]
    FavoriteOrganization,
    #[sea_orm(has_many = "super::favorite_project::Entity")]
    FavoriteProject,
    #[sea_orm(has_many = "super::issue_comment_voter::Entity")]
    IssueCommentVoter,
    #[sea_orm(has_many = "super::issue_sharer::Entity")]
    IssueSharer,
    #[sea_orm(has_many = "super::issue_voter::Entity")]
    IssueVoter,
    #[sea_orm(has_many = "super::mention::Entity")]
    Mention,
    #[sea_orm(has_many = "super::notification_event_n4user::Entity")]
    NotificationEventN4user,
    #[sea_orm(has_many = "super::organization_user::Entity")]
    OrganizationUser,
    #[sea_orm(has_many = "super::project_transfer::Entity")]
    ProjectTransfer,
    #[sea_orm(has_many = "super::project_user::Entity")]
    ProjectUser,
    #[sea_orm(has_many = "super::pull_request_reviewers::Entity")]
    PullRequestReviewers,
    #[sea_orm(has_many = "super::recent_issue::Entity")]
    RecentIssue,
    #[sea_orm(has_many = "super::recently_visited_projects::Entity")]
    RecentlyVisitedProjects,
    #[sea_orm(has_many = "super::site_admin::Entity")]
    SiteAdmin,
    #[sea_orm(has_many = "super::unwatch::Entity")]
    Unwatch,
    #[sea_orm(has_many = "super::user_credential::Entity")]
    UserCredential,
    #[sea_orm(has_many = "super::user_enrolled_organization::Entity")]
    UserEnrolledOrganization,
    #[sea_orm(has_many = "super::user_enrolled_project::Entity")]
    UserEnrolledProject,
    #[sea_orm(has_many = "super::user_project_notification::Entity")]
    UserProjectNotification,
    #[sea_orm(has_many = "super::user_setting::Entity")]
    UserSetting,
    #[sea_orm(has_many = "super::user_verification::Entity")]
    UserVerification,
    #[sea_orm(has_many = "super::watch::Entity")]
    Watch,
}

impl Related<super::assignee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignee.def()
    }
}

impl Related<super::comment_thread_n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentThreadN4user.def()
    }
}

impl Related<super::email::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Email.def()
    }
}

impl Related<super::favorite_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoriteIssue.def()
    }
}

impl Related<super::favorite_organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoriteOrganization.def()
    }
}

impl Related<super::favorite_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoriteProject.def()
    }
}

impl Related<super::issue_comment_voter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueCommentVoter.def()
    }
}

impl Related<super::issue_sharer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueSharer.def()
    }
}

impl Related<super::issue_voter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueVoter.def()
    }
}

impl Related<super::mention::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mention.def()
    }
}

impl Related<super::notification_event_n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationEventN4user.def()
    }
}

impl Related<super::organization_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationUser.def()
    }
}

impl Related<super::project_transfer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectTransfer.def()
    }
}

impl Related<super::project_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectUser.def()
    }
}

impl Related<super::pull_request_reviewers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequestReviewers.def()
    }
}

impl Related<super::recent_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecentIssue.def()
    }
}

impl Related<super::recently_visited_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecentlyVisitedProjects.def()
    }
}

impl Related<super::site_admin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteAdmin.def()
    }
}

impl Related<super::unwatch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Unwatch.def()
    }
}

impl Related<super::user_credential::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCredential.def()
    }
}

impl Related<super::user_enrolled_organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEnrolledOrganization.def()
    }
}

impl Related<super::user_enrolled_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEnrolledProject.def()
    }
}

impl Related<super::user_project_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProjectNotification.def()
    }
}

impl Related<super::user_setting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSetting.def()
    }
}

impl Related<super::user_verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserVerification.def()
    }
}

impl Related<super::watch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watch.def()
    }
}

impl Related<super::comment_thread::Entity> for Entity {
    fn to() -> RelationDef {
        super::comment_thread_n4user::Relation::CommentThread.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::comment_thread_n4user::Relation::N4user.def().rev())
    }
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        super::issue_voter::Relation::Issue.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::issue_voter::Relation::N4user.def().rev())
    }
}

impl Related<super::issue_comment::Entity> for Entity {
    fn to() -> RelationDef {
        super::issue_comment_voter::Relation::IssueComment.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::issue_comment_voter::Relation::N4user.def().rev())
    }
}

impl Related<super::notification_event::Entity> for Entity {
    fn to() -> RelationDef {
        super::notification_event_n4user::Relation::NotificationEvent.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::notification_event_n4user::Relation::N4user
                .def()
                .rev(),
        )
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_enrolled_organization::Relation::Organization.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_enrolled_organization::Relation::N4user
                .def()
                .rev(),
        )
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_enrolled_project::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_enrolled_project::Relation::N4user.def().rev())
    }
}

impl Related<super::pull_request::Entity> for Entity {
    fn to() -> RelationDef {
        super::pull_request_reviewers::Relation::PullRequest.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::pull_request_reviewers::Relation::N4user.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
