//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "posting_issue_label")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub posting_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub issue_label_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::issue_label::Entity",
        from = "Column::IssueLabelId",
        to = "super::issue_label::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    IssueLabel,
    #[sea_orm(
        belongs_to = "super::posting::Entity",
        from = "Column::PostingId",
        to = "super::posting::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Posting,
}

impl Related<super::issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabel.def()
    }
}

impl Related<super::posting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posting.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
