//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_transfer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sender_id: Option<i64>,
    pub destination: Option<String>,
    pub project_id: Option<i64>,
    pub requested: Option<DateTime>,
    pub confirm_key: Option<String>,
    pub accepted: Option<i8>,
    pub new_project_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::SenderId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    N4user,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project,
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::N4user.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
