//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_visitation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_project_visitation_1")]
    pub project_id: Option<i64>,
    #[sea_orm(unique_key = "uq_project_visitation_1")]
    pub recently_visited_projects_id: Option<i64>,
    pub visited: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Project,
    #[sea_orm(
        belongs_to = "super::recently_visited_projects::Entity",
        from = "Column::RecentlyVisitedProjectsId",
        to = "super::recently_visited_projects::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    RecentlyVisitedProjects,
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::recently_visited_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecentlyVisitedProjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
