//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    pub overview: Option<String>,
    pub vcs: Option<String>,
    pub siteurl: Option<String>,
    pub owner: Option<String>,
    pub created_date: Option<DateTime>,
    pub last_issue_number: Option<i64>,
    pub last_posting_number: Option<i64>,
    pub original_project_id: Option<i64>,
    pub last_pushed_date: Option<DateTime>,
    pub default_reviewer_count: Option<i32>,
    pub is_using_reviewer_count: Option<i16>,
    pub organization_id: Option<i64>,
    pub project_scope: Option<String>,
    pub previous_owner_login_id: Option<String>,
    pub previous_name: Option<String>,
    pub previous_name_changed_time: Option<i64>,
    pub is_code_accessible_member_only: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assignee::Entity")]
    Assignee,
    #[sea_orm(has_many = "super::comment_thread::Entity")]
    CommentThread,
    #[sea_orm(has_many = "super::commit_comment::Entity")]
    CommitComment,
    #[sea_orm(has_many = "super::favorite_project::Entity")]
    FavoriteProject,
    #[sea_orm(has_many = "super::issue::Entity")]
    Issue,
    #[sea_orm(has_many = "super::issue_label::Entity")]
    IssueLabel,
    #[sea_orm(has_many = "super::issue_label_category::Entity")]
    IssueLabelCategory,
    #[sea_orm(has_many = "super::milestone::Entity")]
    Milestone,
    #[sea_orm(
        belongs_to = "super::organization::Entity",
        from = "Column::OrganizationId",
        to = "super::organization::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Organization,
    #[sea_orm(has_many = "super::posting::Entity")]
    Posting,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::OriginalProjectId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::project_label::Entity")]
    ProjectLabel,
    #[sea_orm(has_many = "super::project_menu_setting::Entity")]
    ProjectMenuSetting,
    #[sea_orm(has_many = "super::project_pushed_branch::Entity")]
    ProjectPushedBranch,
    #[sea_orm(has_many = "super::project_transfer::Entity")]
    ProjectTransfer,
    #[sea_orm(has_many = "super::project_user::Entity")]
    ProjectUser,
    #[sea_orm(has_many = "super::project_visitation::Entity")]
    ProjectVisitation,
    #[sea_orm(has_many = "super::recent_project::Entity")]
    RecentProject,
    #[sea_orm(has_many = "super::title_head::Entity")]
    TitleHead,
    #[sea_orm(has_many = "super::user_enrolled_project::Entity")]
    UserEnrolledProject,
    #[sea_orm(has_many = "super::user_project_notification::Entity")]
    UserProjectNotification,
    #[sea_orm(has_many = "super::webhook::Entity")]
    Webhook,
}

impl Related<super::assignee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignee.def()
    }
}

impl Related<super::comment_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentThread.def()
    }
}

impl Related<super::commit_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitComment.def()
    }
}

impl Related<super::favorite_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoriteProject.def()
    }
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issue.def()
    }
}

impl Related<super::issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabel.def()
    }
}

impl Related<super::issue_label_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueLabelCategory.def()
    }
}

impl Related<super::milestone::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Milestone.def()
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organization.def()
    }
}

impl Related<super::posting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posting.def()
    }
}

impl Related<super::project_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectLabel.def()
    }
}

impl Related<super::project_menu_setting::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMenuSetting.def()
    }
}

impl Related<super::project_pushed_branch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectPushedBranch.def()
    }
}

impl Related<super::project_transfer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectTransfer.def()
    }
}

impl Related<super::project_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectUser.def()
    }
}

impl Related<super::project_visitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVisitation.def()
    }
}

impl Related<super::recent_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecentProject.def()
    }
}

impl Related<super::title_head::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TitleHead.def()
    }
}

impl Related<super::user_enrolled_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEnrolledProject.def()
    }
}

impl Related<super::user_project_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProjectNotification.def()
    }
}

impl Related<super::webhook::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Webhook.def()
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_label::Relation::Label.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_label::Relation::Project.def().rev())
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_enrolled_project::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_enrolled_project::Relation::Project.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
