//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pull_request")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub body: Option<String>,
    pub to_project_id: Option<i64>,
    pub from_project_id: Option<i64>,
    pub to_branch: Option<String>,
    pub from_branch: Option<String>,
    pub contributor_id: Option<i64>,
    pub receiver_id: Option<i64>,
    pub created: Option<DateTime>,
    pub updated: Option<DateTime>,
    pub received: Option<DateTime>,
    pub state: Option<i32>,
    pub is_conflict: Option<i8>,
    pub is_merging: Option<i8>,
    pub last_commit_id: Option<String>,
    pub merged_commit_id_from: Option<String>,
    pub merged_commit_id_to: Option<String>,
    pub number: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comment_thread::Entity")]
    CommentThread,
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::ContributorId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    N4user2,
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::ReceiverId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    N4user1,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::FromProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project2,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ToProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project1,
    #[sea_orm(has_many = "super::pull_request_commit::Entity")]
    PullRequestCommit,
    #[sea_orm(has_many = "super::pull_request_event::Entity")]
    PullRequestEvent,
    #[sea_orm(has_many = "super::pull_request_reviewers::Entity")]
    PullRequestReviewers,
}

impl Related<super::comment_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentThread.def()
    }
}

impl Related<super::pull_request_commit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequestCommit.def()
    }
}

impl Related<super::pull_request_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequestEvent.def()
    }
}

impl Related<super::pull_request_reviewers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequestReviewers.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        super::pull_request_reviewers::Relation::N4user.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::pull_request_reviewers::Relation::PullRequest
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
