//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recent_issue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_recent_issue_user_id_posting_id_1")]
    pub user_id: Option<i64>,
    #[sea_orm(unique_key = "uq_recent_issue_user_id_issue_id_1")]
    pub issue_id: Option<i64>,
    #[sea_orm(unique_key = "uq_recent_issue_user_id_posting_id_1")]
    pub posting_id: Option<i64>,
    pub title: Option<String>,
    pub url: Option<String>,
    pub created_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::issue::Entity",
        from = "Column::IssueId",
        to = "super::issue::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Issue,
    #[sea_orm(
        belongs_to = "super::n4user::Entity",
        from = "Column::UserId",
        to = "super::n4user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    N4user,
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issue.def()
    }
}

impl Related<super::n4user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::N4user.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
