//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "review_comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(
        ignore,
        column_type = "custom(\"LONGTEXT\")",
        select_as = "text",
        nullable
    )]
    pub contents: Option<String>,
    pub created_date: Option<DateTime>,
    pub author_id: Option<i64>,
    pub author_login_id: Option<String>,
    pub author_name: Option<String>,
    pub thread_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comment_thread::Entity",
        from = "Column::ThreadId",
        to = "super::comment_thread::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    CommentThread,
}

impl Related<super::comment_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentThread.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
