//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "webhook")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub project_id: Option<i64>,
    pub payload_url: Option<String>,
    pub secret: Option<String>,
    pub created_at: Option<DateTime>,
    pub git_push: Option<i16>,
    pub webhook_type: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Project,
    #[sea_orm(has_many = "super::webhook_delivery::Entity")]
    WebhookDelivery,
    #[sea_orm(has_many = "super::webhook_thread::Entity")]
    WebhookThread,
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::webhook_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookThread.def()
    }
}

impl Related<super::webhook_delivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookDelivery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
