import * as stylex from "@stylexjs/stylex";

export const issueEditColors = stylex.defineVars({
  action: "#49afcd",
  issueNumber: "#51aacc",
  inputBorder: "#cccccc",
  inputText: "#555555",
  editorBorder: "#dddddd",
  optionBorder: "#dddddd",
});

export const styles = stylex.create({
  errorWrap: {
    padding: "100px 0px",
    textAlign: "center",
  },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  issueNumber: { color: issueEditColors.issueNumber },
  labelBackground: (backgroundColor: string) => ({ backgroundColor }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  form: { margin: "0px" },
  title: {
    borderColor: issueEditColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: issueEditColors.inputText,
    fontSize: "20px",
    padding: "4px",
    width: "100%",
  },
  editor: {
    borderColor: issueEditColors.editorBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    minHeight: "300px",
    width: "100%",
  },
  markdownEditorWrapper: { marginTop: "10px" },
  editorPositioned: { position: "relative" },
  editorTabContent: { position: "relative", overflow: "visible" },
  assigneeInput: { width: "100%" },
  assigneePicker: { width: "100%" },
  labelPicker: { display: "inline-block" },
  labelSearchInput: { width: "10px" },
  pasteHelp: { display: "block" },
  uploadHelp: { textAlign: "right" },
  actions: { margin: "10px 0px", textAlign: "right" },
  issueOption: {
    borderTopColor: issueEditColors.optionBorder,
    width: "100%",
  },
  sidebar: { minWidth: "0px" },
  subtask: { display: "block" },
  save: {
    backgroundColor: issueEditColors.action,
    borderColor: issueEditColors.action,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
  },
});
