import * as stylex from "@stylexjs/stylex";

export const organizationPullRequestColors = stylex.defineVars({
  badge: "#51aacc",
  border: "#dddddd",
  inputBorder: "#cccccc",
  inputText: "#555555",
  link: "#3592b5",
  metaText: "#777777",
  stateText: "#555555",
  progressSurface: "#f5f5f5",
  progressFill: "#f0ad4e",
  grayText: "#ccc",
});

export const styles = stylex.create({
  headerLogo: (backgroundImage: string) => ({ backgroundImage }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  searchColumn: { paddingTop: "0px" },
  searchBar: {
    backgroundColor: "#fff",
    borderColor: organizationPullRequestColors.inputBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    height: "20px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: organizationPullRequestColors.inputText,
    height: "20px",
    padding: "0px 5px",
    width: "100%",
  },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  tabs: {
    borderBottomColor: organizationPullRequestColors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    listStyle: "none",
    margin: "0px",
    padding: "0px",
  },
  tabButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    color: organizationPullRequestColors.link,
    padding: "8px 15px",
  },
  activeTabButton: { color: "#555", fontWeight: "700" },
  badge: { color: organizationPullRequestColors.badge, fontWeight: "700", marginLeft: "4px" },
  content: { clear: "both", paddingTop: "15px" },
  list: { listStyle: "none" },
  empty: { padding: "100px 0px", textAlign: "center" },
  emptyIcon: (backgroundImage: string) => ({
    backgroundImage,
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  }),
  emptyMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  row: { borderBottomColor: organizationPullRequestColors.border },
  meta: { color: organizationPullRequestColors.metaText },
  state: { color: organizationPullRequestColors.stateText },
  pagination: { color: organizationPullRequestColors.metaText },
  paginationRoot: {
    clear: "both",
    margin: "20px 0",
    textAlign: "center",
    width: "100%",
  },
  paginationPageNums: {
    display: "inline-block",
    fontSize: 0,
    listStyle: "none",
    margin: 0,
    marginLeft: "-120px !important",
    padding: 0,
    "@media all and (max-width: 720px)": { marginLeft: "-120px !important" },
  },
  paginationPageNum: {
    color: "#8e9094",
    display: "inline-block",
    fontSize: "12px",
    padding: "0 10px",
  },
  paginationIconPageNum: { padding: "0 5px" },
  paginationIconLabel: { color: "#f36c22", fontSize: "11px" },
  paginationIconLabelOff: { color: "#8e9094" },
  paginationDelimiter: { color: "#ddd", padding: "0 5px" },
  paginationInput: {
    border: "1px solid #eee",
    fontWeight: "bold",
    margin: 0,
    textAlign: "center",
    width: "30px",
    ":hover": {
      borderColor: "#f36c22",
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
    },
    ":focus": {
      borderColor: "#f36c22",
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
    },
  },
  paginationNoSpinner: { MozAppearance: "textfield" },
  paginationIcon: (backgroundImage: string) => ({
    backgroundImage,
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    verticalAlign: "middle",
  }),
  paginationPrev: {
    backgroundPosition: "-136px -139px",
    height: "9px",
    marginRight: "10px",
    width: "6px",
  },
  paginationPrevOff: { backgroundPosition: "-164px -2px" },
  paginationNext: {
    backgroundPosition: "-146px -139px",
    height: "9px",
    marginLeft: "10px",
    width: "6px",
  },
  paginationNextOff: { backgroundPosition: "-23px -13px" },
  progress: {
    backgroundColor: organizationPullRequestColors.progressSurface,
    borderRadius: "5px",
    display: "inline-block",
    height: "7px",
    marginTop: "3px",
    overflow: "hidden",
    verticalAlign: "middle",
    width: "30px",
  },
  progressMeta: { marginRight: "20px" },
  progressFill: (width) => ({
    backgroundColor: organizationPullRequestColors.progressFill,
    height: "100%",
    width,
  }),
  grayTextSeparator: { color: organizationPullRequestColors.grayText },
});
