import * as stylex from "@stylexjs/stylex";

export const organizationIssuesTheme = stylex.defineVars({
  border: "#dddddd",
  inputBorder: "#cccccc",
  inputText: "#555555",
  searchSurface: "#ffffff",
  emptySurface: "#f7f7f7",
  rowBorder: "#eeeeee",
  postIdText: "#999999",
  titleText: "#333333",
  metaText: "#777777",
  paginationText: "#777777",
});

export const styles = stylex.create({
  quickSearch: { listStyle: "none" },
  // Legacy group_issue_list_partial renders each server-provided label color inline.
  // Keep the runtime paint dynamic while geometry remains owned by frozen legacy CSS.
  issueLabelBackground: (backgroundColor) => ({ backgroundColor }),
  twoColumnPopover: {
    display: "block",
    left: "-75px",
    top: "-74px",
  },
  search: { backgroundColor: organizationIssuesTheme.searchSurface },
  projectSelect: { width: "100%" },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  searchBar: {
    backgroundColor: organizationIssuesTheme.searchSurface,
    borderColor: organizationIssuesTheme.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: organizationIssuesTheme.inputText,
    height: "20px",
    padding: "0px 5px",
  },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  tabs: {
    borderBottomColor: organizationIssuesTheme.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    listStyle: "none",
    margin: "0px",
    padding: "0px",
  },
  list: { listStyle: "none" },
  empty: { backgroundColor: organizationIssuesTheme.emptySurface },
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: {
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  },
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  row: {
    display: "block",
    clear: "both",
    padding: "10px",
    overflow: "auto",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: organizationIssuesTheme.rowBorder,
  },
  avatar: { float: "left", marginRight: "10px" },
  titleWrap: {
    position: "relative",
    display: "block",
    lineHeight: "20px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  postId: {
    marginRight: "5px",
    color: organizationIssuesTheme.postIdText,
    fontSize: "13px",
    fontWeight: "bold",
  },
  title: {
    color: organizationIssuesTheme.titleText,
    fontSize: "15px",
    fontWeight: "600",
    ":hover": { color: organizationIssuesTheme.titleText, textDecoration: "none" },
  },
  meta: {
    display: "block",
    lineHeight: "20px",
    fontSize: "12px",
    color: organizationIssuesTheme.metaText,
    overflow: "hidden",
  },
  pagination: { color: organizationIssuesTheme.paginationText },
});
