import * as stylex from "@stylexjs/stylex";

export const organizationPullRequestColors = stylex.defineVars({
  badge: "#51aacc",
  border: "#dddddd",
  inputBorder: "#cccccc",
  inputText: "#555555",
  link: "#3592b5",
  emptySurface: "#f7f7f7",
  metaText: "#777777",
  stateText: "#555555",
  progressSurface: "#f5f5f5",
  progressFill: "#f0ad4e",
});

export const styles = stylex.create({
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  searchColumn: { paddingTop: "0px" },
  searchBar: {
    backgroundColor: "#fff",
    borderColor: organizationPullRequestColors.inputBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    height: "20px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: organizationPullRequestColors.inputText,
    height: "20px",
    padding: "0px 5px",
    width: "100%",
  },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  tabs: {
    borderBottomColor: organizationPullRequestColors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    listStyle: "none",
    margin: "0px",
    padding: "0px",
  },
  tabButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    color: organizationPullRequestColors.link,
    padding: "8px 15px",
  },
  activeTabButton: { color: "#555", fontWeight: "700" },
  badge: { color: organizationPullRequestColors.badge, fontWeight: "700", marginLeft: "4px" },
  content: { clear: "both", paddingTop: "15px" },
  list: { listStyle: "none" },
  empty: { backgroundColor: organizationPullRequestColors.emptySurface },
  row: { borderBottomColor: organizationPullRequestColors.border },
  meta: { color: organizationPullRequestColors.metaText },
  state: { color: organizationPullRequestColors.stateText },
  pagination: { color: organizationPullRequestColors.metaText },
  progress: { backgroundColor: organizationPullRequestColors.progressSurface },
  progressMeta: { marginRight: "20px" },
  progressFill: { backgroundColor: organizationPullRequestColors.progressFill },
});
