import * as stylex from "@stylexjs/stylex";

// issue/view.scala.html paint tokens only; legacy geometry remains in frozen CSS.
export const issueDetailColors = stylex.defineVars({
  mutedText: "#777777",
  emptySurface: "#f7f7f7",
  accentText: "#337581",
  headerTitleText: "#000000",
  headerSurface: "#f2f2f2",
  headerIdText: "#939393",
  headerDateText: "#999999",
  badgeOpen: "#b6da54",
  badgeClosed: "#fd6956",
  badgeRejected: "#fd8658",
  badgeMerged: "#65c9df",
  badgeConflict: "#c0392b",
  taskProgressSurface: "#d4d4d4",
  taskProgressRed: "red",
});

export const styles = stylex.create({
  errorWrap: {
    padding: "100px 0px",
    textAlign: "center",
  },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  legacyPopoverPosition: (left: number, top: number) => ({
    display: "block",
    left,
    position: "fixed",
    top,
    transform: "translate(-50%, -100%)",
  }),
  labelControl: { display: "inline-block" },
  labelSearchInput: { width: "10px" },
  keymapWrapper: { marginLeft: 55, padding: "10px 0px" },
  shareLinkHidden: { display: "none" },
  votersModalVisible: { display: "block" },
  keymapModalVisible: { display: "block" },
  commentBodyHidden: { display: "none" },
  replyVisible: { display: "block" },
  childCommentFormVisible: { display: "block", visibility: "visible" },
  notificationVisible: { display: "block" },
  voterSummary: { marginRight: "2px" },
  labelColor: (backgroundColor: string) => ({
    backgroundColor,
  }),
  page: {
    minHeight: "100%",
  },
  header: {
    display: "block",
    clear: "both",
    margin: "15px 0",
    border: "none",
    borderBottomColor: issueDetailColors.mutedText,
  },
  title: {
    padding: "10px 20px",
    color: issueDetailColors.headerTitleText,
    wordBreak: "break-all",
    backgroundColor: issueDetailColors.headerSurface,
    borderRadius: "10px",
    fontSize: "18px",
    lineHeight: "30px",
  },
  boardId: {
    color: issueDetailColors.headerIdText,
    fontSize: "14px",
    paddingRight: "10px",
  },
  date: {
    display: "inline-block",
    marginRight: "20px",
    color: issueDetailColors.headerDateText,
    lineHeight: "29px",
    verticalAlign: "top",
  },
  badge: {
    display: "inline-block",
    padding: "5px 15px",
    marginRight: "25px",
    color: "#ffffff",
    backgroundColor: "#777",
    borderRadius: "15px",
    fontWeight: "bold",
    lineHeight: "20px",
  },
  badgeOpen: { backgroundColor: issueDetailColors.badgeOpen },
  badgeClosed: { backgroundColor: issueDetailColors.badgeClosed },
  badgeRejected: { backgroundColor: issueDetailColors.badgeRejected },
  badgeMerged: { backgroundColor: issueDetailColors.badgeMerged },
  badgeConflict: { backgroundColor: issueDetailColors.badgeConflict },
  mobileMetadata: {
    fontSize: "0.7em",
  },
  body: {
    minWidth: 0,
  },
  childCommentVoteText: {
    fontSize: "12px",
  },
  labelGeometry: {
    display: "inline-block",
    margin: "0 4px 4px 0",
    padding: "2px 6px",
    borderRadius: "3px",
  },
  dangerButton: {
    color: "#b13427",
    borderColor: "#d98c82",
  },
  modal: {
    position: "fixed",
    top: "18%",
    left: "50vw",
    zIndex: 1000,
    width: "min(480px, calc(100vw - 32px))",
    marginLeft: "0",
    color: "#333",
    backgroundColor: "#fff",
    border: "1px solid #999",
    borderRadius: "4px",
    boxShadow: "0 3px 12px rgb(0 0 0 / 24%)",
    transform: "translateX(-50%)",
  },
  keymapModal: {
    top: "10%",
    left: "50vw",
    width: "640px",
    padding: "20px",
    marginLeft: "-320px",
    lineHeight: "30px",
    borderRadius: "6px",
    transform: "none",
  },
  modalSection: { padding: "12px 16px" },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid #ddd",
  },
  modalTitle: { order: 1, margin: "0", fontSize: "18px", fontWeight: 400 },
  modalClose: {
    order: 2,
    padding: "0",
    fontSize: "20px",
    lineHeight: "20px",
    color: "#777",
    backgroundColor: "transparent",
    border: "0",
    boxShadow: "none",
  },
  modalBodyText: { margin: "0" },
  modalFooter: {
    display: "flex",
    gap: "8px",
    justifyContent: "flex-end",
    backgroundColor: "#f7f7f7",
    borderTop: "1px solid #ddd",
  },
  content: {
    minWidth: 0,
    minHeight: "150px",
    padding: "0 20px",
    marginBottom: "20px",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    paddingRight: "15px",
    margin: "20px 0",
    overflow: "auto",
    textAlign: "right",
  },
  mobileNewSubtask: {
    marginLeft: "4px",
  },
  disabledCommentActions: { textAlign: "right" },
  commentFormActions: { textAlign: "right" },
  uploadHelp: { textAlign: "right" },
  commentUpdateActions: { textAlign: "right" },
  sidebar: {
    marginBottom: "20px",
    minWidth: 0,
  },
  emptyContent: {
    backgroundColor: issueDetailColors.emptySurface,
  },
  author: {
    color: issueDetailColors.accentText,
    display: "block",
    margin: "10px 20px",
  },
  // `_page.less` keeps the desktop metadata gutter at 52px and only narrows it
  // at the frozen 720px responsive boundary.
  issueInfo: {
    padding: "15px 0 0 52px",
    "@media all and (max-width: 720px)": {
      padding: "15px 0 0 10px",
    },
  },
  boardFooter: {
    marginTop: "20px",
    fontSize: "0",
    textAlign: "right",
  },
  timelineEvent: {
    padding: "2px 0 2px 55px",
    color: "#666",
    fontSize: "1em",
    lineHeight: "30px",
  },
  timelineEventDate: { color: "#aaa", fontSize: "11px" },
  timelineEventState: {
    display: "inline-block",
    width: "90px",
    marginRight: "10px",
    padding: "6px 0",
    color: "#fff",
    fontWeight: "bold",
    lineHeight: "14px",
    textAlign: "center",
    backgroundColor: "#777",
    borderRadius: "5px",
  },
  timelineStateOpen: { backgroundColor: "#b6da54" },
  timelineStateClosed: { backgroundColor: "#fd6956" },
  timelineStateChanged: { backgroundColor: "#65c9df" },
  timelineStateRejected: { backgroundColor: "#f39c12" },
  timelineStateConflict: { backgroundColor: "#c0392b" },
  timelineStateResolved: { backgroundColor: "#468847" },
  timelineStateAdded: { color: "#0097a7", backgroundColor: "#b2ebf2" },
  timelineStateDeleted: { color: "#f4511e", backgroundColor: "#ffccbc" },
  disabledVote: {
    color: issueDetailColors.mutedText,
  },
  timeline: {
    display: "block",
    clear: "both",
    fontFamily: "inherit",
  },
  commentForm: {
    padding: "0 0 15px 54px",
    fontFamily: "inherit",
  },
  childCommentSurface: {
    marginLeft: "60px",
    textAlign: "right",
  },
  childCommentContents: {
    marginLeft: "12px",
    padding: "5px 0 4px 10px",
    textAlign: "left",
    borderBottom: "1px dashed #ccc",
  },
  childCommentDelete: {
    display: "inline-flex",
    alignItems: "center",
    color: "red",
  },
  childCommentFormRow: {
    display: "flex",
    marginLeft: "12px",
  },
  sidebarMetaDl: { marginBottom: "20px" },
  sidebarMetaDd: { padding: "5px 0px" },
  sidebarMetaAssigneeName: { fontSize: "11px" },
  indexTimeline: {
    display: "block",
    clear: "both",
    fontFamily: "inherit",
  },
  originalMessageToggle: {
    paddingLeft: "5px",
    paddingRight: "5px",
    borderWidth: "0px",
  },
  editorTabContent: {
    position: "relative",
    overflow: "visible",
  },
  taskProgressBar: {
    backgroundColor: issueDetailColors.taskProgressRed,
    height: "2px",
    transitionDuration: "0.2s",
    width: "0px",
  },
  tasklist: {
    boxShadow: "none",
    display: "none",
    filter: "none",
    padding: "10px 20px 0px",
  },
  taskTitle: { fontWeight: "500" },
  taskDoneCounter: { marginLeft: "5px" },
  taskProgress: { backgroundColor: issueDetailColors.taskProgressSurface },
  subtaskProgressBar: (width: string) => ({
    width,
  }),
  subtaskProgressShell: {
    boxShadow: "none",
    display: "inline-block",
    marginTop: "3px",
    overflow: "hidden",
    verticalAlign: "middle",
    width: "30px",
  },
  parentIssueState: {
    borderRadius: "0",
    color: "#fff",
    fontSize: "12px",
    lineHeight: "17px",
    padding: "2px",
    verticalAlign: "text-bottom",
  },
  parentIssueStateOpen: { backgroundColor: "#8bc34a" },
  parentIssueStateClosed: { backgroundColor: "#f68c52" },
  selectedChild: {
    backgroundColor: "#f5f5f5",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontWeight: "bold",
  },
  subtasks: {
    marginTop: "40px",
    marginBottom: "15px",
  },
  subtaskItem: {
    padding: "0 3px",
  },
  parentIssue: {
    fontSize: "16px",
  },
  parentIssueDelimiter: {
    margin: "5px 0 0",
    borderTop: "1px dashed #ddd",
  },
  itemCountGroup: {
    border: "1px solid #eee",
    borderRadius: "3px",
    lineHeight: "14px",
    marginTop: "2px",
  },
  itemCountGroupNoBorder: { border: "none" },
  itemCountLinkComment: {
    color: "#8b008b",
    ":hover": { color: "#be00be" },
  },
  itemCountLinkVote: {
    color: "#f36c22",
    ":hover": { color: "#f58c52" },
  },
  itemCountLinkOffset: { marginLeft: "-5px" },
  countGroup: {
    display: "inline-block",
    margin: "0 auto",
    padding: "0 5px",
    textAlign: "center",
  },
  countGroupIcon: {
    borderLeft: "1px solid #eee",
    fontSize: "9px",
    lineHeight: "12px",
    paddingTop: "2px",
  },
  countGroupIconFirst: { borderLeft: "none" },
  countGroupCount: { padding: "0 5px 0 0" },
});
