import * as stylex from "@stylexjs/stylex";

export const issuesTheme = stylex.defineVars({
  resultsSurface: "#ffffff",
  milestoneTag: "#2196f3",
  postBorder: "#dddddd",
  postActiveSurface: "#f5f5f5",
  titleText: "#333333",
  infosText: "#999999",
  postIdText: "#999999",
  progressSurface: "#f0f0f0",
  progressShadow: "inset 0 1px 1px rgb(0 0 0 / 25%)",
  progressDoneBorder: "#8bc34a",
  progressOpenBorder: "#c93426",
  progressDoneBar: "#8bc34a",
  progressOpenBar: "#c93426",
  childDateText: "lightgrey",
  dueDateClosedText: "#999",
});

export const styles = stylex.create({
  errorWrap: {
    padding: "100px 0px",
    textAlign: "center",
  },
  errorIcon: {
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  },
  errorIconSprite: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  downloadWrap: { padding: "10px" },
  keymapWrap: { marginLeft: "55px", padding: "10px 0" },
  manageLabel: { marginLeft: "2px" },
  childIssueListVisible: { display: "block" },
  progressBar: (width: string) => ({ width }),
  relativeAnchor: { position: "relative" },
  modeControl: { marginRight: "10px" },
  labelsWrap: { position: "relative" },
  searchAdvanced: { marginTop: "10px" },
  results: { backgroundColor: issuesTheme.resultsSurface },
  massUpdateOptionButton: {
    background: "transparent",
    border: 0,
    clear: "both",
    color: "#333",
    display: "block",
    fontWeight: "normal",
    lineHeight: "20px",
    padding: "3px 20px",
    textAlign: "left",
    whiteSpace: "nowrap",
    width: "100%",
  },
  selectedLabelSearchInput: { width: "10px" },
  showSubtasksPopover: {
    bottom: "100%",
    display: "block",
    left: "50%",
    marginBottom: "10px",
    minWidth: "150px",
    pointerEvents: "none",
    position: "absolute",
    transform: "translateX(-50%)",
  },
  twoColumnPopover: {
    bottom: "100%",
    display: "block",
    left: "50%",
    marginBottom: "10px",
    minWidth: "276px",
    pointerEvents: "none",
    position: "absolute",
    transform: "translateX(-50%)",
    zIndex: 1010,
  },
  issueRowHoverBackground: (backgroundColor: string) => ({ backgroundColor }),
  childLabelBackground: (backgroundColor: string) => ({ background: backgroundColor }),
  emptyAvatar: { height: "32px", width: "32px" },
  milestoneTag: {
    borderRadius: "6px",
    color: issuesTheme.milestoneTag,
    fontSize: "11px",
    maxWidth: "135px",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  issuePostItem: {
    display: "block",
    clear: "both",
    padding: "10px",
    overflow: "auto",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: issuesTheme.postBorder,
  },
  issuePostItemActive: { backgroundColor: issuesTheme.postActiveSurface },
  dueDateClosed: { color: issuesTheme.dueDateClosedText },
  dueDateIcon: { marginRight: "3px" },
  massUpdateCheck: {
    float: "left",
    marginRight: "15px",
    textAlign: "center",
    verticalAlign: "middle",
  },
  massUpdateCheckInput: { marginTop: "15px" },
  issueTitle: {
    color: issuesTheme.titleText,
    fontSize: "15px",
    fontWeight: 600,
    "@media all and (max-width: 720px)": { fontSize: "16px" },
  },
  issueInfos: {
    display: "block",
    lineHeight: "20px",
    fontSize: "12px",
    color: issuesTheme.infosText,
    overflow: "hidden",
  },
  issueAvatar: { float: "left", marginRight: "10px" },
  issueAssigneeAvatar: { marginRight: 0 },
  titleWrap: {
    position: "relative",
    display: "block",
    lineHeight: "20px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  postId: {
    marginRight: "5px",
    color: issuesTheme.postIdText,
    fontSize: "13px",
    fontWeight: "bold",
  },
  subtaskProgress: {
    float: "left",
    paddingLeft: "5px",
    marginRight: "6px",
    display: "inline-block",
    width: "30px",
    verticalAlign: "bottom",
    height: "7px",
    marginBottom: "5px",
    overflow: "hidden",
    backgroundColor: issuesTheme.progressSurface,
    boxShadow: issuesTheme.progressShadow,
    filter: "none",
  },
  subtaskProgressDone: {
    borderStyle: "solid",
    borderWidth: "1px",
    borderColor: issuesTheme.progressDoneBorder,
  },
  subtaskProgressOpen: {
    borderStyle: "solid",
    borderWidth: "1px",
    borderColor: issuesTheme.progressOpenBorder,
  },
  subtaskProgressBar: { height: "100%", filter: "none" },
  subtaskProgressDoneBar: { backgroundColor: issuesTheme.progressDoneBar },
  subtaskProgressOpenBar: { backgroundColor: issuesTheme.progressOpenBar },
  subtaskProgressRatio: { fontSize: "0.8em" },
  childDate: { display: "none", color: issuesTheme.childDateText },
  childDateVisible: { display: "inline-block" },
  // Frozen `_common.less` pagination declarations and effective `_page.less` cascade.
  paginationWrap: {
    clear: "both",
    width: "100%",
    margin: "20px 0",
    textAlign: "center",
  },
  paginationPageNums: {
    display: "inline-block",
    padding: 0,
    margin: 0,
    fontSize: 0,
    listStyle: "none",
    marginLeft: "-120px !important",
    "@media all and (max-width: 720px)": {
      marginLeft: "-120px !important",
    },
  },
  paginationPageNum: {
    display: "inline-block",
    padding: "0 10px",
    color: "#8e9094",
    fontSize: "12px",
  },
  paginationIconPageNum: { padding: "0 5px" },
  paginationIconLabel: { fontSize: "11px", color: "#f36c22" },
  paginationIconLabelOff: { color: "#8e9094" },
  paginationDelimiter: { color: "#ddd", padding: "0 5px" },
  paginationInput: {
    margin: 0,
    width: "30px",
    textAlign: "center",
    fontWeight: "bold",
    border: "1px solid #eee",
    ":hover": {
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
      borderColor: "#f36c22",
    },
    ":focus": {
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
      borderColor: "#f36c22",
    },
  },
  paginationNoSpinner: { MozAppearance: "textfield" },
  paginationIcon: (backgroundImage: string) => ({
    display: "inline-block",
    backgroundRepeat: "no-repeat",
    backgroundImage,
    verticalAlign: "middle",
  }),
  paginationPrev: {
    width: "6px",
    height: "9px",
    backgroundPosition: "-136px -139px",
    marginRight: "10px",
  },
  paginationPrevOff: { backgroundPosition: "-164px -2px" },
  paginationNext: {
    width: "6px",
    height: "9px",
    backgroundPosition: "-146px -139px",
    marginLeft: "10px",
  },
  paginationNextOff: { backgroundPosition: "-23px -13px" },
});
