import * as stylex from "@stylexjs/stylex";

export const issuesTheme = stylex.defineVars({
  resultsSurface: "#ffffff",
  milestoneTag: "#2196f3",
});

export const styles = stylex.create({
  downloadWrap: { padding: "10px" },
  keymapWrap: { marginLeft: "55px", padding: "10px 0" },
  manageLabel: { marginLeft: "2px" },
  childIssueListVisible: { display: "block" },
  progressBar: (width: string) => ({ width }),
  relativeAnchor: { position: "relative" },
  labelsWrap: { position: "relative" },
  results: { backgroundColor: issuesTheme.resultsSurface },
  massUpdateOptionButton: {
    background: "transparent",
    border: 0,
    clear: "both",
    color: "#333",
    display: "block",
    fontWeight: "normal",
    lineHeight: "20px",
    padding: "3px 20px",
    textAlign: "left",
    whiteSpace: "nowrap",
    width: "100%",
  },
  selectedLabelSearchInput: { width: "10px" },
  showSubtasksPopover: {
    bottom: "100%",
    display: "block",
    left: "50%",
    marginBottom: "10px",
    minWidth: "150px",
    pointerEvents: "none",
    position: "absolute",
    transform: "translateX(-50%)",
  },
  twoColumnPopover: {
    bottom: "100%",
    display: "block",
    left: "50%",
    marginBottom: "10px",
    minWidth: "276px",
    pointerEvents: "none",
    position: "absolute",
    transform: "translateX(-50%)",
    zIndex: 1010,
  },
  issueRowHoverBackground: (backgroundColor: string) => ({ backgroundColor }),
  childLabelBackground: (backgroundColor: string) => ({ background: backgroundColor }),
  emptyAvatar: { height: "32px", width: "32px" },
  milestoneTag: {
    borderRadius: "6px",
    color: issuesTheme.milestoneTag,
    fontSize: "11px",
    maxWidth: "135px",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
});
