import * as stylex from "@stylexjs/stylex";
import { globalBreakpoints } from "../../../theme.stylex";

// Paint-only owners for the frozen issue/create cascade. Layout, editor
// geometry, and type remain in the route and contextual legacy classes.
export const projectIssueFormTheme = stylex.defineVars({
  errorText: "#db3a67",
  attachmentErrorText: "#b94a48",
  savedText: "#62962a",
  savedBorder: "#8bc34a",
});

export const issueFormStyles = stylex.create({
  issueTitleField: { position: "relative" },
  titleHeadOptions: { top: "calc(100% - 13px)" },
  titleHeadOptionsButtonSmall: { marginLeft: "0" },
  assigneeDropdownSearch: {
    width: "calc(100% - 8px)",
    height: "30px",
    margin: "0 4px 4px",
  },
  issueLabelToken: {
    display: "inline-flex",
    gap: "4px",
    alignItems: "center",
    boxSizing: "border-box",
    height: "24px",
    minHeight: "24px",
    padding: "1px 3px 1px 6px",
    backgroundColor: "#fafafa",
    border: "1px solid #ccc",
    borderRadius: "3px",
  },
  issueLabelTokenClose: {
    minHeight: "20px",
    padding: "0 3px",
  },
  uploadShell: {
    position: "relative",
    boxSizing: "border-box",
    width: "100%",
    minHeight: {
      default: "70px",
      [globalBreakpoints.mobile]: "100px",
    },
    padding: "10px",
  },
  subtaskMessage: {
    position: "relative",
    zIndex: 1,
    boxSizing: "border-box",
    minHeight: "30px",
    fontFamily: "inherit",
    backgroundColor: "#fff",
    borderRadius: "0",
  },
  subtaskParentControlHidden: { display: "none" },
  dueDateSearchBar: { position: "relative" },
  dueDateInput: {
    boxSizing: "border-box",
    width: "100%",
    paddingRight: "34px",
  },
  dueDateCalendarButton: {
    position: "absolute",
    top: "0",
    right: "0",
    boxSizing: "border-box",
    width: "30px",
    minHeight: "30px",
    padding: "0",
    cursor: "pointer",
    backgroundColor: "transparent",
    border: "0",
  },
  dueDateNativePicker: {
    position: "absolute",
    top: "15px",
    right: "15px",
    width: "1px",
    minWidth: "1px",
    height: "1px",
    minHeight: "1px",
    padding: "0",
    clipPath: "inset(50%)",
    overflow: "hidden",
    whiteSpace: "nowrap",
    border: "0",
  },
  cancelButton: { marginLeft: "0px" },
  uploadHelpPastable: { display: "block" },
  uploadFakeFile: {
    display: "block",
    padding: "6px 20px",
    marginBottom: "0px",
  },
  uploadFileInput: {
    boxSizing: "content-box",
    padding: "0px",
    border: "0px",
    opacity: 0,
  },
  uploadAttachSaveHelp: { display: "block" },
  attachedFileInsertCopy: {
    marginLeft: "8px",
    color: "#666",
    fontSize: "11px",
    whiteSpace: "nowrap",
  },
  attachedFilesVisible: { display: "block" },
  attachedFile: {
    boxSizing: "border-box",
    height: "auto",
    minHeight: "32px",
    padding: "0 6px",
    cursor: "default",
  },
  attachedFileMain: {
    display: "inline-flex",
    gap: "4px",
    alignItems: "center",
    maxWidth: "calc(100% - 36px)",
    minHeight: "30px",
    padding: "0 4px",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    appearance: "none",
    backgroundColor: "transparent",
    border: "0",
  },
  attachedFileMainDisabled: {
    cursor: "default",
    opacity: 0.65,
  },
  attachedFileMainIcon: {
    display: "inline-block",
    width: "auto",
    margin: "0 3px 0 0",
  },
  attachedFileName: { minWidth: 0 },
  uploadError: {
    display: "inline-block",
    maxWidth: "240px",
    overflow: "hidden",
    color: projectIssueFormTheme.attachmentErrorText,
    fontSize: "11px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    verticalAlign: "middle",
  },
  attachedFileDelete: {
    display: "inline-block",
    minHeight: "30px",
  },
  taskListButton: { marginTop: "2px" },
  editorNoticeLabel: { padding: "4px 15px" },
  editorNoticeSaved: {
    padding: "2px 4px",
    color: projectIssueFormTheme.savedText,
    border: "1px solid",
    borderColor: projectIssueFormTheme.savedBorder,
    borderRadius: "3px",
  },
  editorTabContent: { position: "relative", overflow: "visible" },
  issueMarkdownEditor: { position: "relative" },
  issueMarkdownEditorTabs: { marginBottom: "0" },
  markdownPreview: { minHeight: "280px" },
  markdownPreviewVideo: { maxWidth: "100%" },
  editorMentionOptions: {
    right: "auto",
    width: "min(420px, calc(100% - 16px))",
  },
  editorMentionMirror: {
    position: "absolute",
    top: "1px",
    right: "1px",
    left: "1px",
    boxSizing: "border-box",
    minHeight: "310px",
    padding: "4px 6px",
    overflowWrap: "break-word",
    fontFamily: 'Consolas, Menlo, Monaco, "Ubuntu Mono", "source-code-pro", monospace',
    fontSize: { default: "1em", [globalBreakpoints.mobile]: "16px" },
    lineHeight: "normal",
    whiteSpace: "pre-wrap",
    pointerEvents: "none",
    visibility: "hidden",
  },
  editorMentionMarker: {
    display: "inline-block",
    width: "1px",
    height: "1em",
  },
  markdownTab: {
    display: "block",
    boxSizing: "border-box",
    minHeight: "29px",
    padding: "4px 15px",
    marginRight: "2px",
    color: "#3592b5",
    font: "inherit",
    fontWeight: "bold",
    lineHeight: "20px",
    cursor: "pointer",
    appearance: "none",
    backgroundColor: "transparent",
    border: "1px solid transparent",
    borderRadius: "4px 4px 0 0",
  },
  markdownTabActive: {
    color: "#555",
    cursor: "default",
    backgroundColor: "#fff",
    borderColor: "#ddd #ddd transparent",
  },
  editorTextarea: {
    overflow: "hidden",
    overflowWrap: "break-word",
    resize: "none",
  },
  editorTextareaHeight: (height: string) => ({ height }),
  assigneePicker: { width: "100%" },
  milestonePicker: { width: "100%" },
  labelPicker: { display: "inline-block" },
  labelBackground: (backgroundColor: string) => ({ backgroundColor }),
  uploadProgress: {
    backgroundColor: "#f0f0f0",
    boxShadow: "inset 0 1px 1px rgb(0 0 0 / 25%)",
    display: "inline-block",
    height: "7px",
    margin: "0",
    overflow: "hidden",
    verticalAlign: "middle",
    width: "100px",
  },
  uploadProgressBar: (width: string) => ({
    backgroundColor: "#f36c22",
    display: "block",
    height: "100%",
    width,
  }),
  mentionMirrorTransform: (transform: string) => ({ transform }),
  mentionPopupPosition: (left: number, top: number) => ({ left, top }),
});
