import * as stylex from "@stylexjs/stylex";

export const milestoneColors = stylex.defineVars({
  active: "#f36c22",
  border: "#dddddd",
  closed: "#51aacc",
  description: "#666666",
  due: "#666666",
  issue: "#666666",
  open: "#5dbbe0",
  progress: "#fd6956",
  searchBorder: "#cccccc",
  searchText: "#555555",
  tabText: "#3592b5",
});

export const styles = stylex.create({
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  tabWrap: { clear: "both", minHeight: "40px" },
  tabs: {
    borderBottomColor: milestoneColors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    listStyle: "none",
    margin: "10px 0px 20px",
    padding: "0px",
  },
  tab: { float: "left", marginBottom: "-1px" },
  tabLink: {
    color: milestoneColors.tabText,
    display: "block",
    fontWeight: "700",
    lineHeight: "20px",
    padding: "8px 30px",
    textDecoration: "none",
  },
  activeTabLink: {
    backgroundColor: "#fff",
    borderColor: milestoneColors.border,
    borderStyle: "solid",
    borderWidth: "1px",
    borderBottomColor: "transparent",
    color: "#555",
    cursor: "default",
  },
  newWrap: { float: "right" },
  newButton: {
    backgroundColor: "#51a351",
    borderColor: "#51a351",
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
    textDecoration: "none",
  },
  filterWrap: { display: "block", height: "30px", margin: "5px 0px 0px", position: "relative" },
  filters: {
    borderColor: milestoneColors.border,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#666",
    float: "right",
    marginTop: "5px",
    padding: "2px 10px",
  },
  filterLink: { color: "#666", marginRight: "10px", textDecoration: "none" },
  filterActive: { color: milestoneColors.active, fontWeight: "700" },
  search: {
    backgroundColor: "#fff",
    borderColor: milestoneColors.searchBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    float: "left",
    height: "20px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    backgroundColor: "#fff",
    borderStyle: "none",
    borderWidth: "0px",
    color: milestoneColors.searchText,
    height: "20px",
    margin: "0px -5px",
    padding: "0px 5px",
    width: "350px",
  },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  icon: {
    display: "inline-block",
    fontFamily: "yobicon",
    lineHeight: 1,
    "::before": { content: '"\\e225"' },
  },
  list: { listStyle: "none", margin: "0px", padding: "0px" },
  row: {
    borderBottomColor: milestoneColors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    padding: "15px 0px",
  },
  rowLast: { borderBottomWidth: "0px" },
  infos: { width: "100%" },
  meta: { margin: "5px 0px 10px" },
  name: { color: "#333", fontSize: "20px", fontWeight: "700", textDecoration: "none" },
  separator: { color: "#e4e4e4", margin: "0px 5px" },
  issue: { color: milestoneColors.issue },
  due: { color: milestoneColors.due },
  dueOver: { color: milestoneColors.active },
  completion: { float: "right", textAlign: "center" },
  completionNumber: { fontSize: "20px", fontWeight: "700" },
  progressWrap: {
    color: "#999",
    fontSize: "11px",
    marginTop: "15px",
    overflow: "hidden",
    width: "100%",
  },
  progress: {
    backgroundColor: "#f5f5f5",
    borderRadius: "4px",
    display: "block",
    height: "8px",
    overflow: "hidden",
    width: "100%",
  },
  progressBar: (width) => ({
    backgroundColor: milestoneColors.progress,
    height: "100%",
    width,
  }),
  issueLink: { color: "#333", display: "block", textDecoration: "none" },
  issueItem: { color: "#333", fontSize: "14px", padding: "3px 0px" },
  itemName: { verticalAlign: "middle" },
  issueNumber: {
    color: "gray",
    display: "inline-block",
    fontFamily: "menlo, Consolas, monospace, sans-serif",
    fontSize: "12px",
    marginRight: "3px",
    minWidth: "35px",
    paddingRight: "5px",
    textAlign: "right",
  },
  issueStateOpen: {
    backgroundColor: milestoneColors.open,
    borderRadius: "2px",
    display: "inline-block",
    height: "12px",
    marginRight: "5px",
    verticalAlign: "middle",
    width: "12px",
  },
  issueStateClosed: {
    backgroundColor: milestoneColors.closed,
    borderRadius: "2px",
    display: "inline-block",
    height: "12px",
    marginRight: "5px",
    verticalAlign: "middle",
    width: "12px",
  },
  label: {
    borderRadius: "2px",
    color: "#fff",
    display: "inline-block",
    fontSize: "11px",
    marginLeft: "4px",
    padding: "1px 5px",
  },
  labelColor: (backgroundColor: string) => ({ backgroundColor }),
});
