import * as stylex from "@stylexjs/stylex";

export const postFormColors = stylex.defineVars({
  action: "#51a351",
  attachedFilesBorder: "#e0e0e0",
  editorBorder: "#dddddd",
  inputBorder: "#cccccc",
  inputText: "#555555",
  uploadSurface: "#f5f5f5",
  warning: "#f89406",
});

export const styles = stylex.create({
  attachedFiles: {
    borderTopColor: postFormColors.attachedFilesBorder,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "none",
    marginBottom: "0px",
    marginTop: "15px",
    paddingBottom: "15px",
    paddingTop: "15px",
  },
  attachWrap: { textAlign: "center" },
  editorWrapper: { position: "relative" },
  markdownEditorWrapper: { marginTop: "10px" },
  editorTabContent: { overflow: "visible", position: "relative" },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  form: { margin: "0px" },
  title: {
    borderColor: postFormColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: postFormColors.inputText,
    fontSize: "20px",
    padding: "4px",
    width: "100%",
  },
  editor: {
    borderColor: postFormColors.editorBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    minHeight: "300px",
    width: "100%",
  },
  options: {
    marginBottom: "10px",
    marginTop: "10px",
    textAlign: "right",
  },
  uploadButtonWrap: {
    display: "inline-block",
    marginLeft: "5px",
    marginRight: "5px",
    verticalAlign: "top",
  },
  uploadPlain: { display: "inline-block", lineHeight: "30px" },
  uploadWrap: {
    backgroundColor: postFormColors.uploadSurface,
    borderRadius: "5px",
  },
  actions: { margin: "10px 0px", textAlign: "right" },
  pasteHelpVisible: { display: "block" },
  uploadAttachSaveHelp: { display: "block", textAlign: "right" },
  save: {
    backgroundColor: postFormColors.action,
    borderColor: postFormColors.action,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
  },
  cancel: {
    borderColor: "#ccc",
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#333",
    marginLeft: "4px",
    padding: "4px 12px",
  },
});
