import * as stylex from "@stylexjs/stylex";

// Frozen paint values from _page.less:6375-6519.
export const projectSearchTheme = stylex.defineVars({
  avatarBorder: "#ececec",
  border: "#dddddd",
  emptyCategoryText: "#d3d2d3",
  keywordSurface: "#6bc4e9",
  linkText: "#3592b5",
  metaText: "#999999",
  resultAccent: "#f36c22",
  resultSurface: "#ffffff",
  titleText: "#333333",
});

export const styles = stylex.create({
  results: {
    backgroundColor: projectSearchTheme.resultSurface,
    width: "100%",
  },
  pageGridRow: {
    display: "block",
    width: "100%",
  },
  pageGridCategory: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: 0,
    minHeight: "30px",
    width: "14.893617021276595%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: 0,
      width: "100%",
    },
  },
  pageGridResults: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: "2.127659574468085%",
    minHeight: "30px",
    width: "82.97872340425532%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: 0,
      width: "100%",
    },
  },
  searchCategory: {
    borderTopColor: projectSearchTheme.border,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  searchCategoryItem: {
    borderBottomColor: "#e5e5e5",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    fontWeight: "bold",
  },
  searchCategoryItemActive: {
    backgroundColor: "#f8f8f8",
    color: projectSearchTheme.resultAccent,
    fontWeight: 600,
  },
  searchCategoryAction: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    border: 0,
    borderRadius: 0,
    boxShadow: "none",
    boxSizing: "border-box",
    color: projectSearchTheme.titleText,
    display: "flex",
    font: "inherit",
    gap: "8px",
    justifyContent: "space-between",
    padding: "9px 8px",
    textAlign: "left",
    textDecoration: "none",
    width: "100%",
  },
  searchCategoryActionActive: { color: projectSearchTheme.resultAccent },
  searchCategoryEmpty: { color: projectSearchTheme.emptyCategoryText },
  searchCategoryBadge: { marginLeft: "auto", padding: "0 2px" },
  searchBox: {
    borderBottomColor: projectSearchTheme.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBottom: "15px",
  },
  searchInput: { marginBottom: 0 },
  searchResultTitle: {
    fontSize: "16px",
    fontWeight: "normal",
    marginTop: "15px",
    padding: "0 15px",
  },
  searchResultTitleStrong: { color: projectSearchTheme.resultAccent },
  searchList: { display: "block", listStyle: "none" },
  searchListItem: {
    borderBottomColor: projectSearchTheme.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "block",
    float: "none",
    margin: "0",
    padding: "15px",
    position: "relative",
  },
  searchListProjectItem: { padding: "15px 15px 15px 60px" },
  avatar: {
    borderColor: projectSearchTheme.avatarBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    float: "left",
    height: "40px",
    marginLeft: "-55px",
    width: "40px",
  },
  avatarImage: {
    borderStyle: "none",
    height: "100%",
    verticalAlign: "top",
    width: "100%",
  },
  titleWrap: {
    fontSize: "16px",
    fontWeight: "bold",
    lineHeight: "30px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  postId: { color: projectSearchTheme.metaText, fontWeight: "normal" },
  title: { color: projectSearchTheme.titleText },
  userLink: { color: projectSearchTheme.linkText, fontWeight: "bold" },
  content: { display: "block", fontSize: "14px", paddingLeft: "20px" },
  contentBody: { display: "block" },
  meta: {
    color: projectSearchTheme.metaText,
    fontSize: "13px",
    marginTop: "10px",
    paddingLeft: "20px",
  },
  metaItem: { lineHeight: "20px", marginRight: "10px" },
  keyword: { backgroundColor: projectSearchTheme.keywordSurface, padding: "2px" },
  emptyResult: (backgroundImage: string) => ({
    backgroundImage,
    color: projectSearchTheme.metaText,
    backgroundPosition: "center 50%",
    backgroundRepeat: "no-repeat",
    marginBottom: "20px",
    marginTop: "20px",
    minHeight: "250px",
    paddingLeft: "20px",
    paddingRight: "20px",
    textAlign: "center",
  }),
});
