import * as stylex from "@stylexjs/stylex";

// Frozen paint values from _page.less:6375-6519.
export const projectSearchTheme = stylex.defineVars({
  avatarBorder: "#ececec",
  border: "#dddddd",
  emptyCategoryText: "#d3d2d3",
  keywordSurface: "#6bc4e9",
  linkText: "#3592b5",
  metaText: "#999999",
  resultAccent: "#f36c22",
  resultSurface: "#ffffff",
  titleText: "#333333",
});

export const styles = stylex.create({
  results: { backgroundColor: projectSearchTheme.resultSurface },
  searchCategory: { fontWeight: "bold" },
  searchCategoryEmpty: { color: projectSearchTheme.emptyCategoryText },
  searchBox: {
    borderBottomColor: projectSearchTheme.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBottom: "15px",
  },
  searchInput: { marginBottom: 0 },
  searchResultTitle: {
    fontSize: "16px",
    fontWeight: "normal",
    marginTop: "15px",
    padding: "0 15px",
  },
  searchResultTitleStrong: { color: projectSearchTheme.resultAccent },
  searchList: { display: "block", listStyle: "none" },
  searchListItem: {
    borderBottomColor: projectSearchTheme.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "block",
    float: "none",
    margin: "0",
    padding: "15px",
    position: "relative",
  },
  searchListProjectItem: { padding: "15px 15px 15px 60px" },
  avatar: {
    borderColor: projectSearchTheme.avatarBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    float: "left",
    height: "40px",
    marginLeft: "-55px",
    width: "40px",
  },
  avatarImage: {
    borderStyle: "none",
    height: "100%",
    verticalAlign: "top",
    width: "100%",
  },
  titleWrap: {
    fontSize: "16px",
    fontWeight: "bold",
    lineHeight: "30px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  postId: { color: projectSearchTheme.metaText, fontWeight: "normal" },
  title: { color: projectSearchTheme.titleText },
  userLink: { color: projectSearchTheme.linkText, fontWeight: "bold" },
  content: { display: "block", fontSize: "14px", paddingLeft: "20px" },
  contentBody: { display: "block" },
  meta: {
    color: projectSearchTheme.metaText,
    fontSize: "13px",
    marginTop: "10px",
    paddingLeft: "20px",
  },
  metaItem: { lineHeight: "20px", marginRight: "10px" },
  keyword: { backgroundColor: projectSearchTheme.keywordSurface, padding: "2px" },
  emptyResult: {
    color: projectSearchTheme.metaText,
    minHeight: "32px",
    padding: "10px 0",
  },
});
