import * as stylex from "@stylexjs/stylex";

export const projectHomeTheme = stylex.defineVars({ pageSurface: "#ffffff" });
export const styles = stylex.create({
  page: { backgroundColor: projectHomeTheme.pageSurface },
  header: { marginBottom: "20px", padding: "5px 0", position: "relative" },
  overview: { borderLeft: "3px solid #fc491e", padding: "0 10px" },
  overviewHeading: { fontSize: "14px", fontWeight: "normal", lineHeight: "30px" },
  markdownParagraph: { display: "inline-block", margin: "0" },
  descriptionEditInput: { margin: "0" },
  memberHeader: { backgroundColor: "#f8f8f8", padding: "10px 0" },
  memberHeaderHeading: {
    color: "#4c4c4c",
    display: "inline-block",
    fontSize: "12px",
    lineHeight: "20px",
    margin: "0",
  },
  cloneWrap: { borderRadius: "6px", padding: "5px 0", position: "relative" },
  cloneUrl: {
    backgroundColor: "#ffffff",
    border: "1px solid #dddddd",
    borderRadius: "3px 0 0 3px",
    borderRight: "none",
    cursor: "pointer",
    float: "left",
    marginBottom: "0",
    maxWidth: "125px",
    outline: "0",
    position: "absolute",
    right: "86px",
    textAlign: "right",
    transition: "width 0.15s",
    width: "100px",
  },
  cloneButton: {
    borderRadius: "0 3px 3px 0",
    float: "left",
    marginLeft: "0",
    padding: "4px 0",
    position: "absolute",
    right: "0",
    width: "86px",
  },
  projectButtonWrap: { padding: "5px 0", textAlign: "center" },
  projectButtonItem: { display: "block", marginTop: "10px" },
  projectButtonItemFirst: { marginTop: "0" },
  projectButtonLink: { display: "block" },
  memberInner: {
    backgroundColor: "#ffffff",
    borderRadius: "10px",
    boxShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
    fontSize: "12px",
    marginBottom: "10px",
    overflow: "hidden",
    verticalAlign: "top",
  },
  memberInnerInfo: { height: "auto", marginRight: "0" },
  members: { listStyle: "none", margin: "0", padding: "10px" },
  member: {
    borderBottom: "1px solid #ededed",
    color: "#999",
    display: "block",
    padding: "5px 10px",
  },
  memberFirst: { paddingTop: "0" },
  memberLast: { borderBottom: "none", paddingBottom: "0" },
  memberName: { lineHeight: "24px", marginLeft: "5px" },
  memberNameText: {
    display: "inline-block",
    maxWidth: "180px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sectionHeading: { borderLeft: "3px solid #ff7332", marginBottom: "20px", paddingLeft: "10px" },
  empty: { textAlign: "center" },
  emptyMessage: { color: "#999", fontSize: "13px", marginBottom: "15px" },
  overviewLabel: { borderBottom: "1px solid #eee", padding: "5px 0" },
  overviewLabelDt: { lineHeight: "30px", width: "120px" },
  overviewLabelDd: { lineHeight: "30px", marginLeft: "140px" },
  overviewLabelFirst: { paddingTop: "0" },
  overviewLabelLast: { borderBottom: "none" },
  assigneeLink: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  overviewNumber: { paddingRight: "15px", textAlign: "right" },
  milestoneProgressWrap: {
    color: "#999",
    fontSize: "11px",
    overflow: "hidden",
  },
  milestoneProgress: { height: "7px", width: "100%" },
  milestoneProgressBar: (width: string) => ({ height: "100%", width }),
  progressBar: (width: string) => ({ width }),
});
