import * as stylex from "@stylexjs/stylex";

export const projectHomeTheme = stylex.defineVars({ pageSurface: "#ffffff" });
export const styles = stylex.create({
  projectVisibilityBadge: { color: "#788ba7", fontSize: "14px", marginLeft: "5px" },
  projectOrigin: { fontSize: "12px", lineHeight: "20px", marginTop: "-7px" },
  projectOriginTitle: { color: "#788ba7" },
  projectOriginName: { color: "#5dbbe0", marginLeft: "5px" },
  projectUtilWrap: { bottom: "20px", position: "absolute", right: "0" },
  projectUtil: { listStyle: "none", margin: "0" },
  projectUtilItem: { float: "left", marginLeft: "15px", position: "relative" },
  projectUtilIcons: { margin: "10px 0px 10px 25px" },
  watcherCount: { border: "0px", opacity: 0.9, textShadow: "none" },
  watcherOn: { backgroundColor: "#b6da54", backgroundImage: "none" },
  watchButtonGroup: {
    "@media all and (max-width: 720px)": { display: "none" },
  },
  watchButton: { padding: "4px 10px" },
  menuCount: {
    backgroundColor: "#ff7332",
    borderRadius: "9px",
    color: "#ecf0f1",
    display: "inline-block",
    fontSize: "10px",
    fontWeight: "400",
    lineHeight: "18px",
    minWidth: "8px",
    padding: "0px 6px",
    textAlign: "center",
    verticalAlign: "top",
  },
  projectMenuGroup: { float: "left", marginLeft: "110px" },
  projectSetting: { float: "right" },
  projectMenuOuter: {
    backgroundColor: "#ececec",
    borderBottom: "1px solid #dddddd",
    height: "39px",
  },
  projectMenuInner: { height: "39px", margin: "0 auto" },
  page: { backgroundColor: projectHomeTheme.pageSurface },
  projectHome: { padding: "10px" },
  header: { marginBottom: "20px", padding: "5px 0", position: "relative" },
  overview: { borderLeft: "3px solid #fc491e", padding: "0 10px" },
  overviewHeading: { fontSize: "14px", fontWeight: "normal", lineHeight: "30px" },
  markdownParagraph: { display: "inline-block", margin: "0" },
  descriptionEditInput: { margin: "0" },
  memberHeader: { backgroundColor: "#f8f8f8", padding: "10px 0" },
  memberHeaderHeading: {
    color: "#4c4c4c",
    display: "inline-block",
    fontSize: "12px",
    lineHeight: "20px",
    margin: "0",
  },
  dashboardProgress: { height: "7px", marginTop: "7px", width: "100px" },
  cloneWrap: { borderRadius: "6px", padding: "5px 0", position: "relative" },
  cloneUrl: {
    backgroundColor: "#ffffff",
    border: "1px solid #dddddd",
    borderRadius: "3px 0 0 3px",
    borderRight: "none",
    cursor: "pointer",
    float: "left",
    marginBottom: "0",
    maxWidth: "125px",
    outline: "0",
    position: "absolute",
    right: "86px",
    textAlign: "right",
    transition: "width 0.15s",
    width: "100px",
  },
  cloneButton: {
    borderRadius: "0 3px 3px 0",
    float: "left",
    marginLeft: "0",
    padding: "4px 0",
    position: "absolute",
    right: "0",
    width: "86px",
  },
  projectButtonWrap: { padding: "5px 0", textAlign: "center" },
  projectButtonItem: { display: "block", marginTop: "10px" },
  projectButtonItemFirst: { marginTop: "0" },
  projectButtonLink: { display: "block" },
  memberInner: {
    backgroundColor: "#ffffff",
    borderRadius: "10px",
    boxShadow: "0 1px 0 rgba(0, 0, 0, 0.05)",
    fontSize: "12px",
    marginBottom: "10px",
    overflow: "hidden",
    verticalAlign: "top",
  },
  memberInnerInfo: { height: "auto", marginRight: "0" },
  members: { listStyle: "none", margin: "0", padding: "10px" },
  member: {
    borderBottom: "1px solid #ededed",
    color: "#999",
    display: "block",
    padding: "5px 10px",
  },
  memberFirst: { paddingTop: "0" },
  memberLast: { borderBottom: "none", paddingBottom: "0" },
  memberName: { lineHeight: "24px", marginLeft: "5px" },
  memberNameText: {
    display: "inline-block",
    maxWidth: "180px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sectionHeading: { borderLeft: "3px solid #ff7332", marginBottom: "20px", paddingLeft: "10px" },
  empty: { textAlign: "center" },
  emptyMessage: { color: "#999", fontSize: "13px", marginBottom: "15px" },
  overviewLabel: { borderBottom: "1px solid #eee", padding: "5px 0" },
  overviewLabelDt: { lineHeight: "30px", width: "120px" },
  overviewLabelDd: { lineHeight: "30px", marginLeft: "140px" },
  overviewLabelFirst: { paddingTop: "0" },
  overviewLabelLast: { borderBottom: "none" },
  assigneeLink: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  overviewNumber: { paddingRight: "15px", textAlign: "right" },
  milestoneProgressWrap: {
    color: "#999",
    fontSize: "11px",
    overflow: "hidden",
  },
  milestoneProgress: { height: "7px", width: "100%" },
  milestoneProgressBar: (width: string) => ({ height: "100%", width }),
  progressBar: (width: string) => ({ width }),
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
});
