import * as stylex from "@stylexjs/stylex";

export const pullRequestColors = stylex.defineVars({
  badge: "#51aacc",
  border: "#ddd",
  inputBorder: "#ccc",
  inputText: "#555",
  link: "#3592b5",
  grayText: "#ccc",
});
export const styles = stylex.create({
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  newPullRequestAction: { float: "right" },
  receiverRail: { float: "right" },
  stateBadge: { float: "right" },
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (backgroundImage: string) => ({
    backgroundImage,
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  searchColumn: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: 0,
    minHeight: "30px",
    paddingTop: "0px",
    width: "14.893617021276595%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: 0,
      width: "100%",
    },
    "@media (max-width: 720px)": { display: "none" },
  },
  searchColumnHidden: { display: "none" },
  searchBar: {
    borderColor: pullRequestColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: pullRequestColors.inputText,
    height: "20px",
    padding: "0px 5px",
    width: "100%",
  },
  contributorsSelect: { width: "100%" },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  tabs: {
    borderBottomColor: pullRequestColors.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    listStyle: "none",
    margin: "0px",
    padding: "0px",
  },
  recentlyPushedBranch: { fontWeight: "700", marginLeft: "5px" },
  reviewProgressItem: { marginRight: "10px" },
  reviewProgressBar: (width) => ({ width }),
  reviewerCount: { marginTop: "-1px" },
  badge: { color: pullRequestColors.badge, fontWeight: "700", marginLeft: "4px" },
  contentColumn: {
    boxSizing: "border-box",
    display: "block",
    float: "left",
    marginLeft: "2.127659574468085%",
    minHeight: "30px",
    width: "82.97872340425532%",
    "@media (max-width: 767px)": {
      float: "none",
      marginLeft: 0,
      width: "100%",
    },
  },
  content: { clear: "both", paddingTop: "15px" },
  twoColumnAnchor: { marginRight: "10px", position: "relative" },
  twoColumnPopover: { display: "block", left: "-75px", top: "-74px" },
  rowPointer: { cursor: "pointer" },
  grayTextSeparator: { color: pullRequestColors.grayText },
});
