import * as stylex from "@stylexjs/stylex";

export const projectSettingColors = stylex.defineVars({
  action: "#51a351",
  inputBorder: "#cccccc",
  inputText: "#555555",
  logoSurface: "#eeeeee",
  noteText: "#999999",
});

export const styles = stylex.create({
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  form: { margin: "0px" },
  frame: { overflow: "visible" },
  topBox: { paddingTop: "20px" },
  logo: {
    backgroundColor: projectSettingColors.logoSurface,
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    height: "140px",
    width: "140px",
  },
  input: {
    borderColor: projectSettingColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: projectSettingColors.inputText,
    padding: "4px",
  },
  nameField: { position: "relative" },
  namePopover: {
    display: "block",
    left: "-296px",
    top: "-12px",
    width: "276px",
  },
  textarea: {
    borderColor: projectSettingColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: projectSettingColors.inputText,
    padding: "4px",
  },
  oldPlace: { color: "red" },
  defaultBranchContainer: { width: "220px" },
  defaultBranchDrop: { minWidth: "220px", width: "220px" },
  defaultBranchSelect: { minWidth: "220px" },
  reviewerCountPanelVisible: { display: "block" },
  reviewerCountPanelHidden: { display: "none" },
  reviewerCountControlsVisible: { display: "block" },
  reviewerCountControlsHidden: { display: "none" },
  defaultBranchPanelVisible: { display: "block" },
  defaultBranchPanelHidden: { display: "none" },
  changeVcsMenuVisible: { display: "list-item" },
  changeVcsMenuHidden: { display: "none" },
  save: {
    backgroundColor: projectSettingColors.action,
    borderColor: projectSettingColors.action,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
  },
});
