import * as stylex from "@stylexjs/stylex";
import { globalBreakpoints } from "../../../theme.stylex";

export const projectSettingColors = stylex.defineVars({
  action: "#51a351",
  inputBorder: "#cccccc",
  inputText: "#555555",
  logoSurface: "#eeeeee",
  pointText: "#51aacc",
});

export const styles = stylex.create({
  logoBackground: (backgroundImage: string) => ({ backgroundImage }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  form: { margin: "0px" },
  frame: { overflow: "visible" },
  topBox: { paddingTop: "20px" },
  settingBox: { float: "left", width: "399px" },
  settingBoxLeft: { borderRight: "1px solid #ffffff", paddingRight: "20px" },
  settingBoxRight: {
    borderLeft: {
      default: "1px solid #d4d4d4",
      [globalBreakpoints.mobile]: "none",
    },
    margin: "0px",
    paddingLeft: { default: "20px", [globalBreakpoints.mobile]: "0px" },
  },
  logo: {
    backgroundColor: projectSettingColors.logoSurface,
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    borderRadius: "10px",
    display: "inline-block",
    height: { default: "188px", [globalBreakpoints.mobile]: "100px" },
    width: { default: "260px", [globalBreakpoints.mobile]: "100px" },
  },
  logoDesc: {
    display: "inline-block",
    fontSize: "12px",
    marginLeft: "10px",
    verticalAlign: "top",
    width: "120px",
  },
  point: {
    clear: "both",
    color: projectSettingColors.pointText,
    display: "block",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  descsItem: { marginTop: "10px" },
  descsLast: { marginTop: "25px" },
  input: {
    borderColor: projectSettingColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: projectSettingColors.inputText,
    padding: "4px",
    width: "380px",
  },
  nameField: { position: "relative" },
  namePopover: {
    display: "block",
    left: "-296px",
    top: "-12px",
    width: "276px",
  },
  textarea: {
    borderColor: projectSettingColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: projectSettingColors.inputText,
    padding: "4px",
    marginBottom: "0px",
    resize: "vertical",
    width: { default: "380px", [globalBreakpoints.mobile]: "inherit" },
  },
  textareaHeight: (height: string) => ({ height }),
  oldPlace: { color: "red" },
  defaultBranchContainer: { width: "220px" },
  defaultBranchDrop: { minWidth: "220px", width: "220px" },
  defaultBranchDropVisible: { display: "block" },
  defaultBranchChoice: {
    boxSizing: "border-box",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit",
    height: "auto",
    textAlign: "left",
    width: "100%",
  },
  defaultBranchResult: {
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit",
    textAlign: "left",
    width: "100%",
  },
  defaultBranchSelect: { minWidth: "220px" },
  reviewerCountPanelVisible: { display: "block" },
  reviewerCountPanelHidden: { display: "none" },
  reviewerCountControlsVisible: { display: "block" },
  reviewerCountControlsHidden: { display: "none" },
  defaultBranchPanelVisible: { display: "block" },
  defaultBranchPanelHidden: { display: "none" },
  changeVcsMenuVisible: { display: "list-item" },
  changeVcsMenuHidden: { display: "none" },
  save: {
    backgroundColor: projectSettingColors.action,
    borderColor: projectSettingColors.action,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
  },
});
