import * as stylex from "@stylexjs/stylex";
import { globalBreakpoints } from "../../../theme.stylex";

export const projectSettingColors = stylex.defineVars({
  action: "#51a351",
  inputBorder: "#cccccc",
  inputText: "#555555",
  logoSurface: "#eeeeee",
  pointText: "#51aacc",
});

export const styles = stylex.create({
  logoBackground: (backgroundImage: string) => ({ backgroundImage }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  form: { margin: "0px" },
  frame: { overflow: "visible" },
  topBox: { paddingTop: "20px" },
  settingBox: { float: "left", width: "399px" },
  settingBoxLeft: { borderRight: "1px solid #ffffff", paddingRight: "20px" },
  settingBoxRight: {
    borderLeft: {
      default: "1px solid #d4d4d4",
      [globalBreakpoints.mobile]: "none",
    },
    margin: "0px",
    paddingLeft: { default: "20px", [globalBreakpoints.mobile]: "0px" },
  },
  logo: {
    backgroundColor: projectSettingColors.logoSurface,
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    borderRadius: "10px",
    display: "inline-block",
    height: { default: "188px", [globalBreakpoints.mobile]: "100px" },
    width: { default: "260px", [globalBreakpoints.mobile]: "100px" },
  },
  logoDesc: {
    display: "inline-block",
    fontSize: "12px",
    marginLeft: "10px",
    verticalAlign: "top",
    width: "120px",
  },
  point: {
    clear: "both",
    color: projectSettingColors.pointText,
    display: "block",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  descsItem: { marginTop: "10px" },
  descsLast: { marginTop: "25px" },
  input: {
    borderColor: projectSettingColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: projectSettingColors.inputText,
    padding: "4px",
    width: "380px",
  },
  nameField: { position: "relative" },
  namePopover: {
    display: "block",
    left: "-296px",
    top: "-12px",
    width: "276px",
  },
  textarea: {
    borderColor: projectSettingColors.inputBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    color: projectSettingColors.inputText,
    padding: "4px",
    marginBottom: "0px",
    resize: "vertical",
    width: { default: "380px", [globalBreakpoints.mobile]: "inherit" },
  },
  textareaHeight: (height: string) => ({ height }),
  oldPlace: { color: "red" },
  menuCheckboxInput: {
    margin: "2px",
    verticalAlign: "top",
  },
  radioInput: {
    margin: "2px",
    verticalAlign: "top",
  },
  menuCheckboxLabel: {
    marginLeft: "15px",
    verticalAlign: "middle",
  },
  menuCheckboxLabelFirst: { marginLeft: "0px" },
  defaultBranchContainer: {
    backgroundColor: "#fff",
    borderColor: "rgba(0,0,0,0.15)",
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    boxShadow: "0 1px 0 rgba(0,0,0,0.05)",
    display: "inline-block",
    margin: "0px",
    position: "relative",
    textAlign: "left",
    transition: "all 0.3s ease",
    verticalAlign: "middle",
    width: "220px",
  },
  defaultBranchDrop: {
    backgroundColor: "#fff",
    borderColor: "rgba(0, 0, 0, 0.15)",
    borderRadius: "0 0 3px 3px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    boxShadow: "2px 2px 0 rgba(0, 0, 0, 0.05)",
    color: "#000",
    marginTop: "-1px",
    position: "absolute",
    top: "100%",
    width: "auto",
    zIndex: "9999",
  },
  defaultBranchDropHidden: { display: "none" },
  defaultBranchDropVisible: { display: "block" },
  defaultBranchChoice: {
    backgroundColor: "transparent",
    backgroundImage: "none",
    boxSizing: "border-box",
    borderRadius: "3px",
    borderStyle: "none",
    borderWidth: "0px",
    color: "#444",
    display: "block",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit",
    height: "26px",
    lineHeight: "26px",
    overflow: "hidden",
    padding: "1px 0px 1px 12px",
    position: "relative",
    textAlign: "left",
    textDecoration: "none",
    userSelect: "none",
    whiteSpace: "nowrap",
    width: "100%",
  },
  defaultBranchChosen: {
    display: "block",
    marginRight: "26px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  defaultBranchLabel: { marginTop: "-2px" },
  defaultBranchArrow: {
    backgroundColor: "transparent",
    backgroundImage: "none",
    borderLeftStyle: "none",
    borderRadius: "0 3px 3px 0",
    display: "inline-block",
    height: "100%",
    padding: "4px 9px",
    position: "absolute",
    right: "0px",
    top: "0px",
    width: "auto",
  },
  defaultBranchArrowGlyph: {
    borderLeftColor: "transparent",
    borderLeftStyle: "solid",
    borderLeftWidth: "4px",
    borderRightColor: "transparent",
    borderRightStyle: "solid",
    borderRightWidth: "4px",
    borderTopColor: "#4f4f4f",
    borderTopStyle: "solid",
    borderTopWidth: "4px",
    display: "inline-block",
    height: "0px",
    marginLeft: "0px",
    marginTop: "8px",
    verticalAlign: "top",
    width: "0px",
  },
  defaultBranchSearch: {
    boxSizing: "border-box",
    display: "inline-block",
    margin: "4px 0px 0px",
    minHeight: "26px",
    paddingLeft: "4px",
    paddingRight: "4px",
    position: "relative",
    whiteSpace: "nowrap",
    width: "100%",
    zIndex: "10000",
  },
  defaultBranchSearchInput: {
    boxSizing: "border-box",
    borderColor: "#aaa",
    borderRadius: "0px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "none",
    height: "auto",
    margin: "0px",
    minHeight: "26px",
    outline: "0px",
    padding: "4px 20px 4px 5px",
    width: "100%",
  },
  defaultBranchResults: {
    margin: "4px 0px 0px",
    maxHeight: "350px",
    overflowY: "auto",
    overflowX: "hidden",
    padding: "4px",
    width: "auto",
  },
  defaultBranchResultItem: {
    backgroundImage: "none",
    display: "list-item",
    listStyle: "none",
    marginBottom: "1px",
  },
  defaultBranchResult: {
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit",
    cursor: "pointer",
    margin: "0px",
    minHeight: "1em",
    padding: "3px 7px 4px 8px",
    textAlign: "left",
    userSelect: "none",
    whiteSpace: "nowrap",
  },
  defaultBranchSelect: { minWidth: "220px" },
  reviewerCountPanelVisible: { display: "block" },
  reviewerCountPanelHidden: { display: "none" },
  reviewerCountControlsVisible: { display: "block" },
  reviewerCountControlsHidden: { display: "none" },
  defaultBranchPanelVisible: { display: "block" },
  defaultBranchPanelHidden: { display: "none" },
  changeVcsMenuVisible: { display: "list-item" },
  changeVcsMenuHidden: { display: "none" },
  save: {
    backgroundColor: projectSettingColors.action,
    borderColor: projectSettingColors.action,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "#fff",
    padding: "4px 12px",
  },
});
