[package]
name = "yona-rust-pilot-server"
edition.workspace = true
license.workspace = true
version.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["multipart"] }
base64.workspace = true
bcrypt.workspace = true
buffa.workspace = true
buffa-types.workspace = true
bytes.workspace = true
connectrpc.workspace = true
futures.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
include_dir.workspace = true
md-5.workspace = true
mime_guess.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sea-orm.workspace = true
toml = "0.8"
yona-rust-domain = { path = "../domain" }
yona-rust-integrations = { path = "../integrations" }
yona-rust-persistence = { path = "../persistence" }
yona-rust-pilot-migration = { path = "../migration" }

[build-dependencies]
connectrpc-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
tempfile.workspace = true
testcontainers-modules = { version = "0.15", features = ["postgres", "mariadb"] }
