import * as stylex from "@stylexjs/stylex";

export const milestoneDetailColors = stylex.defineVars({
  action: "#51a351",
  badge: "#51aacc",
  badgeOpen: "#b6da54",
  badgeClosed: "#fd6956",
  bodyText: "#333333",
  descriptionBorder: "#dddddd",
  descriptionSurface: "#f7f7f7",
  descriptionShadow: "inset 0 0 5px #ffffff",
  progress: "#fd6956",
  searchBorder: "#cccccc",
  dueDateClosedText: "#999",
});

export const styles = stylex.create({
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  badge: {
    display: "inline-block",
    padding: "5px 15px",
    marginRight: "25px",
    color: "#ffffff",
    backgroundColor: "#777",
    borderRadius: "15px",
    fontWeight: "bold",
    lineHeight: "20px",
  },
  stateBadge: { marginLeft: "5px" },
  badgeOpen: { backgroundColor: milestoneDetailColors.badgeOpen },
  badgeClosed: { backgroundColor: milestoneDetailColors.badgeClosed },
  titleMeta: { marginLeft: "10px" },
  labelColor: (backgroundColor: string) => ({ backgroundColor }),
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  wrap: { color: milestoneDetailColors.bodyText },
  progress: { backgroundColor: "#f5f5f5", borderRadius: "4px", height: "8px", overflow: "hidden" },
  progressBar: (width: string) => ({
    backgroundColor: milestoneDetailColors.progress,
    height: "100%",
    width,
  }),
  description: {
    backgroundColor: milestoneDetailColors.descriptionSurface,
    borderBottomColor: milestoneDetailColors.descriptionBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderTopColor: milestoneDetailColors.descriptionBorder,
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    boxShadow: milestoneDetailColors.descriptionShadow,
    margin: "15px 0px",
    padding: "10px 15px",
  },
  actions: {
    clear: "both",
    display: "block",
    margin: "10px 0px",
    padding: "15px 0px",
    textAlign: "right",
  },
  listAction: { float: "left" },
  tabs: {
    borderBottom: "1px solid #ddd",
    listStyle: "none",
    marginBottom: "20px",
    marginLeft: "0px",
    padding: "0px",
    "::before": { content: '""', display: "table", lineHeight: "0px" },
    "::after": { clear: "both", content: '""', display: "table", lineHeight: "0px" },
  },
  tabItem: { float: "left", marginBottom: "-1px" },
  tabLink: {
    border: "1px solid transparent",
    borderRadius: "4px 4px 0 0",
    color: "#3592b5",
    display: "block",
    fontWeight: "700",
    lineHeight: "20px",
    marginRight: "2px",
    padding: "8px 30px",
  },
  tabLinkActive: {
    backgroundColor: "#ffffff",
    border: "1px solid #ddd",
    borderBottomColor: "transparent",
    color: "#555555",
    cursor: "default",
  },
  tabLinkMobile: {
    "@media all and (max-width: 720px)": {
      paddingLeft: "5px !important",
      paddingRight: "5px !important",
    },
  },
  tabBadge: { color: milestoneDetailColors.badge, fontWeight: "700", marginLeft: "4px" },
  issueList: { clear: "both", listStyle: "none", margin: "0px", padding: "0px" },
  issueRow: {
    borderBottomColor: milestoneDetailColors.descriptionBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    clear: "both",
    display: "block",
    overflow: "auto",
    padding: "10px 0px",
  },
  issueMeta: { lineHeight: "20px" },
  issueAssigneeRail: { float: "right" },
  issueDueDateRail: { float: "right" },
  dueDateIcon: { marginRight: "3px" },
  dueDateClosed: { color: milestoneDetailColors.dueDateClosedText },
  massUpdate: { position: "relative", transitionDuration: "0.5s", transitionProperty: "padding" },
  massUpdateForm: { float: "left" },
  massUpdateButton: {
    display: "block",
    width: "100%",
    padding: "3px 20px",
    clear: "both",
    fontWeight: "normal",
    lineHeight: "20px",
    color: "#333",
    textAlign: "left",
    whiteSpace: "nowrap",
    backgroundColor: "transparent",
    border: "0",
    ":hover": {
      color: "#fff",
      textDecoration: "none",
      backgroundColor: "#0081c2",
      backgroundImage: "linear-gradient(to bottom, #08c, #0077b3)",
      outline: "0",
    },
    ":focus": {
      color: "#fff",
      textDecoration: "none",
      backgroundColor: "#0081c2",
      backgroundImage: "linear-gradient(to bottom, #08c, #0077b3)",
      outline: "0",
    },
  },
  search: {
    float: "right",
    backgroundColor: "#fff",
    borderColor: milestoneDetailColors.searchBorder,
    borderStyle: "solid",
    borderWidth: "1px",
    padding: "4px 25px 4px 5px",
  },
  deleteModalVisible: { display: "block" },
  deleteModalHidden: { display: "none" },
  issueRowHidden: { display: "none" },
});
