import * as stylex from "@stylexjs/stylex";

// user/partial_issues.scala.html issue title paint only. Geometry stays in the frozen legacy cascade.
export const userIssuesColors = stylex.defineVars({
  controlBorder: "#03afff",
  controlHoverBackground: "#03afff",
  controlHoverText: "#fff0ff",
  controlSelectedBackground: "#aee5ff",
  controlSelectedText: "#0293d6",
  controlText: "#03a9f4",
  inputBorder: "#cccccc",
  inputText: "#555555",
  tabBorder: "#dddddd",
  issueTitle: "#333333",
});

export const styles = stylex.create({
  errorWrap: {
    padding: "100px 0px",
    textAlign: "center",
  },
  errorIcon: (spriteUrl: string) => ({
    backgroundImage: `url(${spriteUrl})`,
    backgroundPosition: "-5px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "82px",
    verticalAlign: "middle",
    width: "62px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  relativeAnchor: { position: "relative" },
  controlsListItem: { marginLeft: "-18px" },
  modeControl: {
    display: "inline-block",
    lineHeight: "37px",
    marginLeft: "10px",
    marginRight: "10px",
  },
  modeControlLabel: { paddingLeft: "0px", paddingTop: "4px" },
  modeControlInput: {
    borderStyle: "none",
    borderWidth: "0px",
    float: "none",
    margin: "4px 4px 0px 2px",
    minHeight: "0px",
    padding: "0px",
    verticalAlign: "top",
  },
  modeControlBorder: {
    borderColor: userIssuesColors.controlBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: userIssuesColors.controlText,
    padding: "3px 3px 0px 3px",
  },
  modeControlBorderHover: {
    backgroundColor: userIssuesColors.controlHoverBackground,
    color: userIssuesColors.controlHoverText,
  },
  modeControlBorderSelected: {
    backgroundColor: userIssuesColors.controlSelectedBackground,
  },
  modeControlText: {
    lineHeight: "20px",
    padding: "0px 4px 0px 0px",
    verticalAlign: "text-bottom",
  },
  modeControlTextHover: { color: userIssuesColors.controlHoverText },
  modeControlTextSelected: { color: userIssuesColors.controlSelectedText },
  twoColumnPopover: {
    bottom: "100%",
    display: "block",
    left: "50%",
    marginBottom: "10px",
    minWidth: "180px",
    pointerEvents: "none",
    position: "absolute",
    transform: "translateX(-50%)",
  },
  showSubtasksPopover: {
    bottom: "100%",
    display: "block",
    left: "50%",
    marginBottom: "10px",
    minWidth: "150px",
    pointerEvents: "none",
    position: "absolute",
    transform: "translateX(-50%)",
  },
  defaultLoginPagePopover: {
    display: "block",
    left: "50%",
    marginTop: "10px",
    minWidth: "190px",
    pointerEvents: "none",
    position: "absolute",
    top: "100%",
    transform: "translateX(-50%)",
  },
  childIssueListVisible: { display: "block" },
  defaultLoginPageHidden: { display: "none" },
  issueRowTwoColumn: { cursor: "pointer" },
  issueRowHovered: { backgroundColor: "#fafafa" },
  // API-derived percentages cannot be enumerated at build time.
  progressBar: (width) => ({ width }),
  issueLabelBackground: (backgroundColor) => ({ backgroundColor }),
  issueTitle: {
    color: userIssuesColors.issueTitle,
    fontSize: "15px",
    fontWeight: 600,
  },
  filters: { float: "right" },
  dueDate: { float: "right" },
  assigneeRail: { float: "right" },
  page: { margin: "0px auto", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  searchWrapper: { margin: "20px 0px" },
  searchBar: {
    backgroundColor: "#ffffff",
    borderColor: userIssuesColors.inputBorder,
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    height: "20px",
    lineHeight: "20px",
    padding: "4px 25px 4px 5px",
    position: "relative",
  },
  searchInput: {
    borderStyle: "none",
    borderWidth: "0px",
    color: userIssuesColors.inputText,
    height: "20px",
    margin: "0px -5px",
    padding: "0px 5px",
    width: "100%",
  },
  searchButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: "0px",
    position: "absolute",
    right: "5px",
    top: "5px",
  },
  tabs: {
    borderBottomColor: userIssuesColors.tabBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  pagination: {
    clear: "both",
    margin: "20px 0",
    textAlign: "center",
    width: "100%",
  },
  paginationPageNums: {
    display: "inline-block",
    fontSize: 0,
    listStyle: "none",
    margin: 0,
    marginLeft: "-120px !important",
    padding: 0,
    "@media all and (max-width: 720px)": { marginLeft: "-120px !important" },
  },
  paginationPageNum: {
    color: "#8e9094",
    display: "inline-block",
    fontSize: "12px",
    padding: "0 10px",
  },
  paginationIconPageNum: { padding: "0 5px" },
  paginationIconLabel: { color: "#f36c22", fontSize: "11px" },
  paginationIconLabelOff: { color: "#8e9094" },
  paginationDelimiter: { color: "#ddd", padding: "0 5px" },
  paginationInput: {
    border: "1px solid #eee",
    fontWeight: "bold",
    margin: 0,
    textAlign: "center",
    width: "30px",
    ":hover": {
      borderColor: "#f36c22",
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
    },
    ":focus": {
      borderColor: "#f36c22",
      boxShadow: "inset -1px -1px 2px rgba(0,0,0,0.1)",
      color: "#f36c22",
    },
  },
  paginationNoSpinner: { MozAppearance: "textfield" },
  paginationIcon: (backgroundImage: string) => ({
    backgroundImage,
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    verticalAlign: "middle",
  }),
  paginationPrev: {
    backgroundPosition: "-136px -139px",
    height: "9px",
    marginRight: "10px",
    width: "6px",
  },
  paginationPrevOff: { backgroundPosition: "-164px -2px" },
  paginationNext: {
    backgroundPosition: "-146px -139px",
    height: "9px",
    marginLeft: "10px",
    width: "6px",
  },
  paginationNextOff: { backgroundPosition: "-23px -13px" },
});
