import * as stylex from "@stylexjs/stylex";

export const pullRequestChangesColors = stylex.defineVars({
  surface: "#fff",
  diffSurface: "#333",
  meta: "#999",
  accent: "#49afcd",
  commitHash: "#5DBBE0",
});
export const styles = stylex.create({
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: (backgroundImage: string) => ({
    backgroundImage,
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    display: "inline-block",
    height: "80px",
    verticalAlign: "middle",
    width: "50px",
  }),
  errorMessage: {
    color: "#898989",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "30px 0px",
  },
  browse: { width: "100%" },
  author: { color: pullRequestChangesColors.meta, marginTop: "20px" },
  commitHash: { color: pullRequestChangesColors.commitHash },
  diffs: {
    backgroundColor: pullRequestChangesColors.diffSurface,
    color: pullRequestChangesColors.surface,
    overflowX: "auto",
  },
  reviewTabs: { marginBottom: "10px" },
  threadActions: { textAlign: "right" },
  commentActions: { textAlign: "right" },
  reviewActions: { textAlign: "right" },
  uploadHelp: { textAlign: "right" },
  editorTabContent: { position: "relative", overflow: "visible" },
  originalMessageToggle: { border: 0, paddingLeft: 5, paddingRight: 5 },
  diffMeta: { cursor: "pointer" },
  threadReviewForm: { display: "block" },
  reviewTextarea: { height: "100px" },
  diffCodeHidden: { display: "none" },
  visibleForm: { display: "block" },
  commentDeleteModalVisible: { display: "block" },
  pendingBlockVisible: { display: "block" },
  pendingBlockPosition: (top: number, left: number) => ({ top, left }),
});
