/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteRouteImport } from './routes/search/route'
import { Route as ResetPasswordRouteRouteImport } from './routes/resetPassword/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as ProjectformRouteRouteImport } from './routes/projectform/route'
import { Route as OrgsRouteRouteImport } from './routes/orgs/route'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as LostPasswordRouteRouteImport } from './routes/lostPassword/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersSignupformRouteRouteImport } from './routes/users/signupform/route'
import { Route as UsersLoginformRouteRouteImport } from './routes/users/loginform/route'
import { Route as UserEditformRouteRouteImport } from './routes/user/editform/route'
import { Route as SitesPageNameRouteRouteImport } from './routes/sites/$pageName/route'
import { Route as ProjectsNewRouteRouteImport } from './routes/projects/new/route'
import { Route as OrganizationsNewRouteRouteImport } from './routes/organizations/new/route'
import { Route as OrganizationsOrganizationNameRouteRouteImport } from './routes/organizations/$organizationName/route'
import { Route as legacyAuthResetPasswordRouteRouteImport } from './routes/(legacy-auth)/reset-password/route'
import { Route as OwnerProjectNameRouteRouteImport } from './routes/$owner/$projectName/route'
import { Route as UserEditformIndexRouteImport } from './routes/user/editform/index'
import { Route as OrganizationsOrganizationNameIndexRouteImport } from './routes/organizations/$organizationName/index'
import { Route as OwnerProjectNameIndexRouteImport } from './routes/$owner/$projectName/index'
import { Route as UserEditformTokenRouteRouteImport } from './routes/user/editform/token/route'
import { Route as UserEditformPasswordRouteRouteImport } from './routes/user/editform/password/route'
import { Route as UserEditformNotificationsRouteRouteImport } from './routes/user/editform/notifications/route'
import { Route as UserEditformEmailsRouteRouteImport } from './routes/user/editform/emails/route'
import { Route as OrganizationsOrganizationNameSettingformRouteRouteImport } from './routes/organizations/$organizationName/settingform/route'
import { Route as OrganizationsOrganizationNamePullrequestsRouteRouteImport } from './routes/organizations/$organizationName/pullrequests/route'
import { Route as OrganizationsOrganizationNameIssuesRouteRouteImport } from './routes/organizations/$organizationName/issues/route'
import { Route as OrganizationsOrganizationNameClosedPullrequestsRouteRouteImport } from './routes/organizations/$organizationName/closedPullrequests/route'
import { Route as OrganizationsOrganizationNameBoardsRouteRouteImport } from './routes/organizations/$organizationName/boards/route'
import { Route as MeSettingsTokenRouteRouteImport } from './routes/me/settings/token/route'
import { Route as MeSettingsProfileRouteRouteImport } from './routes/me/settings/profile/route'
import { Route as MeSettingsPasswordRouteRouteImport } from './routes/me/settings/password/route'
import { Route as MeSettingsNotificationsRouteRouteImport } from './routes/me/settings/notifications/route'
import { Route as MeSettingsEmailsRouteRouteImport } from './routes/me/settings/emails/route'
import { Route as OwnerProjectNameSettingformRouteRouteImport } from './routes/$owner/$projectName/settingform/route'
import { Route as OwnerProjectNameSentPullRequestsRouteRouteImport } from './routes/$owner/$projectName/sentPullRequests/route'
import { Route as OwnerProjectNamePullRequestsRouteRouteImport } from './routes/$owner/$projectName/pullRequests/route'
import { Route as OwnerProjectNamePostsRouteRouteImport } from './routes/$owner/$projectName/posts/route'
import { Route as OwnerProjectNameIssuesRouteRouteImport } from './routes/$owner/$projectName/issues/route'
import { Route as OwnerProjectNameCodeRouteRouteImport } from './routes/$owner/$projectName/code/route'
import { Route as OwnerProjectNameClosedPullRequestsRouteRouteImport } from './routes/$owner/$projectName/closedPullRequests/route'
import { Route as OwnerProjectNamePullRequestPullRequestNumberRouteRouteImport } from './routes/$owner/$projectName/pullRequest/$pullRequestNumber/route'
import { Route as OwnerProjectNamePostPostNumberRouteRouteImport } from './routes/$owner/$projectName/post/$postNumber/route'
import { Route as OwnerProjectNameIssueIssueNumberRouteRouteImport } from './routes/$owner/$projectName/issue/$issueNumber/route'

const SearchRouteRoute = SearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRouteRoute = ResetPasswordRouteRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectformRouteRoute = ProjectformRouteRouteImport.update({
  id: '/projectform',
  path: '/projectform',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsRouteRoute = OrgsRouteRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LostPasswordRouteRoute = LostPasswordRouteRouteImport.update({
  id: '/lostPassword',
  path: '/lostPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersSignupformRouteRoute = UsersSignupformRouteRouteImport.update({
  id: '/users/signupform',
  path: '/users/signupform',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLoginformRouteRoute = UsersLoginformRouteRouteImport.update({
  id: '/users/loginform',
  path: '/users/loginform',
  getParentRoute: () => rootRouteImport,
} as any)
const UserEditformRouteRoute = UserEditformRouteRouteImport.update({
  id: '/user/editform',
  path: '/user/editform',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesPageNameRouteRoute = SitesPageNameRouteRouteImport.update({
  id: '/sites/$pageName',
  path: '/sites/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRouteRoute = ProjectsNewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const OrganizationsNewRouteRoute = OrganizationsNewRouteRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationNameRouteRoute =
  OrganizationsOrganizationNameRouteRouteImport.update({
    id: '/organizations/$organizationName',
    path: '/organizations/$organizationName',
    getParentRoute: () => rootRouteImport,
  } as any)
const legacyAuthResetPasswordRouteRoute =
  legacyAuthResetPasswordRouteRouteImport.update({
    id: '/(legacy-auth)/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerProjectNameRouteRoute = OwnerProjectNameRouteRouteImport.update({
  id: '/$owner/$projectName',
  path: '/$owner/$projectName',
  getParentRoute: () => rootRouteImport,
} as any)
const UserEditformIndexRoute = UserEditformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserEditformRouteRoute,
} as any)
const OrganizationsOrganizationNameIndexRoute =
  OrganizationsOrganizationNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationNameRouteRoute,
  } as any)
const OwnerProjectNameIndexRoute = OwnerProjectNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerProjectNameRouteRoute,
} as any)
const UserEditformTokenRouteRoute = UserEditformTokenRouteRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => UserEditformRouteRoute,
} as any)
const UserEditformPasswordRouteRoute =
  UserEditformPasswordRouteRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => UserEditformRouteRoute,
  } as any)
const UserEditformNotificationsRouteRoute =
  UserEditformNotificationsRouteRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => UserEditformRouteRoute,
  } as any)
const UserEditformEmailsRouteRoute = UserEditformEmailsRouteRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => UserEditformRouteRoute,
} as any)
const OrganizationsOrganizationNameSettingformRouteRoute =
  OrganizationsOrganizationNameSettingformRouteRouteImport.update({
    id: '/settingform',
    path: '/settingform',
    getParentRoute: () => OrganizationsOrganizationNameRouteRoute,
  } as any)
const OrganizationsOrganizationNamePullrequestsRouteRoute =
  OrganizationsOrganizationNamePullrequestsRouteRouteImport.update({
    id: '/pullrequests',
    path: '/pullrequests',
    getParentRoute: () => OrganizationsOrganizationNameRouteRoute,
  } as any)
const OrganizationsOrganizationNameIssuesRouteRoute =
  OrganizationsOrganizationNameIssuesRouteRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => OrganizationsOrganizationNameRouteRoute,
  } as any)
const OrganizationsOrganizationNameClosedPullrequestsRouteRoute =
  OrganizationsOrganizationNameClosedPullrequestsRouteRouteImport.update({
    id: '/closedPullrequests',
    path: '/closedPullrequests',
    getParentRoute: () => OrganizationsOrganizationNameRouteRoute,
  } as any)
const OrganizationsOrganizationNameBoardsRouteRoute =
  OrganizationsOrganizationNameBoardsRouteRouteImport.update({
    id: '/boards',
    path: '/boards',
    getParentRoute: () => OrganizationsOrganizationNameRouteRoute,
  } as any)
const MeSettingsTokenRouteRoute = MeSettingsTokenRouteRouteImport.update({
  id: '/settings/token',
  path: '/settings/token',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeSettingsProfileRouteRoute = MeSettingsProfileRouteRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeSettingsPasswordRouteRoute = MeSettingsPasswordRouteRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeSettingsNotificationsRouteRoute =
  MeSettingsNotificationsRouteRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => MeRouteRoute,
  } as any)
const MeSettingsEmailsRouteRoute = MeSettingsEmailsRouteRouteImport.update({
  id: '/settings/emails',
  path: '/settings/emails',
  getParentRoute: () => MeRouteRoute,
} as any)
const OwnerProjectNameSettingformRouteRoute =
  OwnerProjectNameSettingformRouteRouteImport.update({
    id: '/settingform',
    path: '/settingform',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNameSentPullRequestsRouteRoute =
  OwnerProjectNameSentPullRequestsRouteRouteImport.update({
    id: '/sentPullRequests',
    path: '/sentPullRequests',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNamePullRequestsRouteRoute =
  OwnerProjectNamePullRequestsRouteRouteImport.update({
    id: '/pullRequests',
    path: '/pullRequests',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNamePostsRouteRoute =
  OwnerProjectNamePostsRouteRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNameIssuesRouteRoute =
  OwnerProjectNameIssuesRouteRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNameCodeRouteRoute =
  OwnerProjectNameCodeRouteRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNameClosedPullRequestsRouteRoute =
  OwnerProjectNameClosedPullRequestsRouteRouteImport.update({
    id: '/closedPullRequests',
    path: '/closedPullRequests',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNamePullRequestPullRequestNumberRouteRoute =
  OwnerProjectNamePullRequestPullRequestNumberRouteRouteImport.update({
    id: '/pullRequest/$pullRequestNumber',
    path: '/pullRequest/$pullRequestNumber',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNamePostPostNumberRouteRoute =
  OwnerProjectNamePostPostNumberRouteRouteImport.update({
    id: '/post/$postNumber',
    path: '/post/$postNumber',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)
const OwnerProjectNameIssueIssueNumberRouteRoute =
  OwnerProjectNameIssueIssueNumberRouteRouteImport.update({
    id: '/issue/$issueNumber',
    path: '/issue/$issueNumber',
    getParentRoute: () => OwnerProjectNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/login': typeof LoginRouteRoute
  '/lostPassword': typeof LostPasswordRouteRoute
  '/me': typeof MeRouteRouteWithChildren
  '/orgs': typeof OrgsRouteRoute
  '/projectform': typeof ProjectformRouteRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/register': typeof RegisterRouteRoute
  '/resetPassword': typeof ResetPasswordRouteRoute
  '/search': typeof SearchRouteRoute
  '/$owner/$projectName': typeof OwnerProjectNameRouteRouteWithChildren
  '/reset-password': typeof legacyAuthResetPasswordRouteRoute
  '/organizations/$organizationName': typeof OrganizationsOrganizationNameRouteRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRouteRoute
  '/projects/new': typeof ProjectsNewRouteRoute
  '/sites/$pageName': typeof SitesPageNameRouteRoute
  '/user/editform': typeof UserEditformRouteRouteWithChildren
  '/users/loginform': typeof UsersLoginformRouteRoute
  '/users/signupform': typeof UsersSignupformRouteRoute
  '/$owner/$projectName/closedPullRequests': typeof OwnerProjectNameClosedPullRequestsRouteRoute
  '/$owner/$projectName/code': typeof OwnerProjectNameCodeRouteRoute
  '/$owner/$projectName/issues': typeof OwnerProjectNameIssuesRouteRoute
  '/$owner/$projectName/posts': typeof OwnerProjectNamePostsRouteRoute
  '/$owner/$projectName/pullRequests': typeof OwnerProjectNamePullRequestsRouteRoute
  '/$owner/$projectName/sentPullRequests': typeof OwnerProjectNameSentPullRequestsRouteRoute
  '/$owner/$projectName/settingform': typeof OwnerProjectNameSettingformRouteRoute
  '/me/settings/emails': typeof MeSettingsEmailsRouteRoute
  '/me/settings/notifications': typeof MeSettingsNotificationsRouteRoute
  '/me/settings/password': typeof MeSettingsPasswordRouteRoute
  '/me/settings/profile': typeof MeSettingsProfileRouteRoute
  '/me/settings/token': typeof MeSettingsTokenRouteRoute
  '/organizations/$organizationName/boards': typeof OrganizationsOrganizationNameBoardsRouteRoute
  '/organizations/$organizationName/closedPullrequests': typeof OrganizationsOrganizationNameClosedPullrequestsRouteRoute
  '/organizations/$organizationName/issues': typeof OrganizationsOrganizationNameIssuesRouteRoute
  '/organizations/$organizationName/pullrequests': typeof OrganizationsOrganizationNamePullrequestsRouteRoute
  '/organizations/$organizationName/settingform': typeof OrganizationsOrganizationNameSettingformRouteRoute
  '/user/editform/emails': typeof UserEditformEmailsRouteRoute
  '/user/editform/notifications': typeof UserEditformNotificationsRouteRoute
  '/user/editform/password': typeof UserEditformPasswordRouteRoute
  '/user/editform/token': typeof UserEditformTokenRouteRoute
  '/$owner/$projectName/': typeof OwnerProjectNameIndexRoute
  '/organizations/$organizationName/': typeof OrganizationsOrganizationNameIndexRoute
  '/user/editform/': typeof UserEditformIndexRoute
  '/$owner/$projectName/issue/$issueNumber': typeof OwnerProjectNameIssueIssueNumberRouteRoute
  '/$owner/$projectName/post/$postNumber': typeof OwnerProjectNamePostPostNumberRouteRoute
  '/$owner/$projectName/pullRequest/$pullRequestNumber': typeof OwnerProjectNamePullRequestPullRequestNumberRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/login': typeof LoginRouteRoute
  '/lostPassword': typeof LostPasswordRouteRoute
  '/me': typeof MeRouteRouteWithChildren
  '/orgs': typeof OrgsRouteRoute
  '/projectform': typeof ProjectformRouteRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/register': typeof RegisterRouteRoute
  '/resetPassword': typeof ResetPasswordRouteRoute
  '/search': typeof SearchRouteRoute
  '/reset-password': typeof legacyAuthResetPasswordRouteRoute
  '/organizations/new': typeof OrganizationsNewRouteRoute
  '/projects/new': typeof ProjectsNewRouteRoute
  '/sites/$pageName': typeof SitesPageNameRouteRoute
  '/users/loginform': typeof UsersLoginformRouteRoute
  '/users/signupform': typeof UsersSignupformRouteRoute
  '/$owner/$projectName/closedPullRequests': typeof OwnerProjectNameClosedPullRequestsRouteRoute
  '/$owner/$projectName/code': typeof OwnerProjectNameCodeRouteRoute
  '/$owner/$projectName/issues': typeof OwnerProjectNameIssuesRouteRoute
  '/$owner/$projectName/posts': typeof OwnerProjectNamePostsRouteRoute
  '/$owner/$projectName/pullRequests': typeof OwnerProjectNamePullRequestsRouteRoute
  '/$owner/$projectName/sentPullRequests': typeof OwnerProjectNameSentPullRequestsRouteRoute
  '/$owner/$projectName/settingform': typeof OwnerProjectNameSettingformRouteRoute
  '/me/settings/emails': typeof MeSettingsEmailsRouteRoute
  '/me/settings/notifications': typeof MeSettingsNotificationsRouteRoute
  '/me/settings/password': typeof MeSettingsPasswordRouteRoute
  '/me/settings/profile': typeof MeSettingsProfileRouteRoute
  '/me/settings/token': typeof MeSettingsTokenRouteRoute
  '/organizations/$organizationName/boards': typeof OrganizationsOrganizationNameBoardsRouteRoute
  '/organizations/$organizationName/closedPullrequests': typeof OrganizationsOrganizationNameClosedPullrequestsRouteRoute
  '/organizations/$organizationName/issues': typeof OrganizationsOrganizationNameIssuesRouteRoute
  '/organizations/$organizationName/pullrequests': typeof OrganizationsOrganizationNamePullrequestsRouteRoute
  '/organizations/$organizationName/settingform': typeof OrganizationsOrganizationNameSettingformRouteRoute
  '/user/editform/emails': typeof UserEditformEmailsRouteRoute
  '/user/editform/notifications': typeof UserEditformNotificationsRouteRoute
  '/user/editform/password': typeof UserEditformPasswordRouteRoute
  '/user/editform/token': typeof UserEditformTokenRouteRoute
  '/$owner/$projectName': typeof OwnerProjectNameIndexRoute
  '/organizations/$organizationName': typeof OrganizationsOrganizationNameIndexRoute
  '/user/editform': typeof UserEditformIndexRoute
  '/$owner/$projectName/issue/$issueNumber': typeof OwnerProjectNameIssueIssueNumberRouteRoute
  '/$owner/$projectName/post/$postNumber': typeof OwnerProjectNamePostPostNumberRouteRoute
  '/$owner/$projectName/pullRequest/$pullRequestNumber': typeof OwnerProjectNamePullRequestPullRequestNumberRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/login': typeof LoginRouteRoute
  '/lostPassword': typeof LostPasswordRouteRoute
  '/me': typeof MeRouteRouteWithChildren
  '/orgs': typeof OrgsRouteRoute
  '/projectform': typeof ProjectformRouteRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/register': typeof RegisterRouteRoute
  '/resetPassword': typeof ResetPasswordRouteRoute
  '/search': typeof SearchRouteRoute
  '/$owner/$projectName': typeof OwnerProjectNameRouteRouteWithChildren
  '/(legacy-auth)/reset-password': typeof legacyAuthResetPasswordRouteRoute
  '/organizations/$organizationName': typeof OrganizationsOrganizationNameRouteRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRouteRoute
  '/projects/new': typeof ProjectsNewRouteRoute
  '/sites/$pageName': typeof SitesPageNameRouteRoute
  '/user/editform': typeof UserEditformRouteRouteWithChildren
  '/users/loginform': typeof UsersLoginformRouteRoute
  '/users/signupform': typeof UsersSignupformRouteRoute
  '/$owner/$projectName/closedPullRequests': typeof OwnerProjectNameClosedPullRequestsRouteRoute
  '/$owner/$projectName/code': typeof OwnerProjectNameCodeRouteRoute
  '/$owner/$projectName/issues': typeof OwnerProjectNameIssuesRouteRoute
  '/$owner/$projectName/posts': typeof OwnerProjectNamePostsRouteRoute
  '/$owner/$projectName/pullRequests': typeof OwnerProjectNamePullRequestsRouteRoute
  '/$owner/$projectName/sentPullRequests': typeof OwnerProjectNameSentPullRequestsRouteRoute
  '/$owner/$projectName/settingform': typeof OwnerProjectNameSettingformRouteRoute
  '/me/settings/emails': typeof MeSettingsEmailsRouteRoute
  '/me/settings/notifications': typeof MeSettingsNotificationsRouteRoute
  '/me/settings/password': typeof MeSettingsPasswordRouteRoute
  '/me/settings/profile': typeof MeSettingsProfileRouteRoute
  '/me/settings/token': typeof MeSettingsTokenRouteRoute
  '/organizations/$organizationName/boards': typeof OrganizationsOrganizationNameBoardsRouteRoute
  '/organizations/$organizationName/closedPullrequests': typeof OrganizationsOrganizationNameClosedPullrequestsRouteRoute
  '/organizations/$organizationName/issues': typeof OrganizationsOrganizationNameIssuesRouteRoute
  '/organizations/$organizationName/pullrequests': typeof OrganizationsOrganizationNamePullrequestsRouteRoute
  '/organizations/$organizationName/settingform': typeof OrganizationsOrganizationNameSettingformRouteRoute
  '/user/editform/emails': typeof UserEditformEmailsRouteRoute
  '/user/editform/notifications': typeof UserEditformNotificationsRouteRoute
  '/user/editform/password': typeof UserEditformPasswordRouteRoute
  '/user/editform/token': typeof UserEditformTokenRouteRoute
  '/$owner/$projectName/': typeof OwnerProjectNameIndexRoute
  '/organizations/$organizationName/': typeof OrganizationsOrganizationNameIndexRoute
  '/user/editform/': typeof UserEditformIndexRoute
  '/$owner/$projectName/issue/$issueNumber': typeof OwnerProjectNameIssueIssueNumberRouteRoute
  '/$owner/$projectName/post/$postNumber': typeof OwnerProjectNamePostPostNumberRouteRoute
  '/$owner/$projectName/pullRequest/$pullRequestNumber': typeof OwnerProjectNamePullRequestPullRequestNumberRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/lostPassword'
    | '/me'
    | '/orgs'
    | '/projectform'
    | '/projects'
    | '/register'
    | '/resetPassword'
    | '/search'
    | '/$owner/$projectName'
    | '/reset-password'
    | '/organizations/$organizationName'
    | '/organizations/new'
    | '/projects/new'
    | '/sites/$pageName'
    | '/user/editform'
    | '/users/loginform'
    | '/users/signupform'
    | '/$owner/$projectName/closedPullRequests'
    | '/$owner/$projectName/code'
    | '/$owner/$projectName/issues'
    | '/$owner/$projectName/posts'
    | '/$owner/$projectName/pullRequests'
    | '/$owner/$projectName/sentPullRequests'
    | '/$owner/$projectName/settingform'
    | '/me/settings/emails'
    | '/me/settings/notifications'
    | '/me/settings/password'
    | '/me/settings/profile'
    | '/me/settings/token'
    | '/organizations/$organizationName/boards'
    | '/organizations/$organizationName/closedPullrequests'
    | '/organizations/$organizationName/issues'
    | '/organizations/$organizationName/pullrequests'
    | '/organizations/$organizationName/settingform'
    | '/user/editform/emails'
    | '/user/editform/notifications'
    | '/user/editform/password'
    | '/user/editform/token'
    | '/$owner/$projectName/'
    | '/organizations/$organizationName/'
    | '/user/editform/'
    | '/$owner/$projectName/issue/$issueNumber'
    | '/$owner/$projectName/post/$postNumber'
    | '/$owner/$projectName/pullRequest/$pullRequestNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/lostPassword'
    | '/me'
    | '/orgs'
    | '/projectform'
    | '/projects'
    | '/register'
    | '/resetPassword'
    | '/search'
    | '/reset-password'
    | '/organizations/new'
    | '/projects/new'
    | '/sites/$pageName'
    | '/users/loginform'
    | '/users/signupform'
    | '/$owner/$projectName/closedPullRequests'
    | '/$owner/$projectName/code'
    | '/$owner/$projectName/issues'
    | '/$owner/$projectName/posts'
    | '/$owner/$projectName/pullRequests'
    | '/$owner/$projectName/sentPullRequests'
    | '/$owner/$projectName/settingform'
    | '/me/settings/emails'
    | '/me/settings/notifications'
    | '/me/settings/password'
    | '/me/settings/profile'
    | '/me/settings/token'
    | '/organizations/$organizationName/boards'
    | '/organizations/$organizationName/closedPullrequests'
    | '/organizations/$organizationName/issues'
    | '/organizations/$organizationName/pullrequests'
    | '/organizations/$organizationName/settingform'
    | '/user/editform/emails'
    | '/user/editform/notifications'
    | '/user/editform/password'
    | '/user/editform/token'
    | '/$owner/$projectName'
    | '/organizations/$organizationName'
    | '/user/editform'
    | '/$owner/$projectName/issue/$issueNumber'
    | '/$owner/$projectName/post/$postNumber'
    | '/$owner/$projectName/pullRequest/$pullRequestNumber'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/lostPassword'
    | '/me'
    | '/orgs'
    | '/projectform'
    | '/projects'
    | '/register'
    | '/resetPassword'
    | '/search'
    | '/$owner/$projectName'
    | '/(legacy-auth)/reset-password'
    | '/organizations/$organizationName'
    | '/organizations/new'
    | '/projects/new'
    | '/sites/$pageName'
    | '/user/editform'
    | '/users/loginform'
    | '/users/signupform'
    | '/$owner/$projectName/closedPullRequests'
    | '/$owner/$projectName/code'
    | '/$owner/$projectName/issues'
    | '/$owner/$projectName/posts'
    | '/$owner/$projectName/pullRequests'
    | '/$owner/$projectName/sentPullRequests'
    | '/$owner/$projectName/settingform'
    | '/me/settings/emails'
    | '/me/settings/notifications'
    | '/me/settings/password'
    | '/me/settings/profile'
    | '/me/settings/token'
    | '/organizations/$organizationName/boards'
    | '/organizations/$organizationName/closedPullrequests'
    | '/organizations/$organizationName/issues'
    | '/organizations/$organizationName/pullrequests'
    | '/organizations/$organizationName/settingform'
    | '/user/editform/emails'
    | '/user/editform/notifications'
    | '/user/editform/password'
    | '/user/editform/token'
    | '/$owner/$projectName/'
    | '/organizations/$organizationName/'
    | '/user/editform/'
    | '/$owner/$projectName/issue/$issueNumber'
    | '/$owner/$projectName/post/$postNumber'
    | '/$owner/$projectName/pullRequest/$pullRequestNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  LostPasswordRouteRoute: typeof LostPasswordRouteRoute
  MeRouteRoute: typeof MeRouteRouteWithChildren
  OrgsRouteRoute: typeof OrgsRouteRoute
  ProjectformRouteRoute: typeof ProjectformRouteRoute
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRoute
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRoute
  SearchRouteRoute: typeof SearchRouteRoute
  OwnerProjectNameRouteRoute: typeof OwnerProjectNameRouteRouteWithChildren
  legacyAuthResetPasswordRouteRoute: typeof legacyAuthResetPasswordRouteRoute
  OrganizationsOrganizationNameRouteRoute: typeof OrganizationsOrganizationNameRouteRouteWithChildren
  OrganizationsNewRouteRoute: typeof OrganizationsNewRouteRoute
  SitesPageNameRouteRoute: typeof SitesPageNameRouteRoute
  UserEditformRouteRoute: typeof UserEditformRouteRouteWithChildren
  UsersLoginformRouteRoute: typeof UsersLoginformRouteRoute
  UsersSignupformRouteRoute: typeof UsersSignupformRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projectform': {
      id: '/projectform'
      path: '/projectform'
      fullPath: '/projectform'
      preLoaderRoute: typeof ProjectformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lostPassword': {
      id: '/lostPassword'
      path: '/lostPassword'
      fullPath: '/lostPassword'
      preLoaderRoute: typeof LostPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/signupform': {
      id: '/users/signupform'
      path: '/users/signupform'
      fullPath: '/users/signupform'
      preLoaderRoute: typeof UsersSignupformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/loginform': {
      id: '/users/loginform'
      path: '/users/loginform'
      fullPath: '/users/loginform'
      preLoaderRoute: typeof UsersLoginformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/editform': {
      id: '/user/editform'
      path: '/user/editform'
      fullPath: '/user/editform'
      preLoaderRoute: typeof UserEditformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$pageName': {
      id: '/sites/$pageName'
      path: '/sites/$pageName'
      fullPath: '/sites/$pageName'
      preLoaderRoute: typeof SitesPageNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationName': {
      id: '/organizations/$organizationName'
      path: '/organizations/$organizationName'
      fullPath: '/organizations/$organizationName'
      preLoaderRoute: typeof OrganizationsOrganizationNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy-auth)/reset-password': {
      id: '/(legacy-auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof legacyAuthResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$projectName': {
      id: '/$owner/$projectName'
      path: '/$owner/$projectName'
      fullPath: '/$owner/$projectName'
      preLoaderRoute: typeof OwnerProjectNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/editform/': {
      id: '/user/editform/'
      path: '/'
      fullPath: '/user/editform/'
      preLoaderRoute: typeof UserEditformIndexRouteImport
      parentRoute: typeof UserEditformRouteRoute
    }
    '/organizations/$organizationName/': {
      id: '/organizations/$organizationName/'
      path: '/'
      fullPath: '/organizations/$organizationName/'
      preLoaderRoute: typeof OrganizationsOrganizationNameIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationNameRouteRoute
    }
    '/$owner/$projectName/': {
      id: '/$owner/$projectName/'
      path: '/'
      fullPath: '/$owner/$projectName/'
      preLoaderRoute: typeof OwnerProjectNameIndexRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/user/editform/token': {
      id: '/user/editform/token'
      path: '/token'
      fullPath: '/user/editform/token'
      preLoaderRoute: typeof UserEditformTokenRouteRouteImport
      parentRoute: typeof UserEditformRouteRoute
    }
    '/user/editform/password': {
      id: '/user/editform/password'
      path: '/password'
      fullPath: '/user/editform/password'
      preLoaderRoute: typeof UserEditformPasswordRouteRouteImport
      parentRoute: typeof UserEditformRouteRoute
    }
    '/user/editform/notifications': {
      id: '/user/editform/notifications'
      path: '/notifications'
      fullPath: '/user/editform/notifications'
      preLoaderRoute: typeof UserEditformNotificationsRouteRouteImport
      parentRoute: typeof UserEditformRouteRoute
    }
    '/user/editform/emails': {
      id: '/user/editform/emails'
      path: '/emails'
      fullPath: '/user/editform/emails'
      preLoaderRoute: typeof UserEditformEmailsRouteRouteImport
      parentRoute: typeof UserEditformRouteRoute
    }
    '/organizations/$organizationName/settingform': {
      id: '/organizations/$organizationName/settingform'
      path: '/settingform'
      fullPath: '/organizations/$organizationName/settingform'
      preLoaderRoute: typeof OrganizationsOrganizationNameSettingformRouteRouteImport
      parentRoute: typeof OrganizationsOrganizationNameRouteRoute
    }
    '/organizations/$organizationName/pullrequests': {
      id: '/organizations/$organizationName/pullrequests'
      path: '/pullrequests'
      fullPath: '/organizations/$organizationName/pullrequests'
      preLoaderRoute: typeof OrganizationsOrganizationNamePullrequestsRouteRouteImport
      parentRoute: typeof OrganizationsOrganizationNameRouteRoute
    }
    '/organizations/$organizationName/issues': {
      id: '/organizations/$organizationName/issues'
      path: '/issues'
      fullPath: '/organizations/$organizationName/issues'
      preLoaderRoute: typeof OrganizationsOrganizationNameIssuesRouteRouteImport
      parentRoute: typeof OrganizationsOrganizationNameRouteRoute
    }
    '/organizations/$organizationName/closedPullrequests': {
      id: '/organizations/$organizationName/closedPullrequests'
      path: '/closedPullrequests'
      fullPath: '/organizations/$organizationName/closedPullrequests'
      preLoaderRoute: typeof OrganizationsOrganizationNameClosedPullrequestsRouteRouteImport
      parentRoute: typeof OrganizationsOrganizationNameRouteRoute
    }
    '/organizations/$organizationName/boards': {
      id: '/organizations/$organizationName/boards'
      path: '/boards'
      fullPath: '/organizations/$organizationName/boards'
      preLoaderRoute: typeof OrganizationsOrganizationNameBoardsRouteRouteImport
      parentRoute: typeof OrganizationsOrganizationNameRouteRoute
    }
    '/me/settings/token': {
      id: '/me/settings/token'
      path: '/settings/token'
      fullPath: '/me/settings/token'
      preLoaderRoute: typeof MeSettingsTokenRouteRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/settings/profile': {
      id: '/me/settings/profile'
      path: '/settings/profile'
      fullPath: '/me/settings/profile'
      preLoaderRoute: typeof MeSettingsProfileRouteRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/settings/password': {
      id: '/me/settings/password'
      path: '/settings/password'
      fullPath: '/me/settings/password'
      preLoaderRoute: typeof MeSettingsPasswordRouteRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/settings/notifications': {
      id: '/me/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/me/settings/notifications'
      preLoaderRoute: typeof MeSettingsNotificationsRouteRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/settings/emails': {
      id: '/me/settings/emails'
      path: '/settings/emails'
      fullPath: '/me/settings/emails'
      preLoaderRoute: typeof MeSettingsEmailsRouteRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/$owner/$projectName/settingform': {
      id: '/$owner/$projectName/settingform'
      path: '/settingform'
      fullPath: '/$owner/$projectName/settingform'
      preLoaderRoute: typeof OwnerProjectNameSettingformRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/sentPullRequests': {
      id: '/$owner/$projectName/sentPullRequests'
      path: '/sentPullRequests'
      fullPath: '/$owner/$projectName/sentPullRequests'
      preLoaderRoute: typeof OwnerProjectNameSentPullRequestsRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/pullRequests': {
      id: '/$owner/$projectName/pullRequests'
      path: '/pullRequests'
      fullPath: '/$owner/$projectName/pullRequests'
      preLoaderRoute: typeof OwnerProjectNamePullRequestsRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/posts': {
      id: '/$owner/$projectName/posts'
      path: '/posts'
      fullPath: '/$owner/$projectName/posts'
      preLoaderRoute: typeof OwnerProjectNamePostsRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/issues': {
      id: '/$owner/$projectName/issues'
      path: '/issues'
      fullPath: '/$owner/$projectName/issues'
      preLoaderRoute: typeof OwnerProjectNameIssuesRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/code': {
      id: '/$owner/$projectName/code'
      path: '/code'
      fullPath: '/$owner/$projectName/code'
      preLoaderRoute: typeof OwnerProjectNameCodeRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/closedPullRequests': {
      id: '/$owner/$projectName/closedPullRequests'
      path: '/closedPullRequests'
      fullPath: '/$owner/$projectName/closedPullRequests'
      preLoaderRoute: typeof OwnerProjectNameClosedPullRequestsRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/pullRequest/$pullRequestNumber': {
      id: '/$owner/$projectName/pullRequest/$pullRequestNumber'
      path: '/pullRequest/$pullRequestNumber'
      fullPath: '/$owner/$projectName/pullRequest/$pullRequestNumber'
      preLoaderRoute: typeof OwnerProjectNamePullRequestPullRequestNumberRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/post/$postNumber': {
      id: '/$owner/$projectName/post/$postNumber'
      path: '/post/$postNumber'
      fullPath: '/$owner/$projectName/post/$postNumber'
      preLoaderRoute: typeof OwnerProjectNamePostPostNumberRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
    '/$owner/$projectName/issue/$issueNumber': {
      id: '/$owner/$projectName/issue/$issueNumber'
      path: '/issue/$issueNumber'
      fullPath: '/$owner/$projectName/issue/$issueNumber'
      preLoaderRoute: typeof OwnerProjectNameIssueIssueNumberRouteRouteImport
      parentRoute: typeof OwnerProjectNameRouteRoute
    }
  }
}

interface MeRouteRouteChildren {
  MeSettingsEmailsRouteRoute: typeof MeSettingsEmailsRouteRoute
  MeSettingsNotificationsRouteRoute: typeof MeSettingsNotificationsRouteRoute
  MeSettingsPasswordRouteRoute: typeof MeSettingsPasswordRouteRoute
  MeSettingsProfileRouteRoute: typeof MeSettingsProfileRouteRoute
  MeSettingsTokenRouteRoute: typeof MeSettingsTokenRouteRoute
}

const MeRouteRouteChildren: MeRouteRouteChildren = {
  MeSettingsEmailsRouteRoute: MeSettingsEmailsRouteRoute,
  MeSettingsNotificationsRouteRoute: MeSettingsNotificationsRouteRoute,
  MeSettingsPasswordRouteRoute: MeSettingsPasswordRouteRoute,
  MeSettingsProfileRouteRoute: MeSettingsProfileRouteRoute,
  MeSettingsTokenRouteRoute: MeSettingsTokenRouteRoute,
}

const MeRouteRouteWithChildren =
  MeRouteRoute._addFileChildren(MeRouteRouteChildren)

interface ProjectsRouteRouteChildren {
  ProjectsNewRouteRoute: typeof ProjectsNewRouteRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsNewRouteRoute: ProjectsNewRouteRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface OwnerProjectNameRouteRouteChildren {
  OwnerProjectNameClosedPullRequestsRouteRoute: typeof OwnerProjectNameClosedPullRequestsRouteRoute
  OwnerProjectNameCodeRouteRoute: typeof OwnerProjectNameCodeRouteRoute
  OwnerProjectNameIssuesRouteRoute: typeof OwnerProjectNameIssuesRouteRoute
  OwnerProjectNamePostsRouteRoute: typeof OwnerProjectNamePostsRouteRoute
  OwnerProjectNamePullRequestsRouteRoute: typeof OwnerProjectNamePullRequestsRouteRoute
  OwnerProjectNameSentPullRequestsRouteRoute: typeof OwnerProjectNameSentPullRequestsRouteRoute
  OwnerProjectNameSettingformRouteRoute: typeof OwnerProjectNameSettingformRouteRoute
  OwnerProjectNameIndexRoute: typeof OwnerProjectNameIndexRoute
  OwnerProjectNameIssueIssueNumberRouteRoute: typeof OwnerProjectNameIssueIssueNumberRouteRoute
  OwnerProjectNamePostPostNumberRouteRoute: typeof OwnerProjectNamePostPostNumberRouteRoute
  OwnerProjectNamePullRequestPullRequestNumberRouteRoute: typeof OwnerProjectNamePullRequestPullRequestNumberRouteRoute
}

const OwnerProjectNameRouteRouteChildren: OwnerProjectNameRouteRouteChildren = {
  OwnerProjectNameClosedPullRequestsRouteRoute:
    OwnerProjectNameClosedPullRequestsRouteRoute,
  OwnerProjectNameCodeRouteRoute: OwnerProjectNameCodeRouteRoute,
  OwnerProjectNameIssuesRouteRoute: OwnerProjectNameIssuesRouteRoute,
  OwnerProjectNamePostsRouteRoute: OwnerProjectNamePostsRouteRoute,
  OwnerProjectNamePullRequestsRouteRoute:
    OwnerProjectNamePullRequestsRouteRoute,
  OwnerProjectNameSentPullRequestsRouteRoute:
    OwnerProjectNameSentPullRequestsRouteRoute,
  OwnerProjectNameSettingformRouteRoute: OwnerProjectNameSettingformRouteRoute,
  OwnerProjectNameIndexRoute: OwnerProjectNameIndexRoute,
  OwnerProjectNameIssueIssueNumberRouteRoute:
    OwnerProjectNameIssueIssueNumberRouteRoute,
  OwnerProjectNamePostPostNumberRouteRoute:
    OwnerProjectNamePostPostNumberRouteRoute,
  OwnerProjectNamePullRequestPullRequestNumberRouteRoute:
    OwnerProjectNamePullRequestPullRequestNumberRouteRoute,
}

const OwnerProjectNameRouteRouteWithChildren =
  OwnerProjectNameRouteRoute._addFileChildren(
    OwnerProjectNameRouteRouteChildren,
  )

interface OrganizationsOrganizationNameRouteRouteChildren {
  OrganizationsOrganizationNameBoardsRouteRoute: typeof OrganizationsOrganizationNameBoardsRouteRoute
  OrganizationsOrganizationNameClosedPullrequestsRouteRoute: typeof OrganizationsOrganizationNameClosedPullrequestsRouteRoute
  OrganizationsOrganizationNameIssuesRouteRoute: typeof OrganizationsOrganizationNameIssuesRouteRoute
  OrganizationsOrganizationNamePullrequestsRouteRoute: typeof OrganizationsOrganizationNamePullrequestsRouteRoute
  OrganizationsOrganizationNameSettingformRouteRoute: typeof OrganizationsOrganizationNameSettingformRouteRoute
  OrganizationsOrganizationNameIndexRoute: typeof OrganizationsOrganizationNameIndexRoute
}

const OrganizationsOrganizationNameRouteRouteChildren: OrganizationsOrganizationNameRouteRouteChildren =
  {
    OrganizationsOrganizationNameBoardsRouteRoute:
      OrganizationsOrganizationNameBoardsRouteRoute,
    OrganizationsOrganizationNameClosedPullrequestsRouteRoute:
      OrganizationsOrganizationNameClosedPullrequestsRouteRoute,
    OrganizationsOrganizationNameIssuesRouteRoute:
      OrganizationsOrganizationNameIssuesRouteRoute,
    OrganizationsOrganizationNamePullrequestsRouteRoute:
      OrganizationsOrganizationNamePullrequestsRouteRoute,
    OrganizationsOrganizationNameSettingformRouteRoute:
      OrganizationsOrganizationNameSettingformRouteRoute,
    OrganizationsOrganizationNameIndexRoute:
      OrganizationsOrganizationNameIndexRoute,
  }

const OrganizationsOrganizationNameRouteRouteWithChildren =
  OrganizationsOrganizationNameRouteRoute._addFileChildren(
    OrganizationsOrganizationNameRouteRouteChildren,
  )

interface UserEditformRouteRouteChildren {
  UserEditformEmailsRouteRoute: typeof UserEditformEmailsRouteRoute
  UserEditformNotificationsRouteRoute: typeof UserEditformNotificationsRouteRoute
  UserEditformPasswordRouteRoute: typeof UserEditformPasswordRouteRoute
  UserEditformTokenRouteRoute: typeof UserEditformTokenRouteRoute
  UserEditformIndexRoute: typeof UserEditformIndexRoute
}

const UserEditformRouteRouteChildren: UserEditformRouteRouteChildren = {
  UserEditformEmailsRouteRoute: UserEditformEmailsRouteRoute,
  UserEditformNotificationsRouteRoute: UserEditformNotificationsRouteRoute,
  UserEditformPasswordRouteRoute: UserEditformPasswordRouteRoute,
  UserEditformTokenRouteRoute: UserEditformTokenRouteRoute,
  UserEditformIndexRoute: UserEditformIndexRoute,
}

const UserEditformRouteRouteWithChildren =
  UserEditformRouteRoute._addFileChildren(UserEditformRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  LostPasswordRouteRoute: LostPasswordRouteRoute,
  MeRouteRoute: MeRouteRouteWithChildren,
  OrgsRouteRoute: OrgsRouteRoute,
  ProjectformRouteRoute: ProjectformRouteRoute,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRoute,
  ResetPasswordRouteRoute: ResetPasswordRouteRoute,
  SearchRouteRoute: SearchRouteRoute,
  OwnerProjectNameRouteRoute: OwnerProjectNameRouteRouteWithChildren,
  legacyAuthResetPasswordRouteRoute: legacyAuthResetPasswordRouteRoute,
  OrganizationsOrganizationNameRouteRoute:
    OrganizationsOrganizationNameRouteRouteWithChildren,
  OrganizationsNewRouteRoute: OrganizationsNewRouteRoute,
  SitesPageNameRouteRoute: SitesPageNameRouteRoute,
  UserEditformRouteRoute: UserEditformRouteRouteWithChildren,
  UsersLoginformRouteRoute: UsersLoginformRouteRoute,
  UsersSignupformRouteRoute: UsersSignupformRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
