use super::EndpointStatus;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthRequirement {
    AuthorizationTokenHeader,
    AuthorizationTokenOrImportSession,
    CurrentUserSession,
    IssueCreatePermission,
    IssueUpdatePermission,
    ProjectReadJsonAccept,
    AnonymousJsonAccept,
    LoginSession,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MigrationDirection {
    Export,
    Import,
    Deferred,
    AppOwned,
}

impl MigrationDirection {
    pub const fn endpoint_status(self) -> EndpointStatus {
        match self {
            Self::Export => EndpointStatus::MigratorExport,
            Self::Import => EndpointStatus::MigratorImport,
            Self::Deferred => EndpointStatus::MigratorDeferred,
            Self::AppOwned => EndpointStatus::AppOwned,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FixtureShape {
    pub path_fields: &'static [&'static str],
    pub query_fields: &'static [&'static str],
    pub header_fields: &'static [&'static str],
    pub body_fields: &'static [&'static str],
    pub response_fields: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct IssueEndpointFixture {
    pub method: &'static str,
    pub path: &'static str,
    pub legacy_controller: &'static str,
    pub legacy_action: &'static str,
    pub direction: MigrationDirection,
    pub auth: AuthRequirement,
    pub request: FixtureShape,
    pub response: FixtureShape,
}

pub fn fixtures() -> &'static [IssueEndpointFixture] {
    ISSUE_ENDPOINT_FIXTURES
}

pub fn find_fixture(method: &str, path: &str) -> Option<&'static IssueEndpointFixture> {
    ISSUE_ENDPOINT_FIXTURES
        .iter()
        .find(|fixture| fixture.method == method && fixture.path == path)
}

const fn shape(
    path_fields: &'static [&'static str],
    query_fields: &'static [&'static str],
    header_fields: &'static [&'static str],
    body_fields: &'static [&'static str],
    response_fields: &'static [&'static str],
) -> FixtureShape {
    FixtureShape {
        path_fields,
        query_fields,
        header_fields,
        body_fields,
        response_fields,
    }
}

const ISSUE_ENDPOINT_FIXTURES: &[IssueEndpointFixture] = &[
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/imports",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "imports",
        direction: MigrationDirection::Import,
        auth: AuthRequirement::CurrentUserSession,
        request: shape(
            &["owner", "projectName"],
            &["postNumber"],
            &[],
            &[],
            &["badRequest"],
        ),
        response: shape(&[], &[], &[], &[], &["number"]),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "newIssues",
        direction: MigrationDirection::Import,
        auth: AuthRequirement::IssueCreatePermission,
        request: shape(
            &["owner", "projectName"],
            &[],
            &[],
            &[
                "issues",
                "sendNotification",
                "author",
                "title",
                "body",
                "state",
                "createdAt",
                "updatedAt",
                "assignees",
                "milestoneTitle",
                "dueDate",
                "labels",
                "temporaryUploadFiles",
                "number",
            ],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["status", "location"]),
    },
    IssueEndpointFixture {
        method: "GET",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "getIssue",
        direction: MigrationDirection::Export,
        auth: AuthRequirement::AuthorizationTokenHeader,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &["Authorization"],
            &[],
            &["message"],
        ),
        response: shape(
            &[],
            &[],
            &[],
            &[],
            &[
                "result",
                "id",
                "number",
                "title",
                "body",
                "state",
                "author",
                "assignee",
                "labels",
                "milestone",
                "comments",
                "events",
                "eventType",
                "oldValue",
                "newValue",
                "actor",
            ],
        ),
    },
    IssueEndpointFixture {
        method: "PUT",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateIssue",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::AuthorizationTokenHeader,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &["Authorization"],
            &["title", "body", "state", "assignees", "milestoneTitle"],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["result", "events"]),
    },
    IssueEndpointFixture {
        method: "PATCH",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateIssueState",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::AuthorizationTokenHeader,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &["Authorization"],
            &["state"],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["result", "state", "events"]),
    },
    IssueEndpointFixture {
        method: "PATCH",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/content",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateIssueContent",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::IssueUpdatePermission,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &["content", "original"],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["storedContent", "body"]),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/comments",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "newIssueComment",
        direction: MigrationDirection::Import,
        auth: AuthRequirement::AuthorizationTokenOrImportSession,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &["Authorization"],
            &[
                "comment",
                "author",
                "body",
                "createdAt",
                "temporaryUploadFiles",
            ],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["status", "location", "result"]),
    },
    IssueEndpointFixture {
        method: "PUT",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/comments/:commentId",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateIssueComment",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::IssueUpdatePermission,
        request: shape(
            &["owner", "projectName", "number", "commentId"],
            &[],
            &[],
            &["content", "original"],
            &["message"],
        ),
        response: shape(
            &[],
            &[],
            &[],
            &[],
            &["result", "id", "contents", "createdDate", "author"],
        ),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/commentNotiReceivers",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "commentNotiRecivers",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::CurrentUserSession,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &["comment", "parentCommentId"],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["receivers", "loginId", "name"]),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issuelabel/:number",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateIssueLabel",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::CurrentUserSession,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &["labelId"],
            &[],
        ),
        response: shape(&[], &[], &[], &[], &["id", "labels"]),
    },
    IssueEndpointFixture {
        method: "GET",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/assignableUsers",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "findAssignableUsers",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::ProjectReadJsonAccept,
        request: shape(
            &["owner", "projectName", "number"],
            &["query", "type"],
            &["Accept"],
            &[],
            &[],
        ),
        response: shape(
            &[],
            &[],
            &["Content-Range"],
            &[],
            &["loginId", "name", "avatarUrl"],
        ),
    },
    IssueEndpointFixture {
        method: "GET",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/assignableUsers",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "findAssignableUsersOfProject",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::ProjectReadJsonAccept,
        request: shape(
            &["owner", "projectName"],
            &["query", "type"],
            &["Accept"],
            &[],
            &[],
        ),
        response: shape(
            &[],
            &[],
            &["Content-Range"],
            &[],
            &["loginId", "name", "avatarUrl"],
        ),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/assignees",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateAssginees",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::IssueUpdatePermission,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &["assignees"],
            &["message"],
        ),
        response: shape(
            &[],
            &[],
            &[],
            &[],
            &["assignee", "loginId", "name", "issue"],
        ),
    },
    IssueEndpointFixture {
        method: "GET",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/findSharer",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "findSharerByloginIds",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::AnonymousJsonAccept,
        request: shape(
            &["owner", "projectName", "number"],
            &["query"],
            &["Accept"],
            &[],
            &[],
        ),
        response: shape(&[], &[], &[], &[], &["loginId", "name", "avatarUrl"]),
    },
    IssueEndpointFixture {
        method: "GET",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/sharableUsers",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "findSharableUsers",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::ProjectReadJsonAccept,
        request: shape(
            &["owner", "projectName", "number"],
            &["query", "type"],
            &["Accept"],
            &[],
            &[],
        ),
        response: shape(
            &[],
            &[],
            &["Content-Range"],
            &[],
            &["loginId", "name", "avatarUrl", "projectName"],
        ),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/share",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "updateSharer",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::IssueUpdatePermission,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &["sharer", "type", "loginId", "action"],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["action", "sharer"]),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/upvoteWeight",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "upvoteWeight",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::IssueUpdatePermission,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &[],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["weight"]),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/downvoteWeight",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "downvoteWeight",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::IssueUpdatePermission,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &[],
            &["message"],
        ),
        response: shape(&[], &[], &[], &[], &["weight"]),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/owners/:owner/projects/:projectName/issues/:number/detectChange",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "detectChange",
        direction: MigrationDirection::Deferred,
        auth: AuthRequirement::CurrentUserSession,
        request: shape(
            &["owner", "projectName", "number"],
            &[],
            &[],
            &["issueBodyChecksum", "numOfComments"],
            &["message"],
        ),
        response: shape(
            &[],
            &[],
            &[],
            &[],
            &[
                "result",
                "commentAuthorName",
                "issueBodyChanged",
                "numOfComments",
                "issueBodyChecksum",
                "issueUpdateDate",
            ],
        ),
    },
    IssueEndpointFixture {
        method: "POST",
        path: "/-_-api/v1/translation",
        legacy_controller: "controllers.api.IssueApi",
        legacy_action: "translate",
        direction: MigrationDirection::AppOwned,
        auth: AuthRequirement::LoginSession,
        request: shape(
            &[],
            &[],
            &[],
            &["owner", "projectName", "type", "number"],
            &[],
        ),
        response: shape(&[], &[], &[], &[], &["translated", "Precondition Failed"]),
    },
];
