import * as stylex from "@stylexjs/stylex";

export const commitDetailColors = stylex.defineVars({
  diffBorder: "#bbbbbb",
  diffMetaSurface: "#eeeeee",
  commitText: "#333333",
  diffSurface: "#f5f5f5",
  link: "#3592b5",
  metaText: "#999999",
});

export const styles = stylex.create({
  inlineCommentRow: { display: "table-row" },
  inlineCommentCell: { padding: "0px" },
  blockReviewButtonHidden: { display: "none" },
  blockReviewButtonVisible: { display: "block" },
  commentBodyHidden: { display: "none" },
  commentUpdateFormHidden: { display: "none" },
  commentUpdateFormVisible: { display: "block" },
  browseTabs: { marginBottom: "20px" },
  reviewTabs: { marginBottom: "10px" },
  markdownEditorWrapper: { marginTop: "10px" },
  editorTabContent: { overflow: "visible", position: "relative" },
  reviewTextarea: { height: "100px" },
  reviewFormHidden: { display: "none" },
  reviewFormVisible: { display: "block" },
  reviewFormShell: {
    padding: "0px 10px",
    paddingRight: "6px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    borderRadius: "6px",
  },
  reviewAuthorInfoWrap: {
    padding: "0px",
    marginBottom: "10px",
    display: "block",
    clear: "both",
    height: "35px",
  },
  reviewWriteCommentBox: {
    padding: "0px",
    margin: "0px",
    marginLeft: "46px",
    "@media all and (max-width: 720px)": { marginLeft: "0px" },
  },
  diffLineNumber: {
    textAlign: "right",
    color: "rgba(0, 0, 0, 0.3)",
    whiteSpace: "nowrap",
    borderRight: "1px solid #e5e5e5",
    width: "50px",
    padding: "0px 3px",
    userSelect: "none",
    cursor: "pointer",
  },
  diffLineNumberMarker: {
    width: "50px",
    height: "20px",
    position: "relative",
    "::before": {
      position: "absolute",
      content: "attr(data-line-num)",
      width: "50px",
      display: "block",
    },
  },
  diffLineCommentIcon: {
    position: "absolute",
    cursor: "pointer",
    opacity: 0,
    marginLeft: "-84px",
    width: "25px",
    marginTop: "2px",
  },
  diffCodeCell: { whiteSpace: "nowrap", padding: "0px 5px" },
  diffCodeLine: {
    fontFamily: 'Consolas, "Menlo", "Monaco", "Ubuntu Mono", "source-code-pro", monospace',
    backgroundColor: "transparent",
    borderWidth: "0px",
    borderStyle: "none",
    margin: "0px",
    padding: "0px",
    fontSize: "12px",
    whiteSpace: "pre",
  },
  diffIsBinary: {
    color: "#bbb",
    textShadow: "-1px -1px #fff",
    padding: "5px 10px",
  },
  diffPartialFile: {
    padding: "5px 10px",
    fontWeight: "bold",
    overflow: "hidden",
    whiteSpace: "nowrap",
    wordBreak: "break-all",
    marginRight: "115px",
  },
  diffPartialCommit: { float: "left" },
  diffPartialCommitId: {
    float: "left",
    padding: "5px 2px",
    fontWeight: "bold",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "#bbb",
    width: "52px",
    textAlign: "center",
  },
  diffPartialFilename: {
    color: commitDetailColors.commitText,
    fontSize: "13px",
  },
  reviewCard: {
    display: "block",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#ddd",
    padding: "10px",
    paddingLeft: "15px",
    marginBottom: "5px",
    borderRadius: "0px 3px 3px 0px",
    ":last-of-type": { marginBottom: "0px" },
    ":hover": { textDecoration: "none", backgroundColor: "#fafafa" },
  },
  reviewCardOpen: { boxShadow: "inset 5px 0px 0px #b6da54" },
  reviewCardClosed: { boxShadow: "inset 5px 0px 0px #fd6956" },
  reviewCardContent: {
    display: stylex.firstThatWorks("-webkit-box", "box"),
    overflow: "hidden",
    textOverflow: "ellipsis",
    textAlign: "justify",
    maxHeight: "60px",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    wordBreak: "break-all",
  },
  reviewCardDate: { color: "#999", verticalAlign: "middle" },
  reviewCardComments: { color: "#3592b5", marginTop: "2px", marginLeft: "1px" },
  rightText: { textAlign: "right" },
  commentDeleteModalVisible: { display: "block" },
  threadReviewForm: { display: "block" },
  threadShell: {
    backgroundColor: "#fefefe",
    border: "1px solid #e5e5e5",
    borderWidth: "1px 0px",
    maxWidth: "876px",
    padding: "5px",
    paddingBottom: "0px",
    position: "relative",
  },
  threadShellOpen: { boxShadow: "inset 5px 0px 0px #b6da54" },
  threadShellClosed: { boxShadow: "inset 5px 0px 0px #fd6956" },
  threadShellClosedFold: {
    position: "static",
    padding: "0px",
    margin: "0px",
    backgroundColor: "transparent",
    border: "none",
    borderWidth: "0px",
    borderStyle: "none",
    boxShadow: "none",
  },
  threadAfterThread: { marginTop: "10px" },
  threadAfterFoldedThread: { marginTop: "0px" },
  threadFoldHidden: { display: "none" },
  threadFoldHere: {
    position: "absolute",
    zIndex: 99,
    right: "0px",
    marginTop: "0px",
    display: "block",
  },
  threadFoldOpenButton: {
    borderLeft: "3px solid #b6da54",
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#b6da54",
  },
  threadFoldClosedButton: {
    borderLeft: "3px solid #fd6956",
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#fd6956",
  },
  threadComments: { margin: "0px 5px" },
  threadComment: { padding: "2px 0px" },
  inlineCommentItem: { maxWidth: "1150px" },
  threadMediaBody: { backgroundColor: "#fff" },
  rangedThreadMinimize: { position: "absolute", right: "10px", top: "8px" },
  threadActions: { padding: "5px 5px 10px" },
  rangedThreadHeader: { padding: "5px 10px 10px 10px" },
  rangedThreadBadge: { margin: "0px", padding: "2px 10px" },
  originalMessageToggle: {
    borderWidth: "0px",
    paddingLeft: "5px",
    paddingRight: "5px",
  },
  codediffLayout: { position: "relative" },
  diffsLayout: { display: "block", marginRight: "282px", position: "relative" },
  reviewPanel: {
    display: "block",
    minHeight: "30px",
    position: "absolute",
    right: "0px",
    top: "0px",
    width: "260px",
  },
  reviewContainer: { position: "relative", width: "260px" },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  browse: { width: "100%" },
  diffWrap: { width: "100%", overflow: "auto", marginBottom: "20px" },
  commitInfo: { color: commitDetailColors.commitText, margin: "10px 0px" },
  commitAuthor: { float: "right", marginTop: "5px" },
  commitAuthorAgo: { marginLeft: "5px", color: "#bbb" },
  commitAuthorAvatar: { marginRight: "5px" },
  commitIdWrap: { padding: "10px 5px" },
  commitId: {
    float: "right",
    color: "#51aacc",
    marginTop: "5px",
    fontFamily: 'Consolas, "Menlo", "Monaco", "Ubuntu Mono", "source-code-pro", monospace',
  },
  commitMessage: { color: commitDetailColors.commitText },
  commitDescription: {
    backgroundColor: commitDetailColors.diffSurface,
    color: commitDetailColors.commitText,
    margin: "5px 0px",
    padding: "10px",
    whiteSpace: "pre-wrap",
  },
  footerWatchLeft: { float: "left" },
  footerListRight: { float: "right" },
  diffBody: {
    fontFamily: '"monospace", Consolas, Tahoma',
    overflowX: "auto",
    position: "relative",
    borderRadius: "3px",
    minHeight: "30px",
  },
  file: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: commitDetailColors.diffBorder,
    marginBottom: "20px",
  },
  fileMeta: {
    backgroundColor: commitDetailColors.diffMetaSurface,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: commitDetailColors.diffBorder,
    height: "30px",
    position: "relative",
  },
  fileCode: { overflow: "auto", overflowX: "auto", overflowY: "hidden" },
  diffPartialTable: { width: "100%", borderCollapse: "separate", borderSpacing: "0px" },
  diffStatBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "10px 0px",
  },
  diffStatBadgeChanged: {
    backgroundColor: "#f0f0f0",
    color: "#333333",
    padding: "2px 10px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: 600,
  },
  diffStatBadgeAdd: {
    backgroundColor: "#e6ffec",
    color: "#1f883d",
    padding: "2px 10px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: 600,
  },
  diffStatBadgeDelete: {
    backgroundColor: "#ffebe9",
    color: "#cf222e",
    padding: "2px 10px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: 600,
  },
  fileDiffCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: commitDetailColors.diffMetaSurface,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: commitDetailColors.diffBorder,
    padding: "6px 12px",
    cursor: "pointer",
    userSelect: "none",
  },
  fileToggleIcon: {
    fontSize: "12px",
    color: "#57606a",
    marginRight: "6px",
  },
});
