import * as stylex from "@stylexjs/stylex";

export const commitDetailColors = stylex.defineVars({
  diffBorder: "#bbbbbb",
  diffMetaSurface: "#eeeeee",
  commitText: "#333333",
  diffSurface: "#f5f5f5",
  link: "#3592b5",
  metaText: "#999999",
});

export const styles = stylex.create({
  blockReviewButtonHidden: { display: "none" },
  blockReviewButtonVisible: { display: "block" },
  commentBodyHidden: { display: "none" },
  commentUpdateFormHidden: { display: "none" },
  commentUpdateFormVisible: { display: "block" },
  browseTabs: { marginBottom: "20px" },
  reviewTabs: { marginBottom: "10px" },
  editorTabContent: { overflow: "visible", position: "relative" },
  reviewTextarea: { height: "100px" },
  reviewFormHidden: { display: "none" },
  reviewFormVisible: { display: "block" },
  reviewFormShell: {
    padding: "0px 10px",
    paddingRight: "6px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    borderRadius: "6px",
  },
  reviewAuthorInfoWrap: {
    padding: "0px",
    marginBottom: "10px",
    display: "block",
    clear: "both",
    height: "35px",
  },
  reviewWriteCommentBox: {
    padding: "0px",
    margin: "0px",
    marginLeft: "46px",
    "@media all and (max-width: 720px)": { marginLeft: "0px" },
  },
  reviewCard: {
    display: "block",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#ddd",
    padding: "10px",
    paddingLeft: "15px",
    marginBottom: "5px",
    borderRadius: "0px 3px 3px 0px",
    ":last-of-type": { marginBottom: "0px" },
    ":hover": { textDecoration: "none", backgroundColor: "#fafafa" },
  },
  reviewCardOpen: { boxShadow: "inset 5px 0px 0px #b6da54" },
  reviewCardClosed: { boxShadow: "inset 5px 0px 0px #fd6956" },
  reviewCardContent: {
    display: stylex.firstThatWorks("-webkit-box", "box"),
    overflow: "hidden",
    textOverflow: "ellipsis",
    textAlign: "justify",
    maxHeight: "60px",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    wordBreak: "break-all",
  },
  reviewCardDate: { color: "#999", verticalAlign: "middle" },
  reviewCardComments: { color: "#3592b5", marginTop: "2px", marginLeft: "1px" },
  rightText: { textAlign: "right" },
  commentDeleteModalVisible: { display: "block" },
  threadReviewForm: { display: "block" },
  threadShell: {
    backgroundColor: "#fefefe",
    border: "1px solid #e5e5e5",
    borderWidth: "1px 0px",
    maxWidth: "876px",
    padding: "5px",
    paddingBottom: "0px",
    position: "relative",
  },
  threadShellOpen: { boxShadow: "inset 5px 0px 0px #b6da54" },
  threadShellClosed: { boxShadow: "inset 5px 0px 0px #fd6956" },
  threadShellClosedFold: {
    position: "static",
    padding: "0px",
    margin: "0px",
    backgroundColor: "transparent",
    border: "none",
    borderWidth: "0px",
    borderStyle: "none",
    boxShadow: "none",
  },
  threadAfterThread: { marginTop: "10px" },
  threadAfterFoldedThread: { marginTop: "0px" },
  threadFoldHidden: { display: "none" },
  threadFoldHere: {
    position: "absolute",
    zIndex: 99,
    right: "0px",
    marginTop: "0px",
    display: "block",
  },
  threadFoldOpenButton: {
    borderLeft: "3px solid #b6da54",
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#b6da54",
  },
  threadFoldClosedButton: {
    borderLeft: "3px solid #fd6956",
    borderLeftWidth: "3px",
    borderLeftStyle: "solid",
    borderLeftColor: "#fd6956",
  },
  threadComments: { margin: "0px 5px" },
  threadComment: { padding: "2px 0px" },
  threadMediaBody: { backgroundColor: "#fff" },
  rangedThreadMinimize: { position: "absolute", right: "10px", top: "8px" },
  threadActions: { padding: "5px 5px 10px" },
  rangedThreadHeader: { padding: "5px 10px 10px 10px" },
  rangedThreadBadge: { margin: "0px", padding: "2px 10px" },
  originalMessageToggle: {
    borderWidth: "0px",
    paddingLeft: "5px",
    paddingRight: "5px",
  },
  codediffLayout: { position: "relative" },
  diffsLayout: { display: "block", marginRight: "282px", position: "relative" },
  reviewPanel: {
    display: "block",
    minHeight: "30px",
    position: "absolute",
    right: "0px",
    top: "0px",
    width: "260px",
  },
  reviewContainer: { position: "relative", width: "260px" },
  page: { margin: "20px auto 0px", padding: "0px 10px", width: "100%", boxSizing: "border-box" },
  browse: { width: "100%" },
  commitInfo: { color: commitDetailColors.commitText, margin: "10px 0px" },
  commitMessage: { color: commitDetailColors.commitText },
  commitDescription: {
    backgroundColor: commitDetailColors.diffSurface,
    color: commitDetailColors.commitText,
    margin: "5px 0px",
    padding: "10px",
    whiteSpace: "pre-wrap",
  },
  diffBody: { fontFamily: '"monospace", Consolas, Tahoma', overflowX: "auto" },
  file: {
    border: `1px solid ${commitDetailColors.diffBorder}`,
    marginBottom: "20px",
  },
  fileMeta: {
    backgroundColor: commitDetailColors.diffMetaSurface,
    borderBottom: `1px solid ${commitDetailColors.diffBorder}`,
    height: "30px",
    position: "relative",
  },
  fileCode: { overflowX: "auto", overflowY: "hidden" },
});
