[package]
name = "yona-rust-pilot-migration"
edition.workspace = true
license.workspace = true
version.workspace = true
autotests = false

[dependencies]
base64.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
serde.workspace = true
serde_json.workspace = true
yona-rust-persistence = { path = "../persistence" }

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true

[[test]]
name = "migration"
path = "tests/main.rs"
