import * as stylex from "@stylexjs/stylex";

export const pullRequestDetailColors = stylex.defineVars({
  mutedText: "#777777",
  contentBorder: "#eeeeee",
  accentText: "#337581",
});

export const styles = stylex.create({
  page: { minHeight: "100%" },
  body: { minWidth: 0 },
  errorWrap: { padding: "100px 0px", textAlign: "center" },
  errorIcon: {
    display: "inline-block",
    backgroundPosition: "-80px -160px",
    backgroundRepeat: "no-repeat",
    width: "50px",
    height: "80px",
    verticalAlign: "middle",
  },
  errorIconSprite: (backgroundImage: string) => ({ backgroundImage }),
  errorMessage: {
    fontWeight: "bold",
    fontSize: "16px",
    color: "#898989",
    margin: "30px 0px",
  },
  badge: {
    display: "inline-block",
    padding: "5px 15px",
    marginRight: "25px",
    color: "#fff",
    backgroundColor: "#777",
    borderRadius: "15px",
    fontWeight: "bold",
    lineHeight: "20px",
  },
  badgeOpen: { backgroundColor: "#b6da54" },
  badgeClosed: { backgroundColor: "#fd6956" },
  badgeRejected: { backgroundColor: "#fd8658" },
  badgeMerged: { backgroundColor: "#65c9df" },
  badgeConflict: { backgroundColor: "#c0392b" },
  author: {
    color: pullRequestDetailColors.accentText,
    marginTop: "20px",
    textAlign: "left",
  },
  content: { minWidth: 0, borderColor: pullRequestDetailColors.contentBorder },
  state: { color: pullRequestDetailColors.mutedText, marginTop: "15px" },
  alert: {
    padding: "15px",
    fontSize: "13px",
    fontWeight: "bold",
    borderRadius: "3px",
  },
  alertIcon: {
    marginTop: "-2px",
    marginRight: "5px",
    fontSize: "15px",
    verticalAlign: "middle",
  },
  alertSuccess: { color: "#468847" },
  alertError: { color: "#b94a48" },
  alertWarning: { color: "#c09853" },
  conflictHelp: {
    padding: "10px",
    fontSize: "12px",
    backgroundColor: "#fefefe",
    borderRadius: "2px",
  },
  conflictList: { marginLeft: "30px" },
  conflictCode: { display: "block", fontWeight: "normal", padding: "5px", margin: "5px 0" },
  conflictButton: { margin: "0 5px", fontWeight: "normal" },
  actions: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px" },
  actionWrapper: { display: "inline-block", marginRight: "5px" },
  comments: { minWidth: 0 },
  helpActions: { textAlign: "right" },
  reviewers: { display: "inline-block", marginRight: "5px" },
  reviewerSummary: { fontSize: "13px", verticalAlign: "middle", margin: "0 10px" },
  helpModalVisible: { display: "block" },
  helpModalHidden: { display: "none" },
  branchInfoCode: {
    backgroundColor: "transparent",
    border: "none",
    color: "#2a7f8f",
    padding: "0",
  },
  branchInfoLink: { color: "#2a7f8f" },
  branchName: { color: "#51aacc" },
  branchInfoIcon: {
    backgroundImage: "none",
    color: "#2a7f8f",
    display: "inline-block",
    fontFamily: "yobicon",
    fontSize: "12px",
    fontStyle: "normal",
    fontVariant: "normal",
    fontWeight: 400,
    lineHeight: 1,
    margin: "0 5px",
    textDecoration: "none",
    verticalAlign: "baseline",
  },
  branchInfoStartIcon: { "::before": { content: '"\\e4ed"' } },
  branchInfoDirectionIcon: { "::before": { content: '"\\e504"' } },
});
