[package]
name = "yona-rust-persistence"
edition.workspace = true
license.workspace = true
version.workspace = true
autotests = false

[dependencies]
rand.workspace = true
sea-orm.workspace = true
serde.workspace = true
yona-rust-persistence-entities = { path = "../persistence-entities" }
yona-rust-search = { path = "../search" }

[dev-dependencies]
tokio.workspace = true
yona-rust-pilot-migration = { path = "../migration" }
sea-orm.workspace = true

[[test]]
name = "persistence"
path = "tests/main.rs"
