[package]
name = "yona-rust-persistence"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true
sea-orm.workspace = true
serde.workspace = true

[dev-dependencies]
tokio.workspace = true
yona-rust-pilot-migration = { path = "../migration" }
sea-orm.workspace = true
