[package]
name = "yoram-persistence"
edition.workspace = true
license.workspace = true
version.workspace = true
autotests = false

[features]
default = ["sqlite"]
sqlite = ["sea-orm/sqlx-sqlite"]
postgres = ["sea-orm/sqlx-postgres"]
mysql = ["sea-orm/sqlx-mysql"]
db-matrix = ["sqlite", "postgres", "mysql"]
cache-redis = ["redis"]

[dependencies]
async-trait.workspace = true
bcrypt.workspace = true
chrono.workspace = true
moka.workspace = true
rand.workspace = true
redis = { workspace = true, optional = true }
sea-orm.workspace = true
sea-query = "0.32"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
yoram-persistence-entities = { path = "../persistence-entities" }
yoram-search = { path = "../search" }

[dev-dependencies]
tokio.workspace = true
yoram-migration = { path = "../migration" }
sea-orm.workspace = true

[[test]]
name = "persistence"
path = "tests/main.rs"
