use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use buffa::Message;
use buffa_codegen::generated::descriptor::FileDescriptorSet;

fn main() {
    println!("cargo:rerun-if-env-changed=YONA_EMBED_ASSET_ROOT");

    generate_pilot_proto().expect("failed to compile pilot proto");

    generate_embedded_assets().expect("failed to generate embedded assets");
}

fn generate_pilot_proto() -> Result<(), Box<dyn std::error::Error>> {
    let proto_file = PathBuf::from("../../proto/yona/pilot/v1/pilot.proto");
    let proto_include = PathBuf::from("../../proto");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let descriptor_path = out_dir.join("pilot-descriptor.bin");
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("failed to resolve vendored protoc");

    let output = Command::new(protoc)
        .arg("--include_imports")
        .arg(format!(
            "--descriptor_set_out={}",
            descriptor_path.display()
        ))
        .arg(format!("--proto_path={}", proto_include.display()))
        .arg(&proto_file)
        .output()?;
    if !output.status.success() {
        return Err(format!("protoc failed: {}", String::from_utf8_lossy(&output.stderr)).into());
    }

    let descriptor_bytes = fs::read(&descriptor_path)?;
    let descriptor_set = FileDescriptorSet::decode_from_slice(&descriptor_bytes)
        .map_err(|error| format!("failed to decode FileDescriptorSet: {error}"))?;
    let files_to_generate = vec!["yona/pilot/v1/pilot.proto".to_string()];
    let mut config = buffa_codegen::CodeGenConfig::default();
    config.generate_views = true;
    config.generate_json = true;
    let generated = buffa_codegen::generate(&descriptor_set.file, &files_to_generate, &config)
        .map_err(|error| format!("failed to generate buffa proto: {error}"))?;

    let mut entries = Vec::with_capacity(generated.len());
    for file in &generated {
        let path = out_dir.join(&file.name);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, &file.content)?;
        let package = descriptor_set
            .file
            .iter()
            .find_map(|descriptor| {
                let proto_name = descriptor.name.as_deref()?;
                let rust_name = buffa_codegen::proto_path_to_rust_module(proto_name);
                (rust_name == file.name).then(|| descriptor.package.clone().unwrap_or_default())
            })
            .unwrap_or_default();
        entries.push((file.name.clone(), package));
    }

    let include_path = out_dir.join("_pilot_proto.rs");
    fs::File::create(&include_path)?.write_all(render_include_file(&entries).as_bytes())?;

    println!("cargo:rerun-if-changed={}", proto_file.display());
    Ok(())
}

fn render_include_file(entries: &[(String, String)]) -> String {
    use std::collections::BTreeMap;
    use std::fmt::Write as _;

    #[derive(Default)]
    struct Node {
        files: Vec<String>,
        children: BTreeMap<String, Node>,
    }

    let mut root = Node::default();
    for (file_name, package) in entries {
        let mut node = &mut root;
        for segment in package.split('.').filter(|segment| !segment.is_empty()) {
            node = node.children.entry(segment.to_string()).or_default();
        }
        node.files.push(file_name.clone());
    }

    fn emit(out: &mut String, node: &Node, depth: usize) {
        let indent = "    ".repeat(depth);
        for file in &node.files {
            writeln!(
                out,
                r#"{indent}include!(concat!(env!("OUT_DIR"), "/{file}"));"#
            )
            .unwrap();
        }
        for (name, child) in &node.children {
            let ident = buffa_codegen::idents::escape_mod_ident(name);
            writeln!(
                out,
                "{indent}#[allow(dead_code, non_camel_case_types, unused_imports, clippy::derivable_impls, clippy::match_single_binding)]"
            )
            .unwrap();
            writeln!(out, "{indent}pub mod {ident} {{").unwrap();
            writeln!(out, "{indent}    use super::*;").unwrap();
            emit(out, child, depth + 1);
            writeln!(out, "{indent}}}").unwrap();
        }
    }

    let mut source = String::new();
    writeln!(source, "// @generated by buffa. DO NOT EDIT.").unwrap();
    writeln!(source).unwrap();
    emit(&mut source, &root, 0);
    source
}

fn generate_embedded_assets() -> std::io::Result<()> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let source_root = std::env::var("YONA_EMBED_ASSET_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("testdata").join("embed-assets"));
    let source_root = source_root
        .canonicalize()
        .unwrap_or_else(|_| panic!("embedded asset root not found: {}", source_root.display()));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let copied_root = out_dir.join("embedded-assets");
    if copied_root.exists() {
        fs::remove_dir_all(&copied_root)?;
    }
    fs::create_dir_all(&copied_root)?;

    let mut files = Vec::new();
    copy_asset_tree(&source_root, &copied_root, &source_root, &mut files)?;
    fs::write(
        out_dir.join("_embedded_assets.rs"),
        render_embedded_assets_module(&copied_root, &files),
    )?;

    Ok(())
}

fn copy_asset_tree(
    source_root: &Path,
    target_root: &Path,
    current: &Path,
    files: &mut Vec<String>,
) -> std::io::Result<()> {
    println!("cargo:rerun-if-changed={}", current.display());

    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            copy_asset_tree(source_root, target_root, &path, files)?;
            continue;
        }

        let relative = path.strip_prefix(source_root).expect("relative asset path");
        let relative_string = relative.to_string_lossy().replace('\\', "/");
        let target = target_root.join(relative);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(&path, &target)?;
        files.push(relative_string);
    }

    Ok(())
}

fn render_embedded_assets_module(copied_root: &Path, files: &[String]) -> String {
    let mut sorted = files.to_vec();
    sorted.sort();

    let match_arms = sorted
        .iter()
        .map(|relative| {
            let full = copied_root.join(relative);
            format!(
                "        \"{relative}\" => Some(include_bytes!(r#\"{}\"#) as &'static [u8]),\n",
                full.display()
            )
        })
        .collect::<String>();

    format!(
        "pub fn get(path: &str) -> Option<&'static [u8]> {{\n    match path {{\n{match_arms}        _ => None,\n    }}\n}}\n"
    )
}
